<a href="https://colab.research.google.com/github/bbrauser/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Brad_Brauser(1)_LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####

import pandas as pd

pd.set_option('display.max_rows', 600)
pd.set_option('display.max_columns', 600)

In [2]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-06-02 21:48:31--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 35.163.140.110, 44.228.179.66, 52.89.160.109
Connecting to resources.lendingclub.com (resources.lendingclub.com)|35.163.140.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.6’

LoanStats_2018Q4.cs     [      <=>           ]  22.10M  1.96MB/s    in 13s

2020-06-02 21:48:46 (1.71 MB/s) - ‘LoanStats_2018Q4.csv.zip.6’ saved [23170772]

In [3]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: LoanStats_2018Q4.csv

In [4]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 36 months"," 14.47%","688.13","C","C2","bus driver","4 years","OWN","52000","Source Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","681xx","NE","30.65","1","Jun-1979","2","15","","6","0","15048","73%","22","w","0.00","0.00","8169.13","8169.13","5731.54","2437.59","0.0","0.0","0.0","Feb-2020","0.0","","Mar-2020","0","","1","Individual","","","","0","0","33157","0","2","1","1","8","18109","44","1","2","8628","73","20700","1","1","4","3","5526","5175","73","0","0","141","474","10","8","0","10","15","1","15","0","4","4","11","12","8","4","14","4","6","","0","0","2","95","50","0","0","61699","33157","20700","40999","","","","","","","","","","","","","","","","","688.13","","","","","","","0","0","688.13","N","","","","","",""
"","","16000","16000","16000"," 36 months"," 14.47%","550.51","C","C2","Carpenter","10+ years","RENT","150000","Source Verified","Dec-2018","Current","n","","","other","Other","917xx","CA","17.94","0","Nov-2001","1","","","24","0","43721","59.2%","29","w","9726.53","9726.53","8788.87","8788.87","6273.47","2515.40","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","","1","Individual","","","","0","0","57465","0","2","0","0","36","13744","8","0","8","7445","56","73800","0","0","3","8","2498","4117","87.2","0","0","159","205","13","13","0","13","","2","","0","7","19","7","7","4","22","25","19","24","0","0","0","0","100","85.7","0","0","116647","57465","32100","42847","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8425","8425","8425"," 36 months"," 27.27%","345.18","E","E5","Senior Director Risk Management","3 years","MORTGAGE","450000","Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","020xx","MA","12.37","0","Oct-1997","0","","","21","0","36812","65.7%","37","w","0.00","0.00","8735.1489749534","8735.15","8425.00","310.15","0.0","0.0","0.0","Feb-2019","8754.3","","Mar-2020","0","","1","Joint App","515000","16.47","Not Verified","0","0","690320","0","6","1","6","12","152382","70","1","4","9744","68","56000","7","0","5","10","34516","11632","74.6","0","0","254","89","12","12","4","18","","4","","0","6","8","8","10","16","13","17","8","21","0","0","0","2","100","50","0","0","768304","189194","45800","189054","141905","Jun-2013","0","1","4","77.4","1","4","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 12.98%","227.43","B","B5","Printer","9 years","RENT","60000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","660xx","KS","14.9","0","May-2007","0","","112","7","1","10677","54.2%","12","w","7787.21","7787.21","3805.02","3805.02","2212.79","1592.23","0.0","0.0","0.0","May-2020","227.43","Jun-2020","May-2020","0","","1","Individual","","","","0","469","27595","0","2","1","1","11","16918","103","0","1","4337","76","19700","5","0","7","2","3942","4278","67.1","0","0","139","74","20","11","0","20","","0","","0","3","5","3","4","6","5","6","5","7","0","0","0","1","100","33.3","1","0","36200","27595","13000","16500","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 26.31%","903.73","E","E4","Casino Host","10+ years","OWN","62000","Source Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","920xx","CA","37.24","0","Oct-2007","0","","86","15","1","18890","39.8%","36","w","0.00","0.00","2645.41","2645.41","754.24","1891.17","0.0","0.0","0.0","Apr-2019","903.73","","May-2020","0","","1","Individual","","","","0","0","104590","1","2","1","2","6","85700","86","0","3","5976","49","47500","4","0","8","5","6973","17510","51.9","0","0","134","104","13","6","0","13","","6","","0","5","5","7","7","20","13","16","5","15","0","0","0","1","100","14.3","1","0","138354","104590","36400","90854","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 17.97%","469.79","D","D1","Help Tech Supervisor","10+ years","MORTGAGE","92360","Source Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","300xx","GA","27.44","0","Sep-2006","1","68","","18","0","32020","49.6%","30","w","8062.80","8062.80","7497.17","7497.17","4937.20","2559.97","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","","1","Individual","","","","0","0","131919","1","2","1","3","4","17310","60","0","2","6116","53","64600","1","4","1","5","7760","7140","70.7","0","0","120","147","16","4","2","18","","4","70","0","5","12","6","7","6","15","22","12","18","0","0","0","1","90","66.7","0","0","190803","49330","24400","28861","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","6500","6500","6500"," 36 months"," 11.80%","215.28","B","B4","Educator ","2 years","RENT","46500","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","352xx","AL","21.01","0","Aug-2011","1","61","","24","0","6741","41.6%","30","w","3889.63","3889.63","3438.09","3438.09","2610.37","827.72","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","61","1","Individual","","","","0","0","40223","4","12","2","2","5","33482","97","7","12","3662","79","16200","2","0","4","14","1749","7694","42.2","0","0","88","72","1","1","0","3","","5","61","2","6","10","6","6","14","11","16","10","24","0","0","0","9","93.3","0","0","0","50845","40223","13300","34645","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 10.72%","244.55","B","B2","Program Manager","2 years","RENT","84000","Not Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","600xx","IL","3.86","0","May-2005","1","","114","9","1","2200","12.6%","17","w","0.00","0.00","2829.93","2829.93","1465.61","484.09","0.0","880.23","158.4414","Sep-2019","244.55","","Mar-2020","0","","1","Individual","","","","0","0","381442","1","5","2","2","3","18633","111","0","2","2123","61","17400","3","1","3","5","42382","15200","12.6","0","0","163","105","13","3","1","13","","3","","0","2","2","3","4","10","3","6","2","9","0","0","0","2","76.5","0","1","0","403892","20833","17400","16812","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [5]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","2926.62","2926.62","3603.44","3603.44","2673.38","930.06","0.0","0.0","0.0","May-2020","190.21","Jun-2020","May-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","5280.05","5280.05","6580.1","6580.10","4719.95","1860.15","0.0","0.0","0.0","May-2020","346.76","Jun-2020","May-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","2613.06","2613.06","3223.0","3223.00","2386.94","836.06","0.0","0.0","0.0","May-2020","169.83","Jun-2020","May-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","5133.94","5005.59","6210.56","6055.30","4866.06","1344.50","0.0","0.0","0.0","May-2020","327.68","Jun-2020","May-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","5349.59","5349.59","6756.13","6756.13","4650.41","2105.72","0.0","0.0","0.0","May-2020","356.08","Jun-2020","May-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [6]:
df = pd.read_csv('LoanStats_2018Q4.csv', header=1)

df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000.0,20000.0,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,30.65,1.0,Jun-1979,2.0,15.0,NaN,6.0,0.0,15048.0,73%,22.0,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,33157.0,0.0,2.0,1.0,1.0,8.0,18109.0,44.0,1.0,2.0,8628.0,73.0,20700.0,1.0,1.0,4.0,3.0,5526.0,5175.0,73.0,0.0,0.0,141.0,474.0,10.0,8.0,0.0,10.0,15.0,1.0,15.0,0.0,4.0,4.0,11.0,12.0,8.0,4.0,14.0,4.0,6.0,NaN,0.0,0.0,2.0,95.0,50.0,0.0,0.0,61699.0,33157.0,20700.0,40999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,16000.0,16000.0,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,other,Other,917xx,CA,17.94,0.0,Nov-2001,1.0,NaN,NaN,24.0,0.0,43721.0,59.2%,29.0,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,57465.0,0.0,2.0,0.0,0.0,36.0,13744.0,8.0,0.0,8.0,7445.0,56.0,73800.0,0.0,0.0,3.0,8.0,2498.0,4117.0,87.2,0.0,0.0,159.0,205.0,13.0,13.0,0.0,13.0,NaN,2.0,NaN,0.0,7.0,19.0,7.0,7.0,4.0,22.0,25.0,19.0,24.0,0.0,0.0,0.0,0.0,100.0,85.7,0.0,0.0,116647.0,57465.0,32100.0,42847.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,8425.0,8425.0,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0.0,Oct-1997,0.0,NaN,NaN,21.0,0.0,36812.0,65.7%,37.0,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0.0,NaN,1.0,Joint App,515000.0,16.47,Not Verified,0.0,0.0,690320.0,0.0,6.0,1.0,6.0,12.0,152382.0,70.0,1.0,4.0,9744.0,68.0,56000.0,7.0,0.0,5.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,NaN,4.0,NaN,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000.0,10000.0,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0.0,May-2007,0.0,NaN,112.0,7.0,1.0,10677.0,54.2%,12.0,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,469.0,27595.0,0.0,2.0,1.0,1.0,11.0,16918.0,103.0,0.0,1.0,4337.0,76.0,19700.0,5.0,0.0,7.0,2.0,3942.0,4278.0,67.1,0.0,0.0,139.0,74.0,20.0,11.0,0.0,20.0,NaN,0.0,NaN,0.0,3.0,5.0,3.0,4.0,6.0,5.0,6.0,5.0,7.0,0.0,0.0,0.0,1.0,100.0,33.3,1.0,0.0,36200.0,27595.0,13000.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000.0,30000.0,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,37.24,0.0,Oct-2007,0.0,NaN,86.0,15.0,1.0,18890.0,39.8%,36.0,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,104590.0,1.0,2.0,1.0,2.0,6.0,85700.0,86.0,0.0,3.0,5976.0,49.0,47500.0,4.0,0.0,8.0,5.0,6973.0,17510.0,51.9,0.0,0.0,134.0,104.0,13.0,6.0,0.0,13.0,NaN,6.0,NaN,0.0,5.0,5.0,7.0,7.0,20.0,13.0,16.0,5.0,15.0,0.0,0.0,0.0,1.0,100.0,14.3,1.0,0.0,138354.0,104590.0,36400.0,90854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1)

print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000.0,20000.0,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,30.65,1.0,Jun-1979,2.0,15.0,NaN,6.0,0.0,15048.0,73%,22.0,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,33157.0,0.0,2.0,1.0,1.0,8.0,18109.0,44.0,1.0,2.0,8628.0,73.0,20700.0,1.0,1.0,4.0,3.0,5526.0,5175.0,73.0,0.0,0.0,141.0,474.0,10.0,8.0,0.0,10.0,15.0,1.0,15.0,0.0,4.0,4.0,11.0,12.0,8.0,4.0,14.0,4.0,6.0,NaN,0.0,0.0,2.0,95.0,50.0,0.0,0.0,61699.0,33157.0,20700.0,40999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,16000.0,16000.0,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,other,Other,917xx,CA,17.94,0.0,Nov-2001,1.0,NaN,NaN,24.0,0.0,43721.0,59.2%,29.0,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,57465.0,0.0,2.0,0.0,0.0,36.0,13744.0,8.0,0.0,8.0,7445.0,56.0,73800.0,0.0,0.0,3.0,8.0,2498.0,4117.0,87.2,0.0,0.0,159.0,205.0,13.0,13.0,0.0,13.0,NaN,2.0,NaN,0.0,7.0,19.0,7.0,7.0,4.0,22.0,25.0,19.0,24.0,0.0,0.0,0.0,0.0,100.0,85.7,0.0,0.0,116647.0,57465.0,32100.0,42847.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,8425.0,8425.0,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0.0,Oct-1997,0.0,NaN,NaN,21.0,0.0,36812.0,65.7%,37.0,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0.0,NaN,1.0,Joint App,515000.0,16.47,Not Verified,0.0,0.0,690320.0,0.0,6.0,1.0,6.0,12.0,152382.0,70.0,1.0,4.0,9744.0,68.0,56000.0,7.0,0.0,5.0,10.0,34516.0,11632.0,74.6,0.0,0.0,254.0,89.0,12.0,12.0,4.0,18.0,NaN,4.0,NaN,0.0,6.0,8.0,8.0,10.0,16.0,13.0,17.0,8.0,21.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,768304.0,189194.0,45800.0,189054.0,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000.0,10000.0,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0.0,May-2007,0.0,NaN,112.0,7.0,1.0,10677.0,54.2%,12.0,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,469.0,27595.0,0.0,2.0,1.0,1.0,11.0,16918.0,103.0,0.0,1.0,4337.0,76.0,19700.0,5.0,0.0,7.0,2.0,3942.0,4278.0,67.1,0.0,0.0,139.0,74.0,20.0,11.0,0.0,20.0,NaN,0.0,NaN,0.0,3.0,5.0,3.0,4.0,6.0,5.0,6.0,5.0,7.0,0.0,0.0,0.0,1.0,100.0,33.3,1.0,0.0,36200.0,27595.0,13000.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000.0,30000.0,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,37.24,0.0,Oct-2007,0.0,NaN,86.0,15.0,1.0,18890.0,39.8%,36.0,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,104590.0,1.0,2.0,1.0,2.0,6.0,85700.0,86.0,0.0,3.0,5976.0,49.0,47500.0,4.0,0.0,8.0,5.0,6973.0,17510.0,51.9,0.0,0.0,134.0,104.0,13.0,6.0,0.0,13.0,NaN,6.0,NaN,0.0,5.0,5.0,7.0,7.0,20.0,13.0,16.0,5.0,15.0,0.0,0.0,0.0,1.0,100.0,14.3,1.0,0.0,138354.0,104590.0,36400.0,90854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isnull().sum().sort_values()

inq_fi                                             2
mo_sin_old_rev_tl_op                               2
delinq_amnt                                        2
chargeoff_within_12_mths                           2
acc_open_past_24mths                               2
inq_last_12m                                       2
total_cu_tl                                        2
total_rev_hi_lim                                   2
open_rv_24m                                        2
open_rv_12m                                        2
total_bal_il                                       2
open_il_24m                                        2
open_il_12m                                        2
open_act_il                                        2
open_acc_6m                                        2
tot_cur_bal                                        2
tot_coll_amt                                       2
acc_now_delinq                                     2
application_type                                   2
policy_code                                        2
mo_sin_rcnt_rev_tl_op                              2
collections_12_mths_ex_med                         2
mo_sin_rcnt_tl                                     2
num_accts_ever_120_pd                              2
total_il_high_credit_limit                         2
total_bc_limit                                     2
total_bal_ex_mort                                  2
tot_hi_cred_lim                                    2
tax_liens                                          2
pub_rec_bankruptcies                               2
pct_tl_nvr_dlq                                     2
num_tl_op_past_12m                                 2
num_tl_90g_dpd_24m                                 2
num_tl_30dpd                                       2
num_sats                                           2
num_rev_tl_bal_gt_0                                2
num_rev_accts                                      2
num_op_rev_tl                                      2
num_il_tl                                          2
num_bc_tl                                          2
num_bc_sats                                        2
num_actv_rev_tl                                    2
num_actv_bc_tl                                     2
mort_acc                                           2
last_pymnt_amnt                                    2
max_bal_bc                                         2
collection_recovery_fee                            2
earliest_cr_line                                   2
delinq_2yrs                                        2
addr_state                                         2
zip_code                                           2
title                                              2
purpose                                            2
pymnt_plan                                         2
loan_status                                        2
issue_d                                            2
inq_last_6mths                                     2
verification_status                                2
home_ownership                                     2
sub_grade                                          2
grade                                              2
installment                                        2
int_rate                                           2
term                                               2
funded_amnt_inv                                    2
funded_amnt                                        2
loan_amnt                                          2
annual_inc                                         2
open_acc                                           2
debt_settlement_flag                               2
total_rec_int                                      2
recoveries                                         2
total_rec_late_fee                                 2
total_rec_prncp                                    2
total_pymnt_inv                                    2
out_prncp_inv                                      2
out_prncp                                          2
initial_list_status                                2
total_acc                                          2
total_pymnt                                        2
revol_bal                                          2
pub_rec                                            2
last_credit_pull_d                                 3
avg_cur_bal                                       15
all_util                                          39
revol_util                                       158
last_pymnt_d                                     161
dti                                              239
mths_since_recent_bc                            1593
bc_open_to_buy                                  1693
percent_bc_gt_75                                1694
bc_util                                         1756
num_tl_120dpd_2m                                2861
hardship_flag                                   3198
mo_sin_old_il_acct                              4480
mths_since_rcnt_il                              4480
emp_length                                     11706
mths_since_recent_inq                          16049
il_util                                        20276
emp_title                                      20949
next_pymnt_d                                   39147
mths_since_last_delinq                         72198
mths_since_recent_revol_delinq                 91632
mths_since_last_major_derog                    99234
mths_since_recent_bc_dlq                      103245
sec_app_open_act_il                           111632
dti_joint                                     111632
sec_app_collections_12_mths_ex_med            111632
sec_app_chargeoff_within_12_mths              111632
revol_bal_joint                               111632
sec_app_earliest_cr_line                      111632
sec_app_inq_last_6mths                        111632
sec_app_mort_acc                              111632
sec_app_open_acc                              111632
annual_inc_joint                              111632
sec_app_num_rev_accts                         111632
sec_app_revol_util                            111890
hardship_amount                               112939
hardship_payoff_balance_amount                112939
hardship_last_payment_amount                  112939
orig_projected_additional_accrued_interest    112963
mths_since_last_record                        112964
verification_status_joint                     113566
hardship_dpd                                  116135
hardship_length                               116135
payment_plan_start_date                       116135
hardship_end_date                             116135
hardship_start_date                           116135
hardship_status                               116135
hardship_type                                 116135
deferral_term                                 116135
hardship_reason                               116136
hardship_loan_status                          116151
sec_app_mths_since_last_major_derog           123260
settlement_amount                             127563
settlement_status                             127563
debt_settlement_flag_date                     127563
settlement_date                               127563
settlement_term                               127563
settlement_percentage                         127563
id                                            128412
desc                                          128414
url                                           128414
member_id                                     128414
dtype: int64

In [9]:
df.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
128409,NaN,NaN,5000.0,5000.0,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1.0,Jun-2006,0.0,21.0,NaN,9.0,0.0,2597.0,27.3%,15.0,f,2613.06,2613.06,3223.00,3223.00,2386.94,836.06,0.0,0.0,0.0,May-2020,169.83,Jun-2020,May-2020,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,1413.0,69785.0,0.0,2.0,0.0,1.0,16.0,2379.0,40.0,3.0,4.0,1826.0,32.0,9500.0,0.0,0.0,1.0,5.0,8723.0,1174.0,60.9,0.0,0.0,147.0,85.0,9.0,9.0,2.0,10.0,21.0,9.0,21.0,0.0,1.0,3.0,2.0,2.0,6.0,6.0,7.0,3.0,9.0,0.0,0.0,0.0,3.0,92.9,50.0,0.0,0.0,93908.0,4976.0,3000.0,6028.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000.0,10000.0,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0.0,Oct-2008,2.0,40.0,NaN,15.0,0.0,6269.0,13.1%,25.0,f,5133.94,5005.59,6210.56,6055.30,4866.06,1344.50,0.0,0.0,0.0,May-2020,327.68,Jun-2020,May-2020,0.0,53.0,1.0,Individual,NaN,NaN,NaN,0.0,520.0,16440.0,3.0,1.0,1.0,1.0,2.0,10171.0,100.0,2.0,5.0,404.0,28.0,47700.0,0.0,3.0,5.0,6.0,1265.0,20037.0,2.3,0.0,0.0,61.0,119.0,1.0,1.0,0.0,1.0,NaN,1.0,40.0,1.0,2.0,4.0,6.0,8.0,3.0,14.0,22.0,4.0,15.0,0.0,0.0,0.0,3.0,92.0,0.0,0.0,0.0,57871.0,16440.0,20500.0,10171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000.0,10000.0,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1.0,Sep-2006,0.0,14.0,NaN,17.0,0.0,1942.0,30.8%,31.0,w,5349.59,5349.59,6756.13,6756.13,4650.41,2105.72,0.0,0.0,0.0,May-2020,356.08,Jun-2020,May-2020,0.0,25.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,59194.0,0.0,15.0,1.0,1.0,12.0,57252.0,85.0,0.0,0.0,1942.0,80.0,6300.0,0.0,5.0,0.0,1.0,3482.0,2058.0,48.5,0.0,0.0,144.0,142.0,40.0,12.0,0.0,131.0,30.0,NaN,30.0,3.0,1.0,1.0,1.0,5.0,22.0,2.0,9.0,1.0,17.0,0.0,0.0,0.0,1.0,74.2,0.0,0.0,0.0,73669.0,59194.0,4000.0,67369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128412,Total amount funded in policy code 1: 2050909275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128413,Total amount funded in policy code 2: 820109297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=2, engine='python')

print(df.shape)
df.head()

(128412, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000,20000,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,33157,0,2,1,1,8.0,18109,44.0,1,2,8628,73.0,20700,1,1,4,3,5526.0,5175.0,73.0,0,0,141.0,474,10,8,0,10.0,15.0,1.0,15.0,0,4,4,11,12,8,4,14,4,6,NaN,0,0,2,95.0,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,57465,0,2,0,0,36.0,13744,8.0,0,8,7445,56.0,73800,0,0,3,8,2498.0,4117.0,87.2,0,0,159.0,205,13,13,0,13.0,NaN,2.0,NaN,0,7,19,7,7,4,22,25,19,24,0.0,0,0,0,100.0,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,8425,8425,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0,NaN,1,Joint App,515000.0,16.47,Not Verified,0,0,690320,0,6,1,6,12.0,152382,70.0,1,4,9744,68.0,56000,7,0,5,10,34516.0,11632.0,74.6,0,0,254.0,89,12,12,4,18.0,NaN,4.0,NaN,0,6,8,8,10,16,13,17,8,21,0.0,0,0,2,100.0,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,469,27595,0,2,1,1,11.0,16918,103.0,0,1,4337,76.0,19700,5,0,7,2,3942.0,4278.0,67.1,0,0,139.0,74,20,11,0,20.0,NaN,0.0,NaN,0,3,5,3,4,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,104590,1,2,1,2,6.0,85700,86.0,0,3,5976,49.0,47500,4,0,8,5,6973.0,17510.0,51.9,0,0,134.0,104,13,6,0,13.0,NaN,6.0,NaN,0,5,5,7,7,20,13,16,5,15,0.0,0,0,1,100.0,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().sum().sort_values()

inq_fi                                             0
mo_sin_old_rev_tl_op                               0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
open_il_12m                                        0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_rcnt_rev_tl_op                              0
collections_12_mths_ex_med                         0
mo_sin_rcnt_tl                                     0
num_accts_ever_120_pd                              0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
num_tl_30dpd                                       0
num_sats                                           0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
mort_acc                                           0
last_pymnt_amnt                                    0
max_bal_bc                                         0
collection_recovery_fee                            0
earliest_cr_line                                   0
delinq_2yrs                                        0
addr_state                                         0
zip_code                                           0
title                                              0
purpose                                            0
pymnt_plan                                         0
loan_status                                        0
issue_d                                            0
inq_last_6mths                                     0
verification_status                                0
home_ownership                                     0
sub_grade                                          0
grade                                              0
installment                                        0
int_rate                                           0
term                                               0
funded_amnt_inv                                    0
funded_amnt                                        0
loan_amnt                                          0
annual_inc                                         0
open_acc                                           0
debt_settlement_flag                               0
total_rec_int                                      0
recoveries                                         0
total_rec_late_fee                                 0
total_rec_prncp                                    0
total_pymnt_inv                                    0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
total_acc                                          0
total_pymnt                                        0
revol_bal                                          0
pub_rec                                            0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
hardship_flag                                   3196
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
emp_length                                     11704
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20947
next_pymnt_d                                   39145
mths_since_last_delinq                         72196
mths_since_recent_revol_delinq                 91630
mths_since_last_major_derog                    99232
mths_since_recent_bc_dlq                      103243
sec_app_open_act_il                           111630
dti_joint                                     111630
sec_app_collections_12_mths_ex_med            111630
sec_app_chargeoff_within_12_mths              111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
annual_inc_joint                              111630
sec_app_num_rev_accts                         111630
sec_app_revol_util                            111888
hardship_amount                               112937
hardship_payoff_balance_amount                112937
hardship_last_payment_amount                  112937
orig_projected_additional_accrued_interest    112961
mths_since_last_record                        112962
verification_status_joint                     113564
hardship_dpd                                  116133
hardship_length                               116133
payment_plan_start_date                       116133
hardship_end_date                             116133
hardship_start_date                           116133
hardship_status                               116133
hardship_type                                 116133
deferral_term                                 116133
hardship_reason                               116134
hardship_loan_status                          116149
sec_app_mths_since_last_major_derog           123258
settlement_amount                             127561
settlement_status                             127561
debt_settlement_flag_date                     127561
settlement_date                               127561
settlement_term                               127561
settlement_percentage                         127561
desc                                          128412
url                                           128412
member_id                                     128412
id                                            128412
dtype: int64

In [0]:
df = df.drop(['desc', 'url', 'member_id', 'id'], axis=1)

In [13]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,20000,20000,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,33157,0,2,1,1,8.0,18109,44.0,1,2,8628,73.0,20700,1,1,4,3,5526.0,5175.0,73.0,0,0,141.0,474,10,8,0,10.0,15.0,1.0,15.0,0,4,4,11,12,8,4,14,4,6,NaN,0,0,2,95.0,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN
1,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,57465,0,2,0,0,36.0,13744,8.0,0,8,7445,56.0,73800,0,0,3,8,2498.0,4117.0,87.2,0,0,159.0,205,13,13,0,13.0,NaN,2.0,NaN,0,7,19,7,7,4,22,25,19,24,0.0,0,0,0,100.0,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,8425,8425,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0,NaN,1,Joint App,515000.0,16.47,Not Verified,0,0,690320,0,6,1,6,12.0,152382,70.0,1,4,9744,68.0,56000,7,0,5,10,34516.0,11632.0,74.6,0,0,254.0,89,12,12,4,18.0,NaN,4.0,NaN,0,6,8,8,10,16,13,17,8,21,0.0,0,0,2,100.0,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,469,27595,0,2,1,1,11.0,16918,103.0,0,1,4337,76.0,19700,5,0,7,2,3942.0,4278.0,67.1,0,0,139.0,74,20,11,0,20.0,NaN,0.0,NaN,0,3,5,3,4,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,104590,1,2,1,2,6.0,85700,86.0,0,3,5976,49.0,47500,4,0,8,5,6973.0,17510.0,51.9,0,0,134.0,104,13,6,0,13.0,NaN,6.0,NaN,0,5,5,7,7,20,13,16,5,15,0.0,0,0,1,100.0,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [15]:
df['int_rate'].head(10)

0     14.47%
1     14.47%
2     27.27%
3     12.98%
4     26.31%
5     17.97%
6     11.80%
7     10.72%
8     16.14%
9     12.98%
Name: int_rate, dtype: object

In [16]:
df['int_rate'][3]

' 12.98%'

In [17]:
df.iloc[0:10,0:2]

   loan_amnt  funded_amnt
0      20000        20000
1      16000        16000
2       8425         8425
3      10000        10000
4      30000        30000
5      13000        13000
6       6500         6500
7       7500         7500
8      14000        14000
9      25000        25000

In [0]:
int_rate = ' 12.98%'

In [19]:
int_rate.strip()

'12.98%'

In [20]:
int_rate.strip('%')

' 12.98'

In [21]:
type(int_rate.strip().strip('%'))

str

In [22]:
float(int_rate.strip().strip('%'))

12.98

In [23]:
type(float(int_rate.strip().strip('%')))

float

In [0]:
def int_rate_to_float(cell_contents):
  return float(cell_contents.strip().strip('%'))

In [25]:
int_rate_to_float(int_rate)

12.98

In [26]:
type(int_rate_to_float(int_rate))

float

In [0]:
cleaned = [ ]

for int_rate in df['int_rate']:
  cleaned.append(int_rate_to_float(int_rate))

df['int_rate_cleaned'] = pd.Series(cleaned)

In [28]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,20000,20000,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,33157,0,2,1,1,8.0,18109,44.0,1,2,8628,73.0,20700,1,1,4,3,5526.0,5175.0,73.0,0,0,141.0,474,10,8,0,10.0,15.0,1.0,15.0,0,4,4,11,12,8,4,14,4,6,NaN,0,0,2,95.0,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,57465,0,2,0,0,36.0,13744,8.0,0,8,7445,56.0,73800,0,0,3,8,2498.0,4117.0,87.2,0,0,159.0,205,13,13,0,13.0,NaN,2.0,NaN,0,7,19,7,7,4,22,25,19,24,0.0,0,0,0,100.0,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
2,8425,8425,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0,NaN,1,Joint App,515000.0,16.47,Not Verified,0,0,690320,0,6,1,6,12.0,152382,70.0,1,4,9744,68.0,56000,7,0,5,10,34516.0,11632.0,74.6,0,0,254.0,89,12,12,4,18.0,NaN,4.0,NaN,0,6,8,8,10,16,13,17,8,21,0.0,0,0,2,100.0,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,27.27
3,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,469,27595,0,2,1,1,11.0,16918,103.0,0,1,4337,76.0,19700,5,0,7,2,3942.0,4278.0,67.1,0,0,139.0,74,20,11,0,20.0,NaN,0.0,NaN,0,3,5,3,4,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,12.98
4,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,104590,1,2,1,2,6.0,85700,86.0,0,3,5976,49.0,47500,4,0,8,5,6973.0,17510.0,51.9,0,0,134.0,104,13,6,0,13.0,NaN,6.0,NaN,0,5,5,7,7,20,13,16,5,15,0.0,0,0,1,100.0,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,26.31

In [29]:
df.dtypes[-5:]

settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
int_rate_cleaned         float64
dtype: object

In [30]:
int_rates = [' 16.57%', ' 16.52%', ' 16.58%', ' 16.41%', '15.47%']

[int_rate_to_float(item) for item in int_rates]

[16.57, 16.52, 16.58, 16.41, 15.47]

In [31]:
df['int_rate'].values

array([' 14.47%', ' 14.47%', ' 27.27%', ..., ' 13.56%', ' 11.06%',
       ' 16.91%'], dtype=object)

In [32]:
df['int_rate'] = df['int_rate'].apply(int_rate_to_float)

df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,20000,20000,20000.0,36 months,14.47,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,33157,0,2,1,1,8.0,18109,44.0,1,2,8628,73.0,20700,1,1,4,3,5526.0,5175.0,73.0,0,0,141.0,474,10,8,0,10.0,15.0,1.0,15.0,0,4,4,11,12,8,4,14,4,6,NaN,0,0,2,95.0,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,16000,16000,16000.0,36 months,14.47,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,57465,0,2,0,0,36.0,13744,8.0,0,8,7445,56.0,73800,0,0,3,8,2498.0,4117.0,87.2,0,0,159.0,205,13,13,0,13.0,NaN,2.0,NaN,0,7,19,7,7,4,22,25,19,24,0.0,0,0,0,100.0,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
2,8425,8425,8425.0,36 months,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0,NaN,1,Joint App,515000.0,16.47,Not Verified,0,0,690320,0,6,1,6,12.0,152382,70.0,1,4,9744,68.0,56000,7,0,5,10,34516.0,11632.0,74.6,0,0,254.0,89,12,12,4,18.0,NaN,4.0,NaN,0,6,8,8,10,16,13,17,8,21,0.0,0,0,2,100.0,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,27.27
3,10000,10000,10000.0,60 months,12.98,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,469,27595,0,2,1,1,11.0,16918,103.0,0,1,4337,76.0,19700,5,0,7,2,3942.0,4278.0,67.1,0,0,139.0,74,20,11,0,20.0,NaN,0.0,NaN,0,3,5,3,4,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,12.98
4,30000,30000,30000.0,60 months,26.31,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,104590,1,2,1,2,6.0,85700,86.0,0,3,5976,49.0,47500,4,0,8,5,6973.0,17510.0,51.9,0,0,134.0,104,13,6,0,13.0,NaN,6.0,NaN,0,5,5,7,7,20,13,16,5,15,0.0,0,0,1,100.0,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,26.31

In [33]:
df['term'].values

array([' 36 months', ' 36 months', ' 36 months', ..., ' 36 months',
       ' 36 months', ' 36 months'], dtype=object)

In [0]:
def term_to_int(cell_contents):
  return (int(cell_contents.strip(' months')))

In [0]:
df['term'] = df['term'].apply(term_to_int)

In [39]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,20000,20000,20000.0,36,14.47,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,5731.54,2437.59,0.0,0.0,0.0,Feb-2020,0.00,NaN,Mar-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,33157,0,2,1,1,8.0,18109,44.0,1,2,8628,73.0,20700,1,1,4,3,5526.0,5175.0,73.0,0,0,141.0,474,10,8,0,10.0,15.0,1.0,15.0,0,4,4,11,12,8,4,14,4,6,NaN,0,0,2,95.0,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,16000,16000,16000.0,36,14.47,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,6273.47,2515.40,0.0,0.0,0.0,May-2020,0.00,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,57465,0,2,0,0,36.0,13744,8.0,0,8,7445,56.0,73800,0,0,3,8,2498.0,4117.0,87.2,0,0,159.0,205,13,13,0,13.0,NaN,2.0,NaN,0,7,19,7,7,4,22,25,19,24,0.0,0,0,0,100.0,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
2,8425,8425,8425.0,36,27.27,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,8425.00,310.15,0.0,0.0,0.0,Feb-2019,8754.30,NaN,Mar-2020,0,NaN,1,Joint App,515000.0,16.47,Not Verified,0,0,690320,0,6,1,6,12.0,152382,70.0,1,4,9744,68.0,56000,7,0,5,10,34516.0,11632.0,74.6,0,0,254.0,89,12,12,4,18.0,NaN,4.0,NaN,0,6,8,8,10,16,13,17,8,21,0.0,0,0,2,100.0,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,27.27
3,10000,10000,10000.0,60,12.98,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,2212.79,1592.23,0.0,0.0,0.0,May-2020,227.43,Jun-2020,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,469,27595,0,2,1,1,11.0,16918,103.0,0,1,4337,76.0,19700,5,0,7,2,3942.0,4278.0,67.1,0,0,139.0,74,20,11,0,20.0,NaN,0.0,NaN,0,3,5,3,4,6,5,6,5,7,0.0,0,0,1,100.0,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,12.98
4,30000,30000,30000.0,60,26.31,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,754.24,1891.17,0.0,0.0,0.0,Apr-2019,903.73,NaN,May-2020,0,NaN,1,Individual,NaN,NaN,NaN,0,0,104590,1,2,1,2,6.0,85700,86.0,0,3,5976,49.0,47500,4,0,8,5,6973.0,17510.0,51.9,0,0,134.0,104,13,6,0,13.0,NaN,6.0,NaN,0,5,5,7,7,20,13,16,5,15,0.0,0,0,1,100.0,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,26.31

In [41]:
## Make a column named loan_status_is_great. It should contain the integer 1 if 
## loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.


df['loan_status'].nunique()

7

In [43]:
df['loan_status'].isnull().sum()

0

In [59]:
import numpy as np

df['loan_status'].unique()

array(['Charged Off', 'Current', 'Fully Paid', 'In Grace Period',
       'Late (31-120 days)', 'Default', 'Late (16-30 days)'], dtype=object)

In [0]:
great_loan_statuses = ['Current', 'Fully Paid']

titles = ['Fully Paid',
          'Current', 
          'Charged Off', 
          'In Grace Period', 
          'Late (31-120 days)', 
          'Default', 
          'Late (16-20 days)']

def loan_status_is_great(title):
  if title not in great_loan_statuses:
    return 0
  return 1

In [64]:
[loan_status_is_great(title=title) for title in titles]

[1, 1, 0, 0, 0, 0, 0]

In [65]:
df['new_column'] = df['loan_status_is_great'(title) for title in titles]

df.head()

KeyError: ignored

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01