<a href="https://colab.research.google.com/github/fataik1/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Fatai_King_DS13_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####

import pandas as pd

In [3]:
# Open the Ames Iowa Housing Dataset:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Ames%20Housing%20Data/train.csv')

df.shape

(1460, 81)

In [4]:
df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [5]:
pd.set_option('display.max_rows', 100)

df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object
Electrical        object
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC            object
Fence             object
MiscFeature       object
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
dtype: object

In [6]:
df.isnull()

         Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0     False       False     False  ...     False          False      False
1     False       False     False  ...     False          False      False
2     False       False     False  ...     False          False      False
3     False       False     False  ...     False          False      False
4     False       False     False  ...     False          False      False
...     ...         ...       ...  ...       ...            ...        ...
1455  False       False     False  ...     False          False      False
1456  False       False     False  ...     False          False      False
1457  False       False     False  ...     False          False      False
1458  False       False     False  ...     False          False      False
1459  False       False     False  ...     False          False      False

[1460 rows x 81 columns]

In [12]:
df_small = df[['TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'SalePrice']]

df_small.head()

   TotalBsmtSF  1stFlrSF  2ndFlrSF  SalePrice
0          856       856       854     208500
1         1262      1262         0     181500
2          920       920       866     223500
3          756       961       756     140000
4         1145      1145      1053     250000

In [13]:
# Lets add up all of the square footage to get a single square footage 
# column for the entire dataset

# Using bracket syntax to make a new 'TotalSquareFootage' column

df_small['TotalSF'] = df_small['TotalBsmtSF'] + df_small['1stFlrSF'] + df_small['2ndFlrSF'] 

df_small.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   TotalBsmtSF  1stFlrSF  2ndFlrSF  SalePrice  TotalSF
0          856       856       854     208500     2566
1         1262      1262         0     181500     2524
2          920       920       866     223500     2706
3          756       961       756     140000     2473
4         1145      1145      1053     250000     3343

In [14]:
# Dot Syntax for accessing columns
df_small.TotalBsmtSF

0        856
1       1262
2        920
3        756
4       1145
        ...
1455     953
1456    1542
1457    1152
1458    1078
1459    1256
Name: TotalBsmtSF, Length: 1460, dtype: int64

In [15]:
# Bracket Syntax for accessing columns
df_small['TotalBsmtSF']

0        856
1       1262
2        920
3        756
4       1145
        ...
1455     953
1456    1542
1457    1152
1458    1078
1459    1256
Name: TotalBsmtSF, Length: 1460, dtype: int64

In [16]:
# Lets make a nother new column that is 'PricePerSqFt' by
# dividing the price by the square footage

df_small['PricePerSqFt'] = df_small['SalePrice'] / df_small['TotalSF']

df_small.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   TotalBsmtSF  1stFlrSF  2ndFlrSF  SalePrice  TotalSF  PricePerSqFt
0          856       856       854     208500     2566     81.254871
1         1262      1262         0     181500     2524     71.909667
2          920       920       866     223500     2706     82.594235
3          756       961       756     140000     2473     56.611403
4         1145      1145      1053     250000     3343     74.783129

In [17]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-02-12 00:18:28--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [             <=>    ]  21.74M   406KB/s    in 56s

2020-02-12 00:19:25 (400 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22793561]

In [19]:
#Unzip to extract the csv from the zip folder
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [20]:
#can also use bash/shell commands to look at the raw file
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","35000","35000","35000"," 36 months"," 14.47%","1204.23","C","C2","Staff Physician","8 years","MORTGAGE","360000","Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","336xx","FL","19.9","0","Apr-1995","1","","","24","0","57259","43.2%","51","w","0.00","0.00","38187.0468373662","38187.05","35000.00","3187.05","0.0","0.0","0.0","Aug-2019","29882.16","","Sep-2019","0","","1","Individual","","","","0","0","828060","0","6","1","2","9","112027","29","4","8","19118","36","132400","3","2","5","11","34503","67341","46","0","0","173","284","8","8","3","8","","0","","0","11","11","13","20","23","16","24","11","24","0","0","0","5","100","30.8","0","0","1222051","169286","124600","258401","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 22.35%","191.86","D","D5","Director of Sales","10+ years","MORTGAGE","72000","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","333xx","FL","20.12","0","Mar-2010","0","","","13","0","11720","47.1%","26","f","0.00","0.00","5615.9776735688","5615.98","5000.00","615.98","0.0","0.0","0.0","Jul-2019","4474.13","","Aug-2019","0","","1","Individual","","","","0","534","189279","0","1","0","1","18","22698","","0","0","4056","47","24900","1","0","1","2","14560","8163","55.1","0","0","105","90","29","8","5","40","","9","","0","6","11","6","8","4","11","17","11","13","0","0","0","1","100","50","0","0","218686","34418","18200","37786","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 23.40%","284.21","E","E1","","< 1 year","RENT","55000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","902xx","CA","13.51","0","Apr-2007","0","44","88","9","1","11859","53.9%","11","w","8694.39","8694.39","3675.23","3675.23","1305.61","2369.62","0.0","0.0","0.0","Jan-2020","284.21","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","21235","0","1","0","1","20","9376","76","0","3","3122","62","22000","1","0","0","4","2359","1119","89.3","0","0","140","140","13","13","0","13","","15","44","0","4","7","4","5","2","8","9","7","9","0","0","0","0","90.9","100","1","0","34386","21235","10500","12386","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","17100","17100","17100"," 36 months"," 18.94%","626.3","D","D2","Receptionist ","10+ years","RENT","38000","Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","150xx","PA","38.09","0","Mar-1998","1","47","","14","0","15323","53%","21","w","12001.54","12001.54","8114.91","8114.91","5098.46","3016.45","0.0","0.0","0.0","Jan-2020","626.3","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","43351","1","2","1","1","10","28028","67","1","5","7533","53","29170","0","0","2","6","3096","4150","77","0","0","125","230","5","5","2","5","","5","","0","4","12","5","5","5","12","14","9","14","","0","0","2","95","75","0","0","70954","43351","16600","41784","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 10.72%","130.43","B","B2","Extrusion assistant ","10+ years","MORTGAGE","56000","Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","301xx","GA","31.03","0","Sep-2006","0","","","7","0","4518","28.6%","11","w","2700.74","2700.74","1682.5","1682.50","1299.26","383.24","0.0","0.0","0.0","Jan-2020","130.43","Feb-2020","Jan-2020","1","","1","Individual","","","","0","136","192983","0","2","0","2","14","66857","","0","3","1608","29","15800","3","0","0","5","27569","7835","36.3","0","0","147","29","22","14","1","22","","17","","0","3","4","3","3","6","4","4","4","7","0","0","0","0","100","0","0","0","221310","71375","12300","77865","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10475","10475","10475"," 36 months"," 11.31%","344.48","B","B3","Teacher","6 years","RENT","66150","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","786xx","TX","7.4","0","Jun-1991","0","28","","10","0","10499","40.2%","17","w","7093.15","7093.15","4468.37","4468.37","3381.85","1086.52","0.0","0.0","0.0","Jan-2020","344.48","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","10499","1","0","0","0","84","0","","3","5","3841","40","26100","2","1","5","5","1312","14847","36.8","0","0","88","330","3","3","2","7","","1","28","0","5","8","7","8","2","10","13","8","10","0","0","0","3","88.2","60","0","0","26100","10499","23500","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 11.31%","246.65","B","B3","Supervisor","7 years","MORTGAGE","40500","Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","604xx","IL","31.61","0","Sep-1996","1","","","23","0","14218","16.3%","33","w","5653.88","5653.88","2491.74","2491.74","1846.12","630.62","15.0","0.0","0.0","Nov-2019","508.3","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","123779","3","2","1","1","12","8096","29","3","6","2972","19","87000","0","0","2","7","5626","21078","23.9","0","0","59","267","1","1","1","6","","6","","0","4","6","7","10","2","20","30","6","23","0","0","0","4","100","0","0","0","221569","22314","27700","28409","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3600","3600","3600"," 36 months"," 11.80%","119.23","B","B4","Analyst","5 years","MORTGAGE","50000","Source Verified","Dec-2018","Late (16-30 days)","n","","","other","Other","427xx","KY","16.11","0","Jan-2002","2","","","10","0","5865","17.4%","17","w","2634.82","2634.82","1325.69","1325.69","965.18","360.51","0.0","0.0","0.0","Dec-2019","119.23","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","243415","3","3","1","2","3","68184","95","1","3","0","53","33700","2","1","10","6","24342","17300","0","0","0","203","198","4","3","1","18","","3","","1","0","1","4","6","6","6","10","1","10","0","0","0","3","93.8","0","0","0","272629","74049","17300","68929","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [21]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3537.82","3537.82","2842.6","2842.60","2062.18","780.42","0.0","0.0","0.0","Jan-2020","190.21","Feb-2020","Jan-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","6368.47","6368.47","5193.06","5193.06","3631.53","1561.53","0.0","0.0","0.0","Jan-2020","346.76","Feb-2020","Jan-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3158.77","3158.77","2543.68","2543.68","1841.23","702.45","0.0","0.0","0.0","Jan-2020","169.83","Feb-2020","Jan-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","6230.02","6074.27","4899.84","4777.34","3769.98","1129.86","0.0","0.0","0.0","Jan-2020","327.68","Feb-2020","Jan-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","6433.90","6433.90","5331.81","5331.81","3566.10","1765.71","0.0","0.0","0.0","Jan-2020","356.08","Feb-2020","Jan-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [0]:
import pandas as pd
pd.set_option('display.max_rows', 150)

In [23]:
# Read in the CSV
df = pd.read_csv('LoanStats_2018Q4.csv')
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128415, 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title         emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt      total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       35000     35000       35000            36 months  14.47%  1204.23     C     C2        Staff Physician   8 years    MORTGAGE       360000     Verified            Dec-2018 Fully Paid  n          NaN NaN  credit_card        Credit card refinancing 336xx    FL         19.9  0           Apr-1995         1              NaN                    NaN                    24       0       57259     43.2%      51        w                   0.00      0.00          38187.0468373662 38187.05        35000.00        3187.05       0.0                0.0        0.0                     Aug-2019     29882.16        NaN          Sep-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            828060      0           6           1           2           9                  112027       29      4           8           19118      36       132400           3      2           5            11                   34503       67341          46      0                        0           173                284                  8                     8              3        8                    NaN                      0                     NaN                            0                     11             11              13          20        23        16            24            11                  24       0                0            0                  5                  100            30.8             0                    0         1222051         169286            124600         258401                     NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              5000      5000        5000             36 months  22.35%  191.86      D     D5        Director of Sales 10+ years  MORTGAGE       72000      Source Verified     Dec-2018 Fully Paid  n          NaN NaN  debt_consolidation Debt consolidation      333xx    FL         20.12 0           Mar-2010         0              NaN                    NaN                    13       0       11720     47.1%      26        f                   0.00      0.00          5615.9776735688  5615.98         5000.00         615.98        0.0                0.0        0.0                     Jul-2019     4474.13         NaN          Aug-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              534          189279      0           1           0           1           18                 22698        NaN     0           0           4056       47       24900            1      0           1            2                    14560       8163           55.1    0                        0           105                90                   29                    8              5        40                   NaN                      9                     NaN                            0                     6              11              6           8         4         11            17            11                  13       0                0            0                  1                  100            50               0                    0         218686          34418             18200          37786                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              10000     10000       10000            60 months  23.40%  284.21      E     E1        NaN               < 1 year   RENT           55000      Source Verified     Dec-2018 Current     n          NaN NaN  debt_consolidation Debt consolidation      902xx    CA         13.51 0           Apr-2007         0              44                     88                     9        1       11859     53.9%      11        w                   8694.39   8694.39       3675.23          3675.23         1305.61         2369.62       0.0                0.0        0.0                     Jan-2020     284.21          Feb-2020     Jan-2020           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            21235       0           1           0           1           20                 9376         76      0           3           3122       62       22000            1      0           0            4                    2359        1119           89.3    0                        0           140                140                  13                    13             0        13                   NaN                      15                    44                             0                     4              7               4           5         2         8             9             7                   9        0                0            0                  0                  90.9           100              1                    0         34386           21235             10500          12386                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              17100     17100       17100            36 months  18.94%  626.3       D     D2        Receptionist      10+ years  RENT           38000      Verified            Dec-2018 Current     n          NaN NaN  debt_consolidation Debt consolidation      150xx    PA         38.09 0           Mar-1998         1              47                     NaN                    14       0       15323     53%        21        w                   12001.54  12001.54      8114.91          8114.91         5098.46         3016.45       0.0                0.0        0.0                     Jan-2020     626.3           Feb-2020     Jan-2020           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            43351       1           2           1           1           10                 28028        67      1           5           7533       53       29170            0      0           2            6                    3096        4150           77      0                        0           125                230                  5                     5              2        5                    NaN                      5                     NaN                            0                     4              12              5           5         5         12            14            9                   14       NaN              0            0                  2                  95             75               0                    0         70954           43351             16600          41784                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

In [24]:
# We can fix the header problem by using the 'skiprows' parameter
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [25]:
# Sum null values by column and sort from least to greatest

df.isnull().sum().sort_values()

inq_fi                                             2
delinq_amnt                                        2
chargeoff_within_12_mths                           2
acc_open_past_24mths                               2
inq_last_12m                                       2
total_cu_tl                                        2
total_rev_hi_lim                                   2
max_bal_bc                                         2
open_rv_24m                                        2
open_rv_12m                                        2
total_bal_il                                       2
open_il_24m                                        2
hardship_flag                                      2
open_act_il                                        2
open_acc_6m                                        2
tot_cur_bal                                        2
tot_coll_amt                                       2
acc_now_delinq                                     2
application_type                                   2
policy_code                                        2
mo_sin_old_rev_tl_op                               2
mo_sin_rcnt_rev_tl_op                              2
mo_sin_rcnt_tl                                     2
mort_acc                                           2
total_il_high_credit_limit                         2
total_bc_limit                                     2
total_bal_ex_mort                                  2
tot_hi_cred_lim                                    2
tax_liens                                          2
pub_rec_bankruptcies                               2
pct_tl_nvr_dlq                                     2
num_tl_op_past_12m                                 2
num_tl_90g_dpd_24m                                 2
collections_12_mths_ex_med                         2
num_tl_30dpd                                       2
num_rev_tl_bal_gt_0                                2
num_rev_accts                                      2
num_op_rev_tl                                      2
num_il_tl                                          2
num_bc_tl                                          2
num_bc_sats                                        2
num_actv_rev_tl                                    2
num_actv_bc_tl                                     2
num_accts_ever_120_pd                              2
num_sats                                           2
last_pymnt_amnt                                    2
open_il_12m                                        2
debt_settlement_flag                               2
pub_rec                                            2
open_acc                                           2
grade                                              2
sub_grade                                          2
home_ownership                                     2
inq_last_6mths                                     2
annual_inc                                         2
verification_status                                2
earliest_cr_line                                   2
delinq_2yrs                                        2
issue_d                                            2
addr_state                                         2
zip_code                                           2
title                                              2
loan_status                                        2
pymnt_plan                                         2
installment                                        2
revol_bal                                          2
term                                               2
collection_recovery_fee                            2
loan_amnt                                          2
recoveries                                         2
total_rec_late_fee                                 2
funded_amnt                                        2
funded_amnt_inv                                    2
total_acc                                          2
total_rec_int                                      2
purpose                                            2
total_rec_prncp                                    2
total_pymnt_inv                                    2
total_pymnt                                        2
out_prncp_inv                                      2
out_prncp                                          2
initial_list_status                                2
int_rate                                           2
last_credit_pull_d                                 3
avg_cur_bal                                       15
all_util                                          39
revol_util                                       158
last_pymnt_d                                     161
dti                                              239
mths_since_recent_bc                            1593
bc_open_to_buy                                  1693
percent_bc_gt_75                                1694
bc_util                                         1756
num_tl_120dpd_2m                                2861
mths_since_rcnt_il                              4480
mo_sin_old_il_acct                              4480
emp_length                                     11706
mths_since_recent_inq                          16049
il_util                                        20276
emp_title                                      20949
next_pymnt_d                                   29646
mths_since_last_delinq                         72198
mths_since_recent_revol_delinq                 91632
mths_since_last_major_derog                    99234
mths_since_recent_bc_dlq                      103245
sec_app_open_acc                              111632
sec_app_mort_acc                              111632
sec_app_inq_last_6mths                        111632
sec_app_earliest_cr_line                      111632
revol_bal_joint                               111632
sec_app_open_act_il                           111632
annual_inc_joint                              111632
dti_joint                                     111632
sec_app_collections_12_mths_ex_med            111632
sec_app_chargeoff_within_12_mths              111632
sec_app_num_rev_accts                         111632
sec_app_revol_util                            111890
mths_since_last_record                        112964
verification_status_joint                     113566
sec_app_mths_since_last_major_derog           123260
debt_settlement_flag_date                     127859
settlement_date                               127859
settlement_amount                             127859
settlement_status                             127859
settlement_term                               127859
settlement_percentage                         127859
hardship_status                               128132
deferral_term                                 128132
hardship_amount                               128132
hardship_start_date                           128132
hardship_end_date                             128132
payment_plan_start_date                       128132
hardship_length                               128132
hardship_dpd                                  128132
hardship_loan_status                          128132
hardship_reason                               128132
hardship_payoff_balance_amount                128132
hardship_last_payment_amount                  128132
hardship_type                                 128132
orig_projected_additional_accrued_interest    128174
id                                            128412
url                                           128414
member_id                                     128414
desc                                          128414
dtype: int64

In [26]:
# Address the extra NaNs in each column by skipping the footer as well.
df = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=2)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

(128412, 144)

   id  member_id  ...  settlement_percentage  settlement_term
0 NaN        NaN  ...                    NaN              NaN
1 NaN        NaN  ...                    NaN              NaN
2 NaN        NaN  ...                    NaN              NaN
3 NaN        NaN  ...                    NaN              NaN
4 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [27]:
df.isnull().sum().sort_values()

inq_fi                                             0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
max_bal_bc                                         0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
hardship_flag                                      0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
collections_12_mths_ex_med                         0
num_tl_30dpd                                       0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
num_sats                                           0
last_pymnt_amnt                                    0
open_il_12m                                        0
debt_settlement_flag                               0
pub_rec                                            0
open_acc                                           0
grade                                              0
sub_grade                                          0
home_ownership                                     0
inq_last_6mths                                     0
annual_inc                                         0
verification_status                                0
earliest_cr_line                                   0
delinq_2yrs                                        0
issue_d                                            0
addr_state                                         0
zip_code                                           0
title                                              0
loan_status                                        0
pymnt_plan                                         0
installment                                        0
revol_bal                                          0
term                                               0
collection_recovery_fee                            0
loan_amnt                                          0
recoveries                                         0
total_rec_late_fee                                 0
funded_amnt                                        0
funded_amnt_inv                                    0
total_acc                                          0
total_rec_int                                      0
purpose                                            0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
int_rate                                           0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
mths_since_rcnt_il                              4478
mo_sin_old_il_acct                              4478
emp_length                                     11704
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20947
next_pymnt_d                                   29644
mths_since_last_delinq                         72196
mths_since_recent_revol_delinq                 91630
mths_since_last_major_derog                    99232
mths_since_recent_bc_dlq                      103243
sec_app_open_acc                              111630
sec_app_mort_acc                              111630
sec_app_inq_last_6mths                        111630
sec_app_earliest_cr_line                      111630
revol_bal_joint                               111630
sec_app_open_act_il                           111630
annual_inc_joint                              111630
dti_joint                                     111630
sec_app_collections_12_mths_ex_med            111630
sec_app_chargeoff_within_12_mths              111630
sec_app_num_rev_accts                         111630
sec_app_revol_util                            111888
mths_since_last_record                        112962
verification_status_joint                     113564
sec_app_mths_since_last_major_derog           123258
debt_settlement_flag_date                     127857
settlement_date                               127857
settlement_amount                             127857
settlement_status                             127857
settlement_term                               127857
settlement_percentage                         127857
hardship_status                               128130
deferral_term                                 128130
hardship_amount                               128130
hardship_start_date                           128130
hardship_end_date                             128130
payment_plan_start_date                       128130
hardship_length                               128130
hardship_dpd                                  128130
hardship_loan_status                          128130
hardship_reason                               128130
hardship_payoff_balance_amount                128130
hardship_last_payment_amount                  128130
hardship_type                                 128130
orig_projected_additional_accrued_interest    128172
url                                           128412
member_id                                     128412
desc                                          128412
id                                            128412
dtype: int64

In [0]:
df = df.drop(['url', 'member_id', 'desc', 'id'], axis=1)

In [29]:
df.head()

   loan_amnt  funded_amnt  ...  settlement_percentage settlement_term
0      35000        35000  ...                    NaN             NaN
1       5000         5000  ...                    NaN             NaN
2      10000        10000  ...                    NaN             NaN
3      17100        17100  ...                    NaN             NaN
4       4000         4000  ...                    NaN             NaN

[5 rows x 140 columns]

In [30]:
# Look at the first 10 values of the int_rate column
df['int_rate'].head(10)

0     14.47%
1     22.35%
2     23.40%
3     18.94%
4     10.72%
5     11.31%
6     11.31%
7     11.80%
8     11.80%
9     18.94%
Name: int_rate, dtype: object

In [31]:
df['int_rate'][:10]

0     14.47%
1     22.35%
2     23.40%
3     18.94%
4     10.72%
5     11.31%
6     11.31%
7     11.80%
8     11.80%
9     18.94%
Name: int_rate, dtype: object

In [32]:
# Look at a specific value from the int_rate column
df['int_rate'][0]

' 14.47%'

In [33]:
df['int_rate'].describe()

count      128412
unique         46
top        13.56%
freq         6972
Name: int_rate, dtype: object

In [0]:
# Lets start with just fixing a single string.
# If we can fix one, we can usually fix all of them

int_rate = ' 13.56%'

In [35]:
# If i call .strip() but don't pass in any values into the ()
# .strip() will remove any leading or trailing whitespace

int_rate.strip()

'13.56%'

In [36]:
int_rate.strip("%")

' 13.56'

In [37]:
int_rate.strip().strip('%')

'13.56'

In [38]:
# "Cast" the string value to a float

float("8.5")

8.5

In [39]:
float(int_rate.strip().strip('%'))

13.56

In [40]:
float(df['int_rate'][0].strip().strip('%'))

14.47

In [41]:
float(df['int_rate'][1].strip().strip('%'))

22.35

In [42]:
# We can do this with a for loop

new_int_rate = []

for cell in df['int_rate']:
  new_int_rate.append(float(cell.strip().strip('%')))

new_int_rate

[14.47,
 22.35,
 23.4,
 18.94,
 10.72,
 11.31,
 11.31,
 11.8,
 11.8,
 18.94,
 16.91,
 14.47,
 11.8,
 23.4,
 17.97,
 11.8,
 19.92,
 17.97,
 26.31,
 14.47,
 23.4,
 23.4,
 20.89,
 26.31,
 14.47,
 14.47,
 16.14,
 16.14,
 12.98,
 10.72,
 23.4,
 19.92,
 10.33,
 15.02,
 17.97,
 18.94,
 11.31,
 14.47,
 17.97,
 16.14,
 16.14,
 17.97,
 12.98,
 23.4,
 6.46,
 10.33,
 14.47,
 10.33,
 27.27,
 16.91,
 15.02,
 12.98,
 14.47,
 17.97,
 16.14,
 18.94,
 11.31,
 7.56,
 12.98,
 10.72,
 14.47,
 13.56,
 13.56,
 14.47,
 12.98,
 27.27,
 16.14,
 16.14,
 11.31,
 11.8,
 7.56,
 10.72,
 11.8,
 17.97,
 11.31,
 8.19,
 16.91,
 14.47,
 11.31,
 17.97,
 8.19,
 20.89,
 27.27,
 15.02,
 17.97,
 8.81,
 14.47,
 12.98,
 11.31,
 23.4,
 16.14,
 15.02,
 14.47,
 10.72,
 14.47,
 14.47,
 8.81,
 10.33,
 18.94,
 15.02,
 30.75,
 8.19,
 16.14,
 17.97,
 10.72,
 11.31,
 16.14,
 22.35,
 15.02,
 10.72,
 19.92,
 20.89,
 14.47,
 11.8,
 20.89,
 18.94,
 15.02,
 17.97,
 10.72,
 15.02,
 16.14,
 16.14,
 15.02,
 10.33,
 20.89,
 23.4,
 12.98,
 13.56,
 18.94,
 13.56,
 15.02,
 15.02,
 11.31,
 27.27,
 11.31,
 23.4,
 10.33,
 18.94,
 11.31,
 11.8,
 12.98,
 11.8,
 14.47,
 10.72,
 11.8,
 20.89,
 6.46,
 14.47,
 11.31,
 17.97,
 16.91,
 11.8,
 14.47,
 16.14,
 20.89,
 10.33,
 8.81,
 14.47,
 13.56,
 10.72,
 17.97,
 14.47,
 19.92,
 14.47,
 16.91,
 13.56,
 12.98,
 12.98,
 16.14,
 15.02,
 14.47,
 13.56,
 16.91,
 14.47,
 17.97,
 23.4,
 10.72,
 11.8,
 18.94,
 11.31,
 11.31,
 17.97,
 15.02,
 12.98,
 15.02,
 18.94,
 26.31,
 15.02,
 27.27,
 16.14,
 17.97,
 12.98,
 20.89,
 20.89,
 22.35,
 8.81,
 23.4,
 12.98,
 16.14,
 22.35,
 6.46,
 12.98,
 15.02,
 16.91,
 25.34,
 14.47,
 10.72,
 19.92,
 17.97,
 12.98,
 16.14,
 10.33,
 20.89,
 15.02,
 10.33,
 23.4,
 16.14,
 13.56,
 8.19,
 6.46,
 13.56,
 16.14,
 12.98,
 16.14,
 14.47,
 12.98,
 10.33,
 18.94,
 15.02,
 13.56,
 14.47,
 16.14,
 15.02,
 16.91,
 14.47,
 13.56,
 12.98,
 23.4,
 26.31,
 16.14,
 17.97,
 13.56,
 16.91,
 10.72,
 14.47,
 16.91,
 13.56,
 11.31,
 16.14,
 15.02,
 10.33,
 18.94,
 16.91,
 8.19,
 10.33,
 7.56,
 8.81,
 7.02,
 11.8,
 13.56,
 13.56,
 10.72,
 11.8,
 14.47,
 8.19,
 7.56,
 18.94,
 10.72,
 20.89,
 16.91,
 18.94,
 22.35,
 10.33,
 14.47,
 12.98,
 23.4,
 22.35,
 14.47,
 7.02,
 7.56,
 17.97,
 8.81,
 10.72,
 11.8,
 10.33,
 22.35,
 11.31,
 8.81,
 20.89,
 19.92,
 15.02,
 8.19,
 8.81,
 13.56,
 14.47,
 7.02,
 16.14,
 8.19,
 18.94,
 12.98,
 10.33,
 6.46,
 8.19,
 19.92,
 8.19,
 8.19,
 7.02,
 17.97,
 12.98,
 11.31,
 15.02,
 13.56,
 16.14,
 8.19,
 16.91,
 7.02,
 7.02,
 19.92,
 16.91,
 8.19,
 11.8,
 8.81,
 7.02,
 10.72,
 11.8,
 11.8,
 16.91,
 7.56,
 10.72,
 10.72,
 16.14,
 8.19,
 8.19,
 10.72,
 15.02,
 10.33,
 11.8,
 19.92,
 14.47,
 17.97,
 8.19,
 15.02,
 7.56,
 17.97,
 16.14,
 8.81,
 12.98,
 10.72,
 11.8,
 8.19,
 10.33,
 6.46,
 8.19,
 12.98,
 15.02,
 16.14,
 8.81,
 23.4,
 10.33,
 8.81,
 22.35,
 15.02,
 7.56,
 7.02,
 10.72,
 14.47,
 10.33,
 14.47,
 7.02,
 6.46,
 11.8,
 15.02,
 19.92,
 8.19,
 11.8,
 12.98,
 11.8,
 8.81,
 15.02,
 11.8,
 7.02,
 11.8,
 11.31,
 6.46,
 8.19,
 10.33,
 11.8,
 23.4,
 14.47,
 13.56,
 19.92,
 11.8,
 8.19,
 10.72,
 8.19,
 20.89,
 16.91,
 10.72,
 8.19,
 6.46,
 7.02,
 15.02,
 8.19,
 22.35,
 8.81,
 7.56,
 12.98,
 6.46,
 12.98,
 11.31,
 7.56,
 11.31,
 18.94,
 7.02,
 19.92,
 24.37,
 16.91,
 8.81,
 16.14,
 8.19,
 12.98,
 18.94,
 13.56,
 6.46,
 8.19,
 11.8,
 15.02,
 6.46,
 11.8,
 8.81,
 17.97,
 8.81,
 11.31,
 18.94,
 23.4,
 14.47,
 13.56,
 18.94,
 11.31,
 11.8,
 13.56,
 8.81,
 8.81,
 7.56,
 10.33,
 6.46,
 11.31,
 13.56,
 6.46,
 11.8,
 18.94,
 7.02,
 10.72,
 6.46,
 11.8,
 10.33,
 7.02,
 7.02,
 16.91,
 17.97,
 10.72,
 10.33,
 8.19,
 8.19,
 16.91,
 8.19,
 10.72,
 11.8,
 10.33,
 8.19,
 11.8,
 18.94,
 8.19,
 8.81,
 16.14,
 7.56,
 20.89,
 7.02,
 16.91,
 13.56,
 8.81,
 17.97,
 24.37,
 11.8,
 8.19,
 11.8,
 27.27,
 26.31,
 11.8,
 22.35,
 10.72,
 8.81,
 7.02,
 7.56,
 16.14,
 19.92,
 15.02,
 16.14,
 12.98,
 8.19,
 8.81,
 6.46,
 16.14,
 11.31,
 19.92,
 13.56,
 16.91,
 15.02,
 16.14,
 8.19,
 12.98,
 6.46,
 11.8,
 23.4,
 12.98,
 18.94,
 23.4,
 15.02,
 6.46,
 18.94,
 26.31,
 8.19,
 12.98,
 13.56,
 11.31,
 12.98,
 11.8,
 16.91,
 6.46,
 15.02,
 7.56,
 12.98,
 15.02,
 6.46,
 11.8,
 11.31,
 6.46,
 8.81,
 14.47,
 10.33,
 18.94,
 18.94,
 17.97,
 6.46,
 8.81,
 11.8,
 10.72,
 11.8,
 10.33,
 10.72,
 11.8,
 7.56,
 8.19,
 11.8,
 19.92,
 10.33,
 16.14,
 8.19,
 10.33,
 19.92,
 10.72,
 10.33,
 10.33,
 8.81,
 23.4,
 8.81,
 16.14,
 14.47,
 7.02,
 8.81,
 8.81,
 11.8,
 24.37,
 8.81,
 13.56,
 7.02,
 8.19,
 8.81,
 8.81,
 13.56,
 14.47,
 7.56,
 11.8,
 7.02,
 23.4,
 7.02,
 13.56,
 17.97,
 15.02,
 7.56,
 14.47,
 6.46,
 13.56,
 6.46,
 16.14,
 6.46,
 7.56,
 11.31,
 23.4,
 11.8,
 27.27,
 10.72,
 7.02,
 8.19,
 6.46,
 16.14,
 16.91,
 8.19,
 7.02,
 15.02,
 6.46,
 11.8,
 11.8,
 12.98,
 11.8,
 12.98,
 11.31,
 16.91,
 16.91,
 8.81,
 10.72,
 10.72,
 8.19,
 27.27,
 7.56,
 10.72,
 13.56,
 11.31,
 8.81,
 15.02,
 16.14,
 13.56,
 10.33,
 8.81,
 7.02,
 14.47,
 22.35,
 8.19,
 8.81,
 11.8,
 15.02,
 6.46,
 7.02,
 17.97,
 16.91,
 12.98,
 10.72,
 8.19,
 8.19,
 13.56,
 11.8,
 17.97,
 19.92,
 14.47,
 6.46,
 16.14,
 7.56,
 12.98,
 12.98,
 12.98,
 17.97,
 6.46,
 11.8,
 8.81,
 11.8,
 8.19,
 6.46,
 26.31,
 7.02,
 13.56,
 23.4,
 10.33,
 10.33,
 20.89,
 6.46,
 10.33,
 14.47,
 16.14,
 22.35,
 14.47,
 14.47,
 8.81,
 15.02,
 14.47,
 6.46,
 13.56,
 11.8,
 11.8,
 6.46,
 7.56,
 11.8,
 12.98,
 18.94,
 16.91,
 6.46,
 10.33,
 25.34,
 14.47,
 7.02,
 8.19,
 10.33,
 10.33,
 8.19,
 22.35,
 11.31,
 27.27,
 10.72,
 26.31,
 13.56,
 16.91,
 13.56,
 10.33,
 20.89,
 13.56,
 8.19,
 16.14,
 8.19,
 7.02,
 10.72,
 7.02,
 8.19,
 8.19,
 15.02,
 27.27,
 11.8,
 8.19,
 12.98,
 8.81,
 10.72,
 26.31,
 7.02,
 6.46,
 7.02,
 6.46,
 16.91,
 10.72,
 15.02,
 12.98,
 11.8,
 8.19,
 23.4,
 12.98,
 6.46,
 7.56,
 10.33,
 8.19,
 8.19,
 11.31,
 8.19,
 10.72,
 12.98,
 7.56,
 11.31,
 8.81,
 6.46,
 6.46,
 15.02,
 8.19,
 6.46,
 12.98,
 10.33,
 10.72,
 6.46,
 10.72,
 13.56,
 7.02,
 11.8,
 7.56,
 11.31,
 6.46,
 11.8,
 6.46,
 26.31,
 16.91,
 10.72,
 14.47,
 11.31,
 8.19,
 14.47,
 7.56,
 10.72,
 11.31,
 11.8,
 7.56,
 10.33,
 14.47,
 7.56,
 11.8,
 27.27,
 24.37,
 8.19,
 11.31,
 11.31,
 6.46,
 17.97,
 11.8,
 11.31,
 10.33,
 6.46,
 6.46,
 6.46,
 8.81,
 16.91,
 8.19,
 8.81,
 22.35,
 11.8,
 16.91,
 10.72,
 14.47,
 10.72,
 10.72,
 8.81,
 6.46,
 6.46,
 11.8,
 13.56,
 8.19,
 7.02,
 12.98,
 6.46,
 14.47,
 10.33,
 6.46,
 17.97,
 8.19,
 13.56,
 10.33,
 8.19,
 10.33,
 15.02,
 14.47,
 8.19,
 6.46,
 7.02,
 16.91,
 13.56,
 8.19,
 7.02,
 11.31,
 20.89,
 10.33,
 12.98,
 10.72,
 16.14,
 7.02,
 24.37,
 16.14,
 11.8,
 10.33,
 11.8,
 8.19,
 12.98,
 8.19,
 14.47,
 20.89,
 16.14,
 10.72,
 15.02,
 12.98,
 19.92,
 8.81,
 16.14,
 6.46,
 6.46,
 7.02,
 10.72,
 11.8,
 7.02,
 6.46,
 12.98,
 8.81,
 7.56,
 8.81,
 7.02,
 14.47,
 18.94,
 12.98,
 7.56,
 7.02,
 7.02,
 8.81,
 19.92,
 7.56,
 16.14,
 6.46,
 13.56,
 8.81,
 12.98,
 14.47,
 8.19,
 7.56,
 8.19,
 11.8,
 13.56,
 10.72,
 16.14,
 11.8,
 7.56,
 19.92,
 10.33,
 8.81,
 13.56,
 15.02,
 13.56,
 17.97,
 10.72,
 11.8,
 17.97,
 12.98,
 8.81,
 10.72,
 15.02,
 11.8,
 11.8,
 8.19,
 8.19,
 11.8,
 11.8,
 11.8,
 13.56,
 11.8,
 12.98,
 12.98,
 10.72,
 8.19,
 13.56,
 12.98,
 10.72,
 11.8,
 16.91,
 12.98,
 11.8,
 11.8,
 11.31,
 7.56,
 10.72,
 17.97,
 18.94,
 11.31,
 7.02,
 10.33,
 7.02,
 10.72,
 7.02,
 7.56,
 23.4,
 8.19,
 17.97,
 7.02,
 11.8,
 11.31,
 8.19,
 10.72,
 11.8,
 6.46,
 8.19,
 16.91,
 10.33,
 7.02,
 19.92,
 6.46,
 11.31,
 6.46,
 6.46,
 11.8,
 10.33,
 16.91,
 16.91,
 11.8,
 10.33,
 10.72,
 15.02,
 10.72,
 16.14,
 16.14,
 18.94,
 14.47,
 10.33,
 14.47,
 12.98,
 8.19,
 16.14,
 7.56,
 15.02,
 11.8,
 7.56,
 6.46,
 11.31,
 6.46,
 11.31,
 11.8,
 10.72,
 7.56,
 15.02,
 7.56,
 11.31,
 6.46,
 15.02,
 8.19,
 ...]

In [0]:
term =[df.term.copy()]

In [0]:
 #Writing Function
  def term_conversion(cell_contents):
   return cell_contents.strip().strip('months')

In [96]:
#Test
term_conversion(int_rate)

'13.56%'

In [97]:
type(term_conversion(int_rate))

str

In [102]:
df['term_conversion'] = df['int_rate'].apply(term_conversion).apply(new_int_rate)

df.head()

KeyboardInterrupt: ignored

Convert the term column from strings to integers

In [58]:
#Looking for the datatype of the term column
df['term'].dtypes

dtype('O')

In [59]:
#Output 1 cell from the column
df['term'][0]

' 36 months'

In [0]:
#Assign above output to a variable

term = '36 months'

In [88]:
#Ned to see more rows in the 'term column'

df['term'].head(100)

0      36 months
1      36 months
2      60 months
3      36 months
4      36 months
5      36 months
6      36 months
7      36 months
8      60 months
9      36 months
10     36 months
11     60 months
12     36 months
13     36 months
14     36 months
15     60 months
16     60 months
17     60 months
18     60 months
19     60 months
20     36 months
21     36 months
22     36 months
23     60 months
24     36 months
25     60 months
26     36 months
27     60 months
28     36 months
29     36 months
30     36 months
31     60 months
32     36 months
33     36 months
34     36 months
35     60 months
36     36 months
37     60 months
38     36 months
39     60 months
40     36 months
41     36 months
42     60 months
43     36 months
44     36 months
45     36 months
46     36 months
47     60 months
48     36 months
49     36 months
50     36 months
51     60 months
52     60 months
53     36 months
54     36 months
55     36 months
56     36 months
57     36 months
58     60 months
59     36 months
60     36 months
61     60 months
62     60 months
63     60 months
64     60 months
65     60 months
66     36 months
67     60 months
68     36 months
69     36 months
70     36 months
71     36 months
72     36 months
73     60 months
74     60 months
75     36 months
76     36 months
77     36 months
78     60 months
79     36 months
80     36 months
81     36 months
82     60 months
83     36 months
84     60 months
85     36 months
86     60 months
87     60 months
88     36 months
89     36 months
90     36 months
91     36 months
92     60 months
93     36 months
94     60 months
95     60 months
96     36 months
97     36 months
98     60 months
99     60 months
Name: term, dtype: object

In [91]:
term.strip()

AttributeError: ignored

In [90]:
def loanStatus(cell):
  if cell == "Current" or cell == "Fully Paid":
    return 1
  else:
    return 0
df['loan_status'] = df['loan_status].apply(loanStatus)

SyntaxError: ignored

In [0]:
[col for col in df if col.endswith('_d')]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01