<a href="https://colab.research.google.com/github/raklives/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/intro_tro_python_for_marketers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### KICK STARTER DATA SET

In [0]:
# import library
import pandas as pd # basically a version of excel for python

In [0]:
# read in our data file 
# comma not needed
ksmdata = pd.read_csv('most_backed.csv', sep=',')

In [9]:
# preview the first 10
ksmdata.head()

   Unnamed: 0  ...                                                url
0           0  ...                /projects/elanlee/exploding-kittens
1           1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2           2  ...  /projects/readingrainbow/bring-reading-rainbow...
3           3  ...  /projects/559914737/the-veronica-mars-movie-pr...
4           4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 13 columns]

In [6]:
# how many rows and columns 
ksmdata.shape

(4000, 13)

In [10]:
# add .info() give you a bunch of information about the data
ksmdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
Unnamed: 0          4000 non-null int64
amt.pledged         4000 non-null float64
blurb               4000 non-null object
by                  4000 non-null object
category            4000 non-null object
currency            4000 non-null object
goal                4000 non-null float64
location            4000 non-null object
num.backers         4000 non-null int64
num.backers.tier    4000 non-null object
pledge.tier         4000 non-null object
title               4000 non-null object
url                 4000 non-null object
dtypes: float64(2), int64(2), object(9)
memory usage: 406.4+ KB

In [11]:
# use .desribe() to look at descriptive analysis of the sample data numeric data
ksmdata.describe()

        Unnamed: 0   amt.pledged          goal    num.backers
count  4000.000000  4.000000e+03  4.000000e+03    4000.000000
mean   1999.500000  2.899923e+05  6.175203e+04    3582.875750
std    1154.844867  7.119369e+05  1.266715e+05    7316.102809
min       0.000000  1.925000e+03  1.000000e+00    1109.000000
25%     999.750000  6.771300e+04  1.300000e+04    1406.750000
50%    1999.500000  1.205860e+05  3.000000e+04    1946.000000
75%    2999.250000  2.593680e+05  6.000000e+04    3372.000000
max    3999.000000  2.033899e+07  2.000000e+06  219382.000000

In [17]:
# use head to see first five of the data
ksmdata.head()
# things spotted
# Unnamed: 0 for a title
# amt.pledged & goal columns look like floats but could be changed to integers because
# all values end in .0
# blurb column values have \n infront of some values
# columns with square brackets are actually numbers

   Unnamed: 0  ...                                                url
0           0  ...                /projects/elanlee/exploding-kittens
1           1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2           2  ...  /projects/readingrainbow/bring-reading-rainbow...
3           3  ...  /projects/559914737/the-veronica-mars-movie-pr...
4           4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 13 columns]

In [16]:
# look at a single column
ksmdata['Unnamed: 0']

0          0
1          1
2          2
3          3
4          4
        ...
3995    3995
3996    3996
3997    3997
3998    3998
3999    3999
Name: Unnamed: 0, Length: 4000, dtype: int64

In [0]:
# indexes are important
# setting indexes
# to create a reference point in the data, that you can use to move data around
# could be customer ID

In [0]:
# this is how we set the index
# in this case we are reading over our original data frame
ksmdata = pd.read_csv('most_backed.csv', sep=',', index_col='by')

In [19]:
# check for index reset
ksmdata.head()

                                      Unnamed: 0  ...                                                url
by                                                ...
Elan Lee                                       0  ...                /projects/elanlee/exploding-kittens
Matthew and Mark McLachlan                     1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
LeVar Burton & Reading Rainbow                 2  ...  /projects/readingrainbow/bring-reading-rainbow...
Rob Thomas                                     3  ...  /projects/559914737/the-veronica-mars-movie-pr...
Double Fine and 2 Player Productions           4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 12 columns]

### FILTERING AND RENAMING COLUMNS

In [20]:
# look at columns
# column name can be annoying, helps name them better
# also programing languages don't like white spaces in naming conventions
ksmdata.columns

Index(['Unnamed: 0', 'amt.pledged', 'blurb', 'category', 'currency', 'goal',
       'location', 'num.backers', 'num.backers.tier', 'pledge.tier', 'title',
       'url'],
      dtype='object')

In [0]:
# change the unnamed one into ID
ksmdata.rename(columns={'Unnamed: 0':'ID'}, inplace=True)

In [22]:
# inspect for change
ksmdata.head()

                                      ID  ...                                                url
by                                        ...
Elan Lee                               0  ...                /projects/elanlee/exploding-kittens
Matthew and Mark McLachlan             1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
LeVar Burton & Reading Rainbow         2  ...  /projects/readingrainbow/bring-reading-rainbow...
Rob Thomas                             3  ...  /projects/559914737/the-veronica-mars-movie-pr...
Double Fine and 2 Player Productions   4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 12 columns]

In [24]:
# how to replace annoying characters
# look up all the columns, replace anywhere you see '. repalce with ''(nothing)
# str is a string method
ksmdata.columns = ksmdata.columns.str.replace('.', '')

# inspect
ksmdata.head()

                                      ID  ...                                                url
by                                        ...
Elan Lee                               0  ...                /projects/elanlee/exploding-kittens
Matthew and Mark McLachlan             1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
LeVar Burton & Reading Rainbow         2  ...  /projects/readingrainbow/bring-reading-rainbow...
Rob Thomas                             3  ...  /projects/559914737/the-veronica-mars-movie-pr...
Double Fine and 2 Player Productions   4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 12 columns]

### EXPLORE SPECIFIC COLUMNS

In [0]:
# look at a specific column. location data
ksmdata['location']

# save that toa variable
locdata = ksmdata['location']

In [33]:
# what iss going on in this column
# what type of information are in here
# where are people running campaigns from?
# to know that, we'll need to look at the column with the locations and see what unique location names are in there
# that's where .unique() comes in

# for that we use .unique() for specifc kinda of data
locdata.unique()

# but let's look at is as a list
list(locdata.unique())

# much better

['Los Angeles, CA',
 'Denver, CO',
 'San Diego, CA',
 'San Francisco, CA',
 'Palo Alto, CA',
 'Newport Beach, CA',
 'Irvine, CA',
 'Derby, UK',
 'Toronto, Canada',
 'Tokyo, Japan',
 'Redwood City, CA',
 'Dallas, TX',
 'Portland, OR',
 'Minneapolis, MN',
 'Chicago, IL',
 'Kirkland, WA',
 'Sacramento, CA',
 'Oakland, CA',
 'Bellevue, WA',
 'Prague, Czech Republic',
 'Stockport, UK',
 'Austin, TX',
 'New York, NY',
 'Anacortes, WA',
 'Montreal, Canada',
 'Boston, MA',
 'Cambridge, UK',
 'Miami, FL',
 'Pasadena, CA',
 'San Jose, CA',
 'Atlanta, GA',
 'Spokane, WA',
 'Beijing, China',
 'Oslo, Norway',
 'Cambridge, MA',
 'Vancouver, WA',
 'Plano, TX',
 'Melbourne, AU',
 'Ghent, Belgium',
 'Orem, UT',
 'Lake Forest, CA',
 'Denton, TX',
 'St. Louis, MO',
 'Alpine, UT',
 'Umeå, Sweden',
 'Seattle, WA',
 'Guildford, UK',
 'Brooklyn, NY',
 'Niagara Falls, NY',
 'Las Vegas, NV',
 'Munich, Germany',
 'Carlsbad, CA',
 'Isle of Wight, UK',
 'Sydney, AU',
 'Ogden, UT',
 'Brisbane, AU',
 'Philadelphia, PA',
 'Santa Cruz, CA',
 'Fairfax, VA',
 'Phoenix, AZ',
 'Waterloo, Canada',
 'Londonderry, NH',
 'York, UK',
 'Lexington, MA',
 'London, UK',
 'Newark, DE',
 'Detroit, MI',
 'Easthampton, MA',
 'Queen Creek, AZ',
 'Urbana, IL',
 'Lexington, KY',
 'Paris, France',
 'Pembrokeshire County, UK',
 'Frankfurt, Germany',
 'Framingham, MA',
 'Bethesda, MD',
 'Lower East Side, Manhattan, NY',
 'Storrs, CT',
 'Łódź, Poland',
 'Salt Lake City, UT',
 'Nice, France',
 'Tucson, AZ',
 'Eugene, OR',
 'Hamburg, Germany',
 'Birmingham, UK',
 'Ljubljana, Slovenia',
 'Cannes, France',
 'Fairfield, CT',
 'Washington, DC',
 'Somerville, MA',
 'Stockholm, Sweden',
 'Hillandale, MD',
 'Redondo Beach, CA',
 'Shanghai, China',
 'Manchester, UK',
 'Vancouver, Canada',
 'Wroclaw, Poland',
 'Long Beach, CA',
 'Ottawa, Canada',
 'Missoula, MT',
 'Hyderabad, India',
 'Copenhagen, Denmark',
 'Marina del Rey, CA',
 'Madrid, Spain',
 'Provo, UT',
 'Mountain Green, UT',
 'Lancing, UK',
 'Mesa, AZ',
 'Adelaide, AU',
 'Houston, TX',
 'Albany, CA',
 'Redmond, WA',
 'Silver Spring, MD',
 'West Chester, PA',
 'Malmö, Sweden',
 'Brighton and Hove City, UK',
 'Hellange, Luxembourg',
 'Sunnyvale, CA',
 'Oxford, UK',
 'Hamar, Norway',
 'Chapel Hill, NC',
 'Versailles, France',
 'Honolulu, HI',
 'Bradford, UK',
 'Worcester, UK',
 'Taipei City, Taiwan',
 'Venice, Los Angeles, CA',
 'Bremen, Germany',
 'Alameda, CA',
 'Utrecht, Netherlands',
 'Mexico City, Mexico',
 'Astoria, Queens, NY',
 'Pittsburgh, PA',
 'Apex, NC',
 'Ridgeland, MS',
 'Louisville, KY',
 'Sandy, UT',
 'Moscow, Russia',
 'Calgary, Canada',
 'Los Altos, CA',
 'Oceanside, CA',
 'Cumberland, Canada',
 'Baltimore, MD',
 'Fremont, OH',
 'Rocklin, CA',
 'Columbus, OH',
 'Woodmere, NY',
 'Hermosa Beach, CA',
 'Torrance, CA',
 'Lincoln, NE',
 'Boise, ID',
 'Duluth, MN',
 'Hanford, CA',
 'Phuket, Thailand',
 'Lake Arrowhead, CA',
 'Raleigh, NC',
 'Santa Barbara, CA',
 'Hull, UK',
 'Tel Aviv, Israel',
 'Offenburg, Germany',
 'Bellingham, WA',
 'Draper, UT',
 'Lincoln City, OR',
 'Mission Viejo, CA',
 'Milan, Italy',
 'Cupertino, CA',
 'Berlin, Germany',
 'Highlands Ranch, CO',
 'Vienna, Austria',
 'Santa Ana, CA',
 'Nottingham, UK',
 'Gijon, Spain',
 'Boulder, CO',
 'Layton, UT',
 'Lancaster, PA',
 'Osaka-shi, Japan',
 'Izhevsk, Russia',
 'Bend, OR',
 'Burbank, CA',
 'San Mateo, CA',
 'Santa Clara, CA',
 'Richmond, VA',
 'Discovery Bay, CA',
 'New Haven, CT',
 'Rochester, NY',
 'Stanford, CA',
 'Hollywood, Los Angeles, CA',
 'West Yorkshire, UK',
 'Durham, NC',
 'Carbondale, IL',
 'Tempe, AZ',
 'Indianapolis, IN',
 'Westland, MI',
 'San Luis Obispo, CA',
 'Trbovlje, Slovenia',
 'Aurora, CO',
 'Agoura Hills, CA',
 'Italia, Italy',
 'Valencia, Spain',
 'Santa Monica, CA',
 'Ottawa South, Canada',
 'San Carlos, CA',
 'Orlando, FL',
 'Seoul, South Korea',
 'Mountain View, CA',
 'Sofia, Bulgaria',
 'Nashville, TN',
 'Sterling, VA',
 'Providence, RI',
 'Lynnwood, WA',
 'Ann Arbor, MI',
 'Lutz, FL',
 'Fort Worth, TX',
 'Lafayette, LA',
 'Wilmington, NC',
 "Coeur D'Alene, ID",
 'Bath, UK',
 'Lafayette, IN',
 'Wake Forest, NC',
 'Milwaukee, WI',
 'Mapleton, UT',
 'Manhattan, NY',
 'Noblesville, IN',
 'Sausalito, CA',
 'Memphis, TN',
 'Akron, OH',
 'Springfield, MO',
 'Deerfield Beach, FL',
 'Saskatchewan, Canada',
 'Rockwall, TX',
 'New Orleans, LA',
 'Warsaw, Poland',
 'Bozeman, MT',
 'Swindon, UK',
 'Macungie, PA',
 'Greenfield, MA',
 'Eindhoven, Netherlands',
 'Johannesburg, South Africa',
 'Menlo Park, CA',
 'Chandler, AZ',
 'West Lafayette, IN',
 'Park City, UT',
 'Athens, GA',
 'Somerset, NJ',
 'Kabul, Afghanistan',
 'Cornwall and Isles of Scilly, UK',
 'Newport, NH',
 'Brookfield, CT',
 'Aliso Viejo, CA',
 'Nimes, France',
 'Erie, PA',
 'Auckland, NZ',
 'Toledo, OH',
 'Tuscaloosa, AL',
 'Chesterland, OH',
 'Hong Kong, Hong Kong',
 'Cocoa Beach, FL',
 'Big Bear Lake, CA',
 'Traverse City, MI',
 'Pleasanton, CA',
 'Sarasota, FL',
 'Brasilia, Brazil',
 'Amsterdam, Netherlands',
 'Cardiff, UK',
 'Anchorage, AK',
 'Viborg, Denmark',
 'Iowa City, IA',
 'Lille, France',
 'Landschlacht, Switzerland',
 'Charlotte, NC',
 'Aalborg, Denmark',
 'Zug, Switzerland',
 'Cleveland, OH',
 'Orinda, CA',
 'Turin, Italy',
 'Berkeley, CA',
 'West Hollywood, CA',
 'Greenville, SC',
 'Knoxville, TN',
 'Camaiore, Italy',
 'Centennial, CO',
 'Des Moines, IA',
 'Sheffield, UK',
 'Santa Rosa, CA',
 'Albany, NY',
 'Hayward, CA',
 'Kiev, Ukraine',
 'Gernsbach, Germany',
 'Aptos, CA',
 'Southend-on-Sea, UK',
 'Birmingham, AL',
 'Alexandria, VA',
 'Huntington Beach, CA',
 'Muscatine, IA',
 'Santiago, Chile',
 'Charlottesville, VA',
 'Rexburg, ID',
 'Berwick-upon-Tweed, UK',
 'St. Paul, MN',
 'Vigo, Spain',
 'Slough, UK',
 'Shrewsbury, UK',
 'Olathe, KS',
 'Fort Myers, FL',
 'Edinburgh, UK',
 'Kansas City, MO',
 'Greater London, UK',
 'Bielsko-Biała, Poland',
 'Ithaca, NY',
 'Ljungbyholm, Sweden',
 'Katowice, Poland',
 'Cincinnati, OH',
 "St. John's, Canada",
 'Colorado Springs, CO',
 'Lake Helen, FL',
 'Quebec, Canada',
 'Portsmouth, NH',
 'Long Branch, NJ',
 'Laguna Beach, CA',
 'Turlock, CA',
 'Los Gatos, CA',
 'Buenos Aires, Argentina',
 'Dubai, United Arab Emirates',
 'Bronx, NY',
 'Reno, NV',
 'Graz, Austria',
 'Jacksonville, FL',
 'Szczecin, Poland',
 'Mechanicsburg, PA',
 'Issaquah, WA',
 'Jerusalem, Israel',
 'Griffin, GA',
 'Arlington, MA',
 'The Woodlands, TX',
 'Montpellier, France',
 'Farmington, MI',
 'South Lyon, MI',
 'Costa Mesa, CA',
 'Naples, FL',
 'Machias, ME',
 'Kingsland, GA',
 'Walnut Creek, CA',
 'France, France',
 'Albuquerque, NM',
 'Chico, CA',
 'Wappingers Falls, NY',
 'Bethlehem, PA',
 'Lebanon, PA',
 'Rockport, ME',
 'Rotterdam, Netherlands',
 'Tinton Falls, NJ',
 'Albany, OR',
 'Virginia Beach, VA',
 'La Plata, MD',
 'Hoofddorp, Netherlands',
 'Zurich, Switzerland',
 'Arlington, VA',
 'Fishers, IN',
 'Lompoc, CA',
 'Jackson, WY',
 'Turku, Finland',
 'Southern Pines, NC',
 'Great Neck, NY',
 'Halethorpe, MD',
 'Hamilton, Canada',
 'Fremont, CA',
 'Jersey City, NJ',
 'Red Bank, NJ',
 'Minsk, Belarus',
 'Westport, CT',
 'Barcelona, Spain',
 'Sorrento, LA',
 'Tarpley, TX',
 'Winnipeg, Canada',
 'Hackensack, NJ',
 'Bristol, UK',
 'Jupiter, FL',
 'Palm Bay, FL',
 'Boca Raton, FL',
 'Northampton, MA',
 'Liege, Belgium',
 'Dover, DE',
 'Bordeaux, France',
 'Bloomington, IN',
 'Seville, Spain',
 'Istanbul, Turkey',
 'Princeton, NJ',
 'North Hollywood, Los Angeles, CA',
 'South Lake Tahoe, CA',
 'Kenmore, WA',
 'Edmonton, Canada',
 'Norman, OK',
 'Chelsea, AL',
 'Trumbull, CT',
 'Milton Keynes, UK',
 'Mount Prospect, IL',
 'Sioux Falls, SD',
 'Shenzhen, China',
 'Queens, NY',
 'Leipzig, Germany',
 'Bucharest, Romania',
 'Coney Island, Brooklyn, NY',
 'Oulu, Finland',
 'Tulsa, OK',
 'Ashland, MA',
 'Lawrenceville, GA',
 'Ames, IA',
 'South San Francisco, CA',
 'Grenoble, France',
 'Zebbug, Malta',
 'Navarre, FL',
 'Athens, Greece',
 'Antwerp, Belgium',
 'Ridgewood, Queens, NY',
 'Coconut Creek, FL',
 'Haddonfield, NJ',
 'Elgin, IL',
 'Rosemount, MN',
 'Portland, ME',
 'Gallup, NM',
 'Reykjavik, Iceland',
 'Fort Collins, CO',
 'Accord, NY',
 'East Palo Alto, CA',
 'Flint, MI',
 'Minnetonka, MN',
 'Norrköping, Sweden',
 'Huntsville, AL',
 'Bloomington, IL',
 'Wilmington, DE',
 'Edmonds, WA',
 'Placerville, CA',
 'Helsinki, Finland',
 'Innsbruck, Austria',
 'Bratislava, Slovakia',
 'Athens, OH',
 'Takoma Park, MD',
 'Belfast, UK',
 'Singapore, Singapore',
 'East Nashville, Nashville, TN',
 'Brisbane, CA',
 'Stuttgart, Germany',
 'Winooski, VT',
 'Olympia, WA',
 'Nephi, UT',
 'Dayton, OH',
 'Rio de Janeiro, Brazil',
 'Des Plaines, IL',
 'St. Veit an der Glan, Austria',
 'Odessa, TX',
 'County Durham, UK',
 'New Milford, CT',
 'Rome, Italy',
 'El Dorado Hills, CA',
 'Krakow, Poland',
 'Leitchfield, KY',
 'Petaluma, CA',
 'Durango, CO',
 'Busan, South Korea',
 'Glen Cove, NY',
 'Flower Mound, TX',
 'Aylesbury, UK',
 'College Park, MD',
 'Ringold, OK',
 'Marlborough, MA',
 'Toulouse, France',
 'Nashua, NH',
 'Waikanae, NZ',
 'Douglas, NV',
 'Sabadell, Spain',
 'Braddock, PA',
 'Williston, SC',
 'Pleasant Grove, UT',
 'Charleston, SC',
 'Malibu, CA',
 'Evergreen, CO',
 'Newark, CA',
 'Taos, NM',
 'Moncton, Canada',
 'Burlington, VT',
 'Skopje, Macedonia',
 'Rockport, MA',
 'Westby, WI',
 'Charlotte, VT',
 'South Philadelphia, Philadelphia, PA',
 'Victoria, Canada',
 'Humble, TX',
 'Hoboken, NJ',
 'Springville, UT',
 'Lake Worth, FL',
 'Washougal, WA',
 'Liverpool, UK',
 'Webster City, IA',
 'Mission Beach, San Diego, CA',
 'Taichung City, Taiwan',
 'Cheyenne, WY',
 'Jaipur, India',
 'Targu Mures, Romania',
 'Alhambra, CA',
 'Madison, WI',
 'Glasgow, UK',
 'Ogdensburg, NJ',
 'Mellor, UK',
 'Cypress, TX',
 'Bremerton, WA',
 'Sundance, UT',
 'Greater Manchester, UK',
 'Everett, WA',
 'Norfolk, UK',
 'Port Richey, FL',
 'Aberdeen, UK',
 'Southampton, UK',
 'Eureka, CA',
 'Dubuque, IA',
 'Middlesbrough, UK',
 'Bangor, ME',
 'South Royalton, VT',
 'Stuart, FL',
 'Camarillo, CA',
 'Lincoln, CA',
 'Brno, Czech Republic',
 'West Midlands, UK',
 'Maitland, FL',
 'Carver, MA',
 'Pori, Finland',
 'Capezzano Pianore, Italy',
 'West Palm Beach, FL',
 'Wales, UK',
 'Perth, AU',
 'Bochum, Germany',
 'Hilo, HI',
 'Jefferson, GA',
 'Seal Beach, CA',
 'Leesburg, VA',
 'Wellsville, NY',
 'Prince William, VA',
 'Branford, CT',
 'North Vancouver, Canada',
 'Yorba Linda, CA',
 'Gothenburg, Sweden',
 'San Jose, Costa Rica',
 'Ashland, OR',
 'Gloucester, MA',
 'Å Kofja Loka, Slovenia',
 'Lenexa, KS',
 'St. John, IN',
 'Glendale, CA',
 'Portola Valley, CA',
 'Helena, MT',
 'Artisan, Bakersfield, CA',
 'Wiltshire, UK',
 'Spanish Fork, UT',
 'Carmel, IN',
 'Evanston, IL',
 'Stafford, VA',
 'Plantation, FL',
 'Simi Valley, CA',
 'Richardson, TX',
 'Samara, Russia',
 'Rzgów, Poland',
 'Penticton, Canada',
 'NE Portland, Portland, OR',
 'Chattanooga, TN',
 'Menomonie, WI',
 'Tehachapi, CA',
 'St. Petersburg, FL',
 'Melbourne, FL',
 'Syracuse, NY',
 'Teruel, Spain',
 'City of Gold Coast, AU',
 'Harrisburg, PA',
 'Emeryville, CA',
 'Fredericksburg, VA',
 'Naperville, IL',
 'Shetland Islands, UK',
 'Charleroi, Belgium',
 'Carlisle, PA',
 'Christchurch, NZ',
 'Derbyshire, UK',
 'Stockbridge, GA',
 'Blacksburg, VA',
 'Rantoul, IL',
 'Waldems, Germany',
 'Champaign, IL',
 'Conifer, CO',
 'Thompsons Station, TN',
 'Lindon, UT',
 'Nokomis, FL',
 'Decatur, IL',
 'Varberg, Sweden',
 'Vallejo, CA',
 'Plymouth, MN',
 'Wichita, KS',
 'Kutztown, PA',
 'Savannah, GA',
 'Reading, UK',
 'Sherwood, OR',
 'Wynwood Art District, Miami, FL',
 'Dundee, UK',
 'Parker, CO',
 'Medford, MA',
 'Qualicum Beach, Canada',
 'Geneva, Switzerland',
 'Vashon, WA',
 'Northampton, UK',
 'Orange, CA',
 'Wayland, MA',
 'Redding, CA',
 'Kennesaw, GA',
 'Manila, Philippines',
 'Clearwater, FL',
 'Flensburg, Germany',
 'Springfield, IL',
 'Appleton, WI',
 'Danvers, MA',
 'Butlers Place, NJ',
 'Long Island, NY',
 'Tacoma, WA',
 'Leeds, UK',
 'Zagreb, Croatia',
 'Murfreesboro, TN',
 'Suffolk, VA',
 'Makati City, Philippines',
 'Downtown Toronto, Canada',
 'Whitefish, MT',
 'Borgholzhausen, Germany',
 'Southsea, UK',
 'Cairo, Egypt',
 'Amherst, MA',
 'Port Hope, Canada',
 'Berwyn, IL',
 'Vineland, NJ',
 'Towson, MD',
 'Ventura, CA',
 'Arlington, TX',
 'Reisterstown, MD',
 'Friedburg, Germany',
 'Johnstown, OH',
 'Buderim, AU',
 'Caerphilly, UK',
 'Sigel, IL',
 'Leeuwarden, Netherlands',
 'Stevensville, MD',
 'Sicklerville, NJ',
 'East Taunton, MA',
 'Kenilworth, UK',
 'Little Rock, AR',
 'Dulles, VA',
 'Dublin, Ireland',
 'Noosaville, AU',
 'Homestead, FL',
 'Big Timber, MT',
 'Danville, CA',
 'Bartlett, TN',
 'Barrington, IL',
 'Longmeadow, MA',
 'Scottsdale, AZ',
 'Norfolk, VA',
 'Maysville, MO',
 'Newbury Park, Thousand Oaks, CA',
 'Charlotte Amalie, Virgin Islands, U.S.',
 'Irving, TX',
 'Asheville, NC',
 'Powellton, VA',
 'Venus, FL',
 'Folkestone, UK',
 'Woodstock, NY',
 'South Setauket, NY',
 'North Salt Lake, UT',
 'Ohope, NZ',
 'Franklin, TN',
 'Folsom, CA',
 'Mount Crested Butte, Crested Butte, CO',
 'Niles, IL',
 'Brandenburg, KY',
 'Nanuet, NY',
 'Fort Lauderdale, FL',
 'Clarkfield, MN',
 'Morecambe, UK',
 'Zaporizhzhya, Ukraine',
 'Doylestown, PA',
 'Leicestershire, UK',
 'El Segundo, CA',
 'East Brunswick, NJ',
 'Tampa, FL',
 'Westmont, NJ',
 'San Juan, Puerto Rico',
 'Gerlach, NV',
 'Beaverton, OR',
 'Bandung, Indonesia',
 'Yaounde, Cameroon',
 'London, Canada',
 'Brea, CA',
 'Saxonville, Framingham, MA',
 'Troy, NY',
 'Davis, CA',
 'Garland, TX',
 'Norcross, GA',
 'Kapiti, NZ',
 'Longmont, CO',
 'Cape Elizabeth, ME',
 'Edwardsville, IL',
 'Williams Bay, WI',
 'Rzeszów, Poland',
 'Lake Geneva, WI',
 'Canberra, AU',
 'Carpinteria, CA',
 'Malmesbury, UK',
 'Homeland, FL',
 'Annapolis, MD',
 'Grand Rapids, MI',
 'Velenje, Slovenia',
 'Harrisonburg, VA',
 'Taunton, UK',
 'Baulkham Hills, AU',
 'Lansing, MI',
 'Budapest, Hungary',
 'St. George, UT',
 'Trabuco Canyon, CA',
 'Cary, NC',
 'Valletta, Malta',
 'Rowley, MA',
 'Linköping, Sweden',
 'Tsukuba, Japan',
 'Sandpoint, ID',
 'Comox, Canada',
 'Columbia, MD',
 'Collingswood, NJ',
 'Northport, AL',
 'Neu-Ulm, Germany',
 'Coonabarabran, AU',
 'Bogota, Colombia',
 'Elk Grove, CA',
 'Guadalajara, Mexico',
 'San Antonio, TX',
 'Salem, OR',
 'Crestview Hills, KY',
 'Kyle, TX',
 'Studio City, Los Angeles, CA',
 'Abergavenny, UK',
 'San Clemente, CA',
 'Independence, KY',
 'Scheveningen, Netherlands',
 'Shepherdstown, WV',
 'Gardena, CA',
 'Topeka, KS',
 'Šoštanj, Slovenia',
 'Sherman Oaks, Los Angeles, CA',
 'Anglet, France',
 'Williamsburg, VA',
 'Angouleme, France',
 'Hudson, NY',
 'Kountze, TX',
 'Pittsfield, MA',
 'Baton Rouge, LA',
 'Oegstgeest, Netherlands',
 'Norristown, PA',
 'Gemeinde Offenburg, Germany',
 'Vista, CA',
 'Laie, HI',
 'Windsor, Canada',
 'Bridgeport, CT',
 'Jenison, MI',
 'Sweden, SC',
 'Osceola, IN',
 'American Fork, UT',
 'Guelph, Canada',
 'Mesquite, TX',
 'Perth Central, AU',
 'Oxford, MI',
 'Midland Park, Maplewood, NJ',
 'North Yorkshire, UK',
 'Glassell Park, Los Angeles, CA',
 'Roswell, GA',
 'Waco, TX',
 'Warwick, UK',
 'Rowlett, TX',
 'Buffalo, NY',
 'Warwick, NY',
 'Lakewood, NJ',
 'Fall River, MA',
 'Ashburn, VA',
 'Johnson City, TN',
 'Redgranite, WI',
 'Fayetteville, NC',
 'Tottori, Japan',
 'Gig Harbor, WA',
 'Maribor, Slovenia',
 'Bingley, UK',
 'Devonport, UK',
 'Leominster, MA',
 'Mckinney, TX',
 'Riverside, CA',
 'Hudson, WI',
 'Wagga Wagga, AU',
 'Lehi, UT',
 'Keller, TX',
 'Gilbert, AZ',
 'Lawrence, KS',
 'Houghton, MI',
 'Riga, Latvia',
 'Merthyr Tydfil, UK',
 'Omsk, Russia',
 'Nairobi, Kenya',
 "Luhans'k, Ukraine",
 'Hamilton, NZ']

In [79]:
# where are most of these campaigns happening? Top locations
# how many capaigns are coming from each of these top locations?
percentloc = locdata.value_counts()

# value counts tells you how much of something is in a list. 
# in this case, the values we want to count are number of each 

percentloc.head(10)

San Francisco, CA    280
Los Angeles, CA      271
New York, NY         212
Seattle, WA          147
London, UK           132
Chicago, IL          121
Brooklyn, NY         103
Portland, OR          84
San Diego, CA         62
Toronto, Canada       60
Name: location, dtype: int64

In [41]:
# what kind of catagories are there

# assign category a specific variable name
categories = ksmdata['category']

# the unique categories
categories.unique()

# make it a list. it's easier to see
list(categories)

['Tabletop Games',
 'Product Design',
 'Web',
 'Narrative Film',
 'Video Games',
 'Product Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Technology',
 'Video Games',
 'Product Design',
 'Video Games',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Gaming Hardware',
 'Product Design',
 'Video Games',
 'Television',
 'Narrative Film',
 'Product Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Hardware',
 'Hardware',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Video Games',
 'Hardware',
 'Product Design',
 'Video Games',
 'Music',
 'Video Games',
 'Video Games',
 'Narrative Film',
 'Product Design',
 'Space Exploration',
 'Video Games',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Hardware',
 'Video Games',
 'Radio &amp; Podcasts',
 'Video Games',
 'Product Design',
 'Flight',
 'Tabletop Games',
 'Product Design',
 'Radio &amp; Podcasts',
 'Video Games',
 'Video Games',
 'Product Design',
 'Video Games',
 'Technology',
 'Technology',
 'Video Games',
 'Sound',
 'Animation',
 'Video Games',
 'Video Games',
 'Games',
 'Tabletop Games',
 'Technology',
 'Action',
 'Space Exploration',
 'Gadgets',
 'Video Games',
 'Product Design',
 'Video Games',
 'Documentary',
 'Hardware',
 '3D Printing',
 'DIY Electronics',
 'Product Design',
 'Video Games',
 'Product Design',
 'Technology',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Publishing',
 'Product Design',
 'Fashion',
 'Video Games',
 'Tabletop Games',
 'Comics',
 'Typography',
 'Video Games',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Animation',
 'Video Games',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Video Games',
 'Fashion',
 'Product Design',
 'Tabletop Games',
 "Children's Books",
 'Product Design',
 'Apparel',
 'Product Design',
 'Food',
 'Technology',
 'Tabletop Games',
 'Crafts',
 'Camera Equipment',
 'Gadgets',
 'Food',
 'Food',
 'Product Design',
 'Tabletop Games',
 'Video Games',
 'DIY Electronics',
 'Video Games',
 'Tabletop Games',
 'Animation',
 'Tabletop Games',
 'Technology',
 'Tabletop Games',
 'Animation',
 'Tabletop Games',
 '3D Printing',
 'Fashion',
 'Radio &amp; Podcasts',
 'Comedy',
 'Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Product Design',
 'Sound',
 'Product Design',
 'Graphic Design',
 'Apps',
 'Hip-Hop',
 'Video Games',
 'DIY Electronics',
 'Product Design',
 'Product Design',
 'Tabletop Games',
 'Tabletop Games',
 'Video Games',
 'World Music',
 'Gadgets',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Film &amp; Video',
 'Sound',
 'Food',
 'Hardware',
 'Video Games',
 'Video Games',
 'Drinks',
 'Sound',
 'Product Design',
 'Product Design',
 'Music',
 'Technology',
 'Tabletop Games',
 'Wearables',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Wearables',
 'Product Design',
 'Tabletop Games',
 'Video Games',
 'Hardware',
 'Food',
 'Accessories',
 'Publishing',
 'Video Games',
 'Tabletop Games',
 'Footwear',
 'Fashion',
 'Tabletop Games',
 'Fashion',
 'Gaming Hardware',
 'Video Games',
 'Space Exploration',
 'Product Design',
 'Documentary',
 'Tabletop Games',
 'Food',
 "Children's Books",
 'Technology',
 'Apparel',
 'Product Design',
 'Video Games',
 'Product Design',
 'Gadgets',
 'Accessories',
 'Technology',
 'Comics',
 'Product Design',
 'Tabletop Games',
 "Children's Books",
 'Wearables',
 'Video Games',
 'Gadgets',
 'Tabletop Games',
 'Tabletop Games',
 'Documentary',
 'Product Design',
 'Gadgets',
 'Video Games',
 'Product Design',
 'Product Design',
 'Product Design',
 'Graphic Design',
 'Gadgets',
 'Product Design',
 'Video Games',
 'Documentary',
 'Hardware',
 'Tabletop Games',
 'Product Design',
 'Technology',
 'Science Fiction',
 'Product Design',
 'Product Design',
 'Comics',
 'Design',
 'Technology',
 'Tabletop Games',
 'Hardware',
 'Video Games',
 'Product Design',
 'Art Books',
 'Product Design',
 'Nonfiction',
 'Hardware',
 'Technology',
 'Film &amp; Video',
 'Video Games',
 'Video Games',
 'Product Design',
 'Wearables',
 'Video Games',
 'Video Games',
 'Product Design',
 '3D Printing',
 'Hardware',
 'Hardware',
 'Comics',
 'Hardware',
 'Tabletop Games',
 'Product Design',
 'Animation',
 'Product Design',
 'Product Design',
 'Design',
 'Video Games',
 'Technology',
 'Robots',
 'Product Design',
 'Hardware',
 'Gadgets',
 'Tabletop Games',
 'Product Design',
 'Sound',
 'Technology',
 'Art',
 'Product Design',
 'Design',
 'Hardware',
 'Animation',
 'Comics',
 'Video Games',
 'Hardware',
 'Fashion',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Wearables',
 'Video Games',
 'Technology',
 'Robots',
 'Video Games',
 'Video Games',
 'Product Design',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Video Games',
 'Gadgets',
 'Software',
 'Tabletop Games',
 'Space Exploration',
 'Apparel',
 'Games',
 'Product Design',
 'Wearables',
 'Chiptune',
 'Tabletop Games',
 'Fashion',
 'Video Games',
 'Gaming Hardware',
 'Comedy',
 'Product Design',
 'Tabletop Games',
 'Video Games',
 'Webseries',
 'Video Games',
 'Webcomics',
 'Tabletop Games',
 'Nonfiction',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Art Books',
 'DIY Electronics',
 'Video Games',
 'Tabletop Games',
 'Webseries',
 'Video Games',
 'Video Games',
 'Wearables',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Hardware',
 'Video Games',
 'Gadgets',
 'Music',
 'Tabletop Games',
 'Food',
 'Accessories',
 'Design',
 'Tabletop Games',
 'Hardware',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Product Design',
 'Graphic Design',
 'Product Design',
 'Video Games',
 'Games',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Tabletop Games',
 'Tabletop Games',
 'Apps',
 'Product Design',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Technology',
 'Hardware',
 'Product Design',
 'Film &amp; Video',
 'Documentary',
 'Wearables',
 'Software',
 'Comics',
 'Narrative Film',
 'Technology',
 'Video Games',
 'Video Games',
 'Product Design',
 'Rock',
 'Gadgets',
 'Video Games',
 'Video Games',
 'Product Design',
 'Product Design',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Design',
 'Product Design',
 'DIY Electronics',
 'Accessories',
 'Video Games',
 'Design',
 'Wearables',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Film &amp; Video',
 'Gadgets',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Design',
 'Hardware',
 'Technology',
 'Design',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Comics',
 'Video Games',
 'Gadgets',
 'Technology',
 'DIY Electronics',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Product Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Product Design',
 'Tabletop Games',
 'Video Games',
 'Sound',
 'Video Games',
 'Product Design',
 'Video Games',
 'Wearables',
 'Hardware',
 'Product Design',
 'Sound',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Animation',
 'Gadgets',
 'Product Design',
 'Hardware',
 'Tabletop Games',
 'Video Games',
 'Technology',
 'Product Design',
 'Playing Cards',
 'Comics',
 'Animation',
 'Technology',
 'Technology',
 'Hardware',
 'Product Design',
 'Video Games',
 'Webseries',
 'Radio &amp; Podcasts',
 'Video Games',
 'Product Design',
 'Cookbooks',
 'Video Games',
 'Design',
 'Hardware',
 'Product Design',
 'Footwear',
 'Animation',
 'Video Games',
 'Fantasy',
 'Design',
 'Photography',
 'Fashion',
 'DIY Electronics',
 'Anthologies',
 'Video Games',
 'DIY Electronics',
 'Food',
 'Wearables',
 'Tabletop Games',
 'Design',
 'Food',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Design',
 'Video Games',
 'Tabletop Games',
 'Technology',
 'Product Design',
 'Video Games',
 'Video Games',
 'Footwear',
 'Food',
 'Tabletop Games',
 'Tabletop Games',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Tabletop Games',
 'Tabletop Games',
 'Technology',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Gadgets',
 'Fashion',
 'Tabletop Games',
 'Hardware',
 'Product Design',
 'Product Design',
 'Video Games',
 'Documentary',
 'Product Design',
 'Tabletop Games',
 'Webseries',
 'Software',
 'Tabletop Games',
 'Video Games',
 'Product Design',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Film &amp; Video',
 'Video Games',
 'Product Design',
 'Wearables',
 'Technology',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Apps',
 'Tabletop Games',
 'Design',
 'Product Design',
 'Product Design',
 'Design',
 'Hardware',
 'Webcomics',
 'Product Design',
 'Tabletop Games',
 'Technology',
 'Wearables',
 'Video Games',
 'Video Games',
 'Tabletop Games',
 'Faith',
 'Mixed Media',
 'Technology',
 'Product Design',
 'Product Design',
 'Video Games',
 'Radio &amp; Podcasts',
 'Film &amp; Video',
 'Product Design',
 'Apparel',
 'Hardware',
 'Product Design',
 'Video Games',
 'Video Games',
 'Product Design',
 'Video Games',
 'Product Design',
 'Gadgets',
 'Footwear',
 'Product Design',
 'Product Design',
 'Video Games',
 'Rock',
 'Tabletop Games',
 'Product Design',
 'Apparel',
 'Video Games',
 'Tabletop Games',
 'Comedy',
 'Tabletop Games',
 'Hardware',
 'Product Design',
 'Video Games',
 'Technology',
 'Sound',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Product Design',
 'Video Games',
 'Product Design',
 'Video Games',
 'Narrative Film',
 'Tabletop Games',
 'Product Design',
 'Art',
 'Tabletop Games',
 'Radio &amp; Podcasts',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Product Design',
 'Gadgets',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Technology',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Games',
 'Product Design',
 'Video Games',
 'Product Design',
 'Video Games',
 'Metal',
 'Product Design',
 'Product Design',
 'Product Design',
 'Webseries',
 'Product Design',
 'Video Games',
 'Video Games',
 'Product Design',
 'Product Design',
 'Hardware',
 'Comics',
 'Video Games',
 'Product Design',
 'Video Games',
 'Small Batch',
 'Product Design',
 'Design',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Narrative Film',
 'Product Design',
 'Video Games',
 'Animation',
 'Documentary',
 'Hardware',
 'Art',
 'Product Design',
 'Documentary',
 'DIY Electronics',
 'Video Games',
 'Video Games',
 'Hardware',
 'Comics',
 'Product Design',
 'Video Games',
 'Product Design',
 '3D Printing',
 'Tabletop Games',
 'Tabletop Games',
 'Wearables',
 'Video Games',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Documentary',
 'Documentary',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Design',
 'Gadgets',
 'Hardware',
 'DIY Electronics',
 'Tabletop Games',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Product Design',
 'Video Games',
 'Tabletop Games',
 'Tabletop Games',
 'Tabletop Games',
 'Design',
 'Robots',
 'Narrative Film',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Product Design',
 'Hardware',
 'Tabletop Games',
 'Documentary',
 'Video Games',
 'Product Design',
 'Product Design',
 'Classical Music',
 'Product Design',
 'Documentary',
 'Hardware',
 'Video Games',
 'Nonfiction',
 'Product Design',
 'Tabletop Games',
 'Architecture',
 'Product Design',
 'Product Design',
 'Tabletop Games',
 'Video Games',
 'Video Games',
 'Product Design',
 'Video Games',
 'Pop',
 'Product Design',
 'Tabletop Games',
 'Comics',
 'Product Design',
 'Video Games',
 'DIY Electronics',
 'Product Design',
 'Video Games',
 'Gadgets',
 'Video Games',
 'Design',
 'Dance',
 'Video Games',
 'Video Games',
 'Electronic Music',
 'Fashion',
 'Narrative Film',
 'Video Games',
 'Hardware',
 'Video Games',
 'Publishing',
 'Video Games',
 'Food',
 'Technology',
 'Tabletop Games',
 'Food',
 'Video Games',
 'Technology',
 'Video Games',
 'Product Design',
 'Video Games',
 'Video Games',
 'Hardware',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Video Games',
 'Video Games',
 'Fashion',
 'Design',
 'Product Design',
 'Product Design',
 'Product Design',
 'Accessories',
 'Product Design',
 'Gadgets',
 'Graphic Design',
 'Tabletop Games',
 'Tabletop Games',
 'Gadgets',
 'Games',
 'Fashion',
 'Hardware',
 'Design',
 'Product Design',
 'Animation',
 'Hardware',
 'Product Design',
 'Product Design',
 'Video Games',
 'Design',
 'Technology',
 'Video Games',
 'DIY Electronics',
 'Video Games',
 'Comedy',
 'Wearables',
 'Tabletop Games',
 'Product Design',
 'Tabletop Games',
 'Hardware',
 'Technology',
 'Tabletop Games',
 'Tabletop Games',
 'Comics',
 'Animation',
 'Technology',
 'Tabletop Games',
 'Playing Cards',
 'Music',
 'Hardware',
 'Product Design',
 'Product Design',
 'Product Design',
 'Video Games',
 'Video Games',
 'Video Games',
 'Webseries',
 'Art Books',
 'Art',
 'Video Games',
 'Music',
 'Video Games',
 'Tabletop Games',
 'Technology',
 'Hardware',
 'Tabletop Games',
 'Product Design',
 'Graphic Novels',
 'Product Design',
 'Product Design',
 'Technology',
 'Video Games',
 'Comedy',
 'Documentary',
 'Tabletop Games',
 'Film &amp; Video',
 'Games',
 'Product Design',
 'Tabletop Games',
 'Hardware',
 'Fashion',
 'Product Design',
 'Gadgets',
 'Documentary',
 'Tabletop Games',
 'Video Games',
 'Tabletop Games',
 'Gadgets',
 'Product Design',
 'Software',
 'Technology',
 'Video Games',
 'Video Games',
 'Gadgets',
 'Tabletop Games',
 'Design',
 'Wearables',
 'Tabletop Games',
 'Comics',
 'Rock',
 'Documentary',
 'Tabletop Games',
 'Tabletop Games',
 'Design',
 'Comedy',
 'Tabletop Games',
 'Comedy',
 'Art Books',
 'Webcomics',
 'Tabletop Games',
 'Video Games',
 'Musical',
 'Wearables',
 'Product Design',
 'Video Games',
 'Product Design',
 'Technology',
 'Animation',
 'Gadgets',
 'Product Design',
 'Product Design',
 '3D Printing',
 'Tabletop Games',
 'Video Games',
 'Product Design',
 'Wearables',
 'Food',
 'Product Design',
 'Product Design',
 'Games',
 'Video Games',
 'Video Games',
 'Product Design',
 'Video Games',
 'Product Design',
 'Anthologies',
 'Tabletop Games',
 'Playing Cards',
 'Video Games',
 'Wearables',
 'Documentary',
 'Gadgets',
 'Tabletop Games',
 'Hardware',
 'Fashion',
 'Technology',
 'Hardware',
 'Video Games',
 'Tabletop Games',
 'Cookbooks',
 'Product Design',
 'Documentary',
 'DIY Electronics',
 'Video Games',
 'Video Games',
 'Product Design',
 'Film &amp; Video',
 'Documentary',
 'Tabletop Games',
 'Animation',
 'Video Games',
 'Film &amp; Video',
 'Product Design',
 'Product Design',
 'Theater',
 'Webseries',
 'Camera Equipment',
 'Photobooks',
 'Video Games',
 'Tabletop Games',
 'Product Design',
 'Fashion',
 'Tabletop Games',
 'Tabletop Games',
 'Playing Cards',
 'Product Design',
 'Hardware',
 'Video Games',
 'Product Design',
 'Technology',
 'Technology',
 '3D Printing',
 'Video Games',
 'Drama',
 'Product Design',
 'Software',
 'Hardware',
 'Fashion',
 'Tabletop Games',
 'Tabletop Games',
 'Tabletop Games',
 'Tabletop Games',
 'Design',
 'Gadgets',
 'Hardware',
 'Product Design',
 'Hardware',
 'Technology',
 'Video Games',
 'Space Exploration',
 'Video Games',
 'Video Games',
 'Fashion',
 'Hardware',
 'Tabletop Games',
 'Tabletop Games',
 'Gadgets',
 'Documentary',
 'Video Games',
 'Software',
 'Video Games',
 'Product Design',
 'Product Design',
 'Product Design',
 'Video Games',
 'Technology',
 'Video Games',
 'Games',
 'Video Games',
 'Chiptune',
 'Product Design',
 'Publishing',
 'Comics',
 'Tabletop Games',
 'Tabletop Games',
 'Hardware',
 'Gadgets',
 'Product Design',
 'Tabletop Games',
 'Product Design',
 'Product Design',
 'Hardware',
 'Product Design',
 'Shorts',
 'Documentary',
 'Product Design',
 'Science Fiction',
 'Comics',
 'Science Fiction',
 'Product Design',
 ...]

In [47]:
# what are the most popular categories
# save the value counts so you can call a .head() on it
percentcategories = categories.value_counts()

# you assign calls for categories to variables so you can use pandas
# methods to be able to call them

percentcategories.head(10)

Product Design    773
Tabletop Games    742
Video Games       524
Hardware          182
Technology        152
Documentary       124
Gadgets           121
Design             99
Comics             79
Wearables          64
Name: category, dtype: int64

In [0]:
# top products as percentages

In [53]:
percategories = categories.value_counts(normalize=True)

percategories.head()

Product Design    0.19325
Tabletop Games    0.18550
Video Games       0.13100
Hardware          0.04550
Technology        0.03800
Name: category, dtype: float64

In [69]:
# what's the most common currency
# different types of currencies
list(ksmdata['currency'].unique())

# save the list as a variable
currencies = ksmdata['currency'].value_counts()
currencies.head()

usd    3438
gbp     252
cad     128
eur      96
aud      52
Name: currency, dtype: int64

In [88]:
# how many times was each currency used
# usd is the most used currency by far
# chf is the least used
ucurrency= ksmdata['currency'].value_counts()
ucurrency.head()

usd    3438
gbp     252
cad     128
eur      96
aud      52
Name: currency, dtype: int64

### FILTERING THE DATA SET

In [89]:
# let's look at our features/columns
ksmdata.columns

Index(['ID', 'amtpledged', 'blurb', 'category', 'currency', 'goal', 'location',
       'numbackers', 'numbackerstier', 'pledgetier', 'title', 'url'],
      dtype='object')

In [91]:
# we want to filter our data to only show campaigns where
# amount pledged was more than/equals 100 dollars & goal was more than/equal to 100
# so basically people who met/exceeded their goals

# we're calling the data frame because we want to only show rows of the df
# that meets our specific criteria
ksmdata[(ksmdata['amtpledged'] >= 100) & (ksmdata['goal']>= 100)]

                                        ID  ...                                                url
by                                          ...
Elan Lee                                 0  ...                /projects/elanlee/exploding-kittens
Matthew and Mark McLachlan               1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
LeVar Burton & Reading Rainbow           2  ...  /projects/readingrainbow/bring-reading-rainbow...
Rob Thomas                               3  ...  /projects/559914737/the-veronica-mars-movie-pr...
Double Fine and 2 Player Productions     4  ...         /projects/doublefine/double-fine-adventure
...                                    ...  ...                                                ...
Shane Hensley                         3995  ...  /projects/545820095/savage-worlds-rippers-resu...
PulsePet                              3996  ...  /projects/santiagogutierrez/gobone-all-day-pla...
I AM Cardboard                        3997  ...  /projects/imcardboard/orbit-360-a-better-way-t...
Rick Davidson                         3998  ...  /projects/rickdavidson/origins-playing-cards-i...
OFF LIFE                              3999  ...     /projects/1907907192/yellow-the-collected-book

[3993 rows x 12 columns]

In [93]:
# store this filter
pledgegoal100 = ksmdata[(ksmdata['amtpledged'] >= 100) & (ksmdata['goal']>= 100)]

# check
pledgegoal100.head()

                                      ID  ...                                                url
by                                        ...
Elan Lee                               0  ...                /projects/elanlee/exploding-kittens
Matthew and Mark McLachlan             1  ...   /projects/antsylabs/fidget-cube-a-vinyl-desk-toy
LeVar Burton & Reading Rainbow         2  ...  /projects/readingrainbow/bring-reading-rainbow...
Rob Thomas                             3  ...  /projects/559914737/the-veronica-mars-movie-pr...
Double Fine and 2 Player Productions   4  ...         /projects/doublefine/double-fine-adventure

[5 rows x 12 columns]

In [97]:
# looking for a combination of words in a series/column
# we want a data frame that only shows rows where the 'category' column contains
# 'fil' or the 'blurb' column contains 'love'
filmslove = ksmdata[(ksmdata['category'].str.contains('film') | ksmdata['blurb'].str.contains('love'))]
filmslove.head()

                   ID  ...                                                url
by                     ...
BAUBAX LLC         21  ...  /projects/597538543/the-worlds-best-travel-jac...
Yacht Club Games  103  ...             /projects/yachtclubgames/shovel-knight
Freddie Wong      175  ...  /projects/freddiew/video-game-high-school-seas...
Taryn Brumfitt    233  ...  /projects/embrace/embrace-the-documentary-that...
North Aware Inc   238  ...  /projects/577214365/smart-parka-worlds-first-c...

[5 rows x 12 columns]

In [102]:
# filter data frame for rows where the category says 'video games' and the blurb
# says 'school'
ksmdata[ksmdata['category'].str.contains('Video Games') & ksmdata['blurb'].str.contains('school')].head()

                        ID  ...                                                url
by                          ...
Larian Studios LLC      64  ...      /projects/larianstudios/divinity-original-sin
Saulo Camarotti        793  ...  /projects/1893273284/chroma-squad-manager-game...
Chevy Ray Johnston    1369  ...                        /projects/chevyray/ikenfell
Elysian Shadows Team  1603  ...  /projects/1945059142/elysian-shadows-next-gen-...
Jonathan P. King      2238  ...             /projects/coldricegames/interstellaria

[5 rows x 12 columns]

In [0]:
#