<a href="https://colab.research.google.com/github/urenajose/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Jose_Urena_housing__LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

#Import and pd.set

In [1]:
##### Begin Working Here #####
import pandas as pd
import numpy as np
import seaborn as sns
pd.set_option('display.max_rows',144)
pd.set_option('display.max_columns',81)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
#df_housing = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Ames%20Housing%20Data/train.csv')

# Data set review

In [2]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-06-03 04:53:33--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 54.71.0.232, 52.26.240.115, 44.232.224.58
Connecting to resources.lendingclub.com (resources.lendingclub.com)|54.71.0.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.5’

LoanStats_2018Q4.cs     [             <=>    ]  22.10M  2.04MB/s    in 11s

2020-06-03 04:53:45 (2.00 MB/s) - ‘LoanStats_2018Q4.csv.zip.5’ saved [23170772]

In [3]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: LoanStats_2018Q4.csv

In [4]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 36 months"," 14.47%","688.13","C","C2","bus driver","4 years","OWN","52000","Source Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","681xx","NE","30.65","1","Jun-1979","2","15","","6","0","15048","73%","22","w","0.00","0.00","8169.13","8169.13","5731.54","2437.59","0.0","0.0","0.0","Feb-2020","0.0","","Mar-2020","0","","1","Individual","","","","0","0","33157","0","2","1","1","8","18109","44","1","2","8628","73","20700","1","1","4","3","5526","5175","73","0","0","141","474","10","8","0","10","15","1","15","0","4","4","11","12","8","4","14","4","6","","0","0","2","95","50","0","0","61699","33157","20700","40999","","","","","","","","","","","","","","","","","688.13","","","","","","","0","0","688.13","N","","","","","",""
"","","16000","16000","16000"," 36 months"," 14.47%","550.51","C","C2","Carpenter","10+ years","RENT","150000","Source Verified","Dec-2018","Current","n","","","other","Other","917xx","CA","17.94","0","Nov-2001","1","","","24","0","43721","59.2%","29","w","9726.53","9726.53","8788.87","8788.87","6273.47","2515.40","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","","1","Individual","","","","0","0","57465","0","2","0","0","36","13744","8","0","8","7445","56","73800","0","0","3","8","2498","4117","87.2","0","0","159","205","13","13","0","13","","2","","0","7","19","7","7","4","22","25","19","24","0","0","0","0","100","85.7","0","0","116647","57465","32100","42847","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8425","8425","8425"," 36 months"," 27.27%","345.18","E","E5","Senior Director Risk Management","3 years","MORTGAGE","450000","Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","020xx","MA","12.37","0","Oct-1997","0","","","21","0","36812","65.7%","37","w","0.00","0.00","8735.1489749534","8735.15","8425.00","310.15","0.0","0.0","0.0","Feb-2019","8754.3","","Mar-2020","0","","1","Joint App","515000","16.47","Not Verified","0","0","690320","0","6","1","6","12","152382","70","1","4","9744","68","56000","7","0","5","10","34516","11632","74.6","0","0","254","89","12","12","4","18","","4","","0","6","8","8","10","16","13","17","8","21","0","0","0","2","100","50","0","0","768304","189194","45800","189054","141905","Jun-2013","0","1","4","77.4","1","4","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 12.98%","227.43","B","B5","Printer","9 years","RENT","60000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","660xx","KS","14.9","0","May-2007","0","","112","7","1","10677","54.2%","12","w","7787.21","7787.21","3805.02","3805.02","2212.79","1592.23","0.0","0.0","0.0","May-2020","227.43","Jun-2020","May-2020","0","","1","Individual","","","","0","469","27595","0","2","1","1","11","16918","103","0","1","4337","76","19700","5","0","7","2","3942","4278","67.1","0","0","139","74","20","11","0","20","","0","","0","3","5","3","4","6","5","6","5","7","0","0","0","1","100","33.3","1","0","36200","27595","13000","16500","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 26.31%","903.73","E","E4","Casino Host","10+ years","OWN","62000","Source Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","920xx","CA","37.24","0","Oct-2007","0","","86","15","1","18890","39.8%","36","w","0.00","0.00","2645.41","2645.41","754.24","1891.17","0.0","0.0","0.0","Apr-2019","903.73","","May-2020","0","","1","Individual","","","","0","0","104590","1","2","1","2","6","85700","86","0","3","5976","49","47500","4","0","8","5","6973","17510","51.9","0","0","134","104","13","6","0","13","","6","","0","5","5","7","7","20","13","16","5","15","0","0","0","1","100","14.3","1","0","138354","104590","36400","90854","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 17.97%","469.79","D","D1","Help Tech Supervisor","10+ years","MORTGAGE","92360","Source Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","300xx","GA","27.44","0","Sep-2006","1","68","","18","0","32020","49.6%","30","w","8062.80","8062.80","7497.17","7497.17","4937.20","2559.97","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","","1","Individual","","","","0","0","131919","1","2","1","3","4","17310","60","0","2","6116","53","64600","1","4","1","5","7760","7140","70.7","0","0","120","147","16","4","2","18","","4","70","0","5","12","6","7","6","15","22","12","18","0","0","0","1","90","66.7","0","0","190803","49330","24400","28861","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","6500","6500","6500"," 36 months"," 11.80%","215.28","B","B4","Educator ","2 years","RENT","46500","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","352xx","AL","21.01","0","Aug-2011","1","61","","24","0","6741","41.6%","30","w","3889.63","3889.63","3438.09","3438.09","2610.37","827.72","0.0","0.0","0.0","May-2020","0.0","Jun-2020","May-2020","0","61","1","Individual","","","","0","0","40223","4","12","2","2","5","33482","97","7","12","3662","79","16200","2","0","4","14","1749","7694","42.2","0","0","88","72","1","1","0","3","","5","61","2","6","10","6","6","14","11","16","10","24","0","0","0","9","93.3","0","0","0","50845","40223","13300","34645","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 10.72%","244.55","B","B2","Program Manager","2 years","RENT","84000","Not Verified","Dec-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","600xx","IL","3.86","0","May-2005","1","","114","9","1","2200","12.6%","17","w","0.00","0.00","2829.93","2829.93","1465.61","484.09","0.0","880.23","158.4414","Sep-2019","244.55","","Mar-2020","0","","1","Individual","","","","0","0","381442","1","5","2","2","3","18633","111","0","2","2123","61","17400","3","1","3","5","42382","15200","12.6","0","0","163","105","13","3","1","13","","3","","0","2","2","3","4","10","3","6","2","9","0","0","0","2","76.5","0","1","0","403892","20833","17400","16812","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [0]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","2926.62","2926.62","3603.44","3603.44","2673.38","930.06","0.0","0.0","0.0","May-2020","190.21","Jun-2020","May-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","5280.05","5280.05","6580.1","6580.10","4719.95","1860.15","0.0","0.0","0.0","May-2020","346.76","Jun-2020","May-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","2613.06","2613.06","3223.0","3223.00","2386.94","836.06","0.0","0.0","0.0","May-2020","169.83","Jun-2020","May-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","5133.94","5005.59","6210.56","6055.30","4866.06","1344.50","0.0","0.0","0.0","May-2020","327.68","Jun-2020","May-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","5349.59","5349.59","6756.13","6756.13","4650.41","2105.72","0.0","0.0","0.0","May-2020","356.08","Jun-2020","May-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [5]:
df_housing = pd.read_csv('LoanStats_2018Q4.csv',skiprows=1,skipfooter=2, engine='python')
df_housing.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,20000,20000,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,...,50.0,0,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,...,85.7,0,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,8425,8425,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,...,50.0,0,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,...,33.3,1,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,...,14.3,1,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
print (df_housing.shape)

(128412, 144)

In [0]:
df_housing.dtypes.sort_index()

acc_now_delinq                                  int64
acc_open_past_24mths                            int64
addr_state                                     object
all_util                                      float64
annual_inc                                    float64
annual_inc_joint                              float64
application_type                               object
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
collection_recovery_fee                       float64
collections_12_mths_ex_med                      int64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
deferral_term                                 float64
delinq_2yrs                                     int64
delinq_amnt                                     int64
desc                                          float64
dti                                           float64
dti_joint                                     float64
earliest_cr_line                               object
emp_length                                     object
emp_title                                      object
funded_amnt                                     int64
funded_amnt_inv                               float64
grade                                          object
hardship_amount                               float64
hardship_dpd                                  float64
hardship_end_date                              object
hardship_flag                                  object
hardship_last_payment_amount                  float64
hardship_length                               float64
hardship_loan_status                           object
hardship_payoff_balance_amount                float64
hardship_reason                                object
hardship_start_date                            object
hardship_status                                object
hardship_type                                  object
home_ownership                                 object
id                                            float64
il_util                                       float64
initial_list_status                            object
inq_fi                                          int64
inq_last_12m                                    int64
inq_last_6mths                                  int64
installment                                   float64
int_rate                                       object
issue_d                                        object
last_credit_pull_d                             object
last_pymnt_amnt                               float64
last_pymnt_d                                   object
loan_amnt                                       int64
loan_status                                    object
max_bal_bc                                      int64
member_id                                     float64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_last_delinq                        float64
mths_since_last_major_derog                   float64
mths_since_last_record                        float64
mths_since_rcnt_il                            float64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
next_pymnt_d                                   object
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
open_acc                                        int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
open_rv_12m                                     int64
open_rv_24m                                     int64
orig_projected_additional_accrued_interest    float64
out_prncp                                     float64
out_prncp_inv                                 float64
payment_plan_start_date                        object
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
policy_code                                     int64
pub_rec                                         int64
pub_rec_bankruptcies                            int64
purpose                                        object
pymnt_plan                                     object
recoveries                                    float64
revol_bal                                       int64
revol_bal_joint                               float64
revol_util                                     object
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_mths_since_last_major_derog           float64
sec_app_num_rev_accts                         float64
sec_app_open_acc                              float64
sec_app_open_act_il                           float64
sec_app_revol_util                            float64
settlement_amount                             float64
settlement_date                                object
settlement_percentage                         float64
settlement_status                              object
settlement_term                               float64
sub_grade                                      object
tax_liens                                       int64
term                                           object
title                                          object
tot_coll_amt                                    int64
tot_cur_bal                                     int64
tot_hi_cred_lim                                 int64
total_acc                                       int64
total_bal_ex_mort                               int64
total_bal_il                                    int64
total_bc_limit                                  int64
total_cu_tl                                     int64
total_il_high_credit_limit                      int64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
total_rec_prncp                               float64
total_rev_hi_lim                                int64
url                                           float64
verification_status                            object
verification_status_joint                      object
zip_code                                       object
dtype: object

# Assignment Part 1 workout

- Convert the `term` column from string to integer.

In [0]:
df_housing['term'].value_counts()

 36 months    88179
 60 months    40233
Name: term, dtype: int64

In [0]:
term_modify = '36 months'

In [0]:
term_modify.strip('months').strip()

'36'

In [0]:
type(term_modify)

str

In [0]:
type(int(term_modify.strip('months').strip()))

int

In [0]:
def term_modify_int(cell_contents):
  return int(cell_contents.strip('months').strip())

In [0]:
df_housing['term'] = df_housing['term'].apply(term_modify_int)

In [81]:
df_housing['id'].dtypes

dtype('float64')

In [0]:
#Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.
def great(loan_status):
    if loan_status == 'Current' or loan_status == 'Fully Paid':
        return 1
    else:
        return 0
    
df_housing['loan_status_is_great'] = df_housing['loan_status'].apply(great)

In [0]:
print(df_housing['loan_status_is_great'].value_counts())
print(df_housing['loan_status'].value_counts())

1    116544
0     11868
Name: loan_status_is_great, dtype: int64
Current               86502
Fully Paid            30042
Charged Off            9103
Late (31-120 days)     1674
In Grace Period         827
Late (16-30 days)       238
Default                  26
Name: loan_status, dtype: int64

# **Assigment Part**  **2** workout
Make last_pymnt_d_month and last_pymnt_d_year columns.

In [84]:
[col for col in df_housing if col.endswith('d')]

['id',
 'member_id',
 'issue_d',
 'mths_since_last_record',
 'last_pymnt_d',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'num_accts_ever_120_pd',
 'num_tl_30dpd',
 'sec_app_collections_12_mths_ex_med',
 'hardship_dpd']

In [6]:
df_housing['last_pymnt_d'].dtypes

dtype('O')

In [11]:
df_housing['last_pymnt_d'].value_counts()

2020-05-01    84284
2020-06-01     3236
2019-07-01     3146
2019-09-01     2755
2019-10-01     2722
2019-08-01     2716
2019-12-01     2714
2019-05-01     2547
2020-04-01     2418
2019-11-01     2388
2020-03-01     2365
2019-04-01     2356
2020-01-01     2312
2019-06-01     2288
2019-03-01     1984
2019-02-01     1915
2020-02-01     1805
2019-01-01     1561
2018-12-01     1054
2020-07-01      770
2018-11-01      679
2018-10-01      234
2020-08-01        4
Name: last_pymnt_d, dtype: int64

In [0]:
df_housing['last_pymnt_d'] =  pd.to_datetime(df_housing['last_pymnt_d'], infer_datetime_format=True)

In [23]:

df_housing['last_pymnt_d'].head()

0   2020-02-01
1   2020-05-01
2   2019-02-01
3   2020-05-01
4   2019-04-01
Name: last_pymnt_d, dtype: datetime64[ns]

In [25]:
df_housing['last_pymnt_d'].dt.year.astype('Int64')

0         2020
1         2020
2         2019
3         2020
4         2019
          ...
128407    2018
128408    2020
128409    2020
128410    2020
128411    2020
Name: last_pymnt_d, Length: 128412, dtype: Int64

In [26]:

df_housing['last_pymnt_d_month'] = df_housing['last_pymnt_d'].dt.month.astype('Int64')
df_housing['last_pymnt_d_year'] = df_housing['last_pymnt_d'].dt.year.astype('Int64')
df_housing.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,...,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,last_pymnt_d_month,last_pymnt_d_year
0,NaN,NaN,20000,20000,20000.0,36 months,14.47%,688.13,C,C2,bus driver,4 years,OWN,52000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,681xx,NE,30.65,1,Jun-1979,2,15.0,NaN,6,0,15048,73%,22,w,0.00,0.00,8169.130000,8169.13,...,0,61699,33157,20700,40999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688.13,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,688.13,N,NaN,NaN,NaN,NaN,NaN,NaN,2,2020
1,NaN,NaN,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,Carpenter,10+ years,RENT,150000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,other,Other,917xx,CA,17.94,0,Nov-2001,1,NaN,NaN,24,0,43721,59.2%,29,w,9726.53,9726.53,8788.870000,8788.87,...,0,116647,57465,32100,42847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,5,2020
2,NaN,NaN,8425,8425,8425.0,36 months,27.27%,345.18,E,E5,Senior Director Risk Management,3 years,MORTGAGE,450000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,020xx,MA,12.37,0,Oct-1997,0,NaN,NaN,21,0,36812,65.7%,37,w,0.00,0.00,8735.148975,8735.15,...,0,768304,189194,45800,189054,141905.0,Jun-2013,0.0,1.0,4.0,77.4,1.0,4.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,2,2019
3,NaN,NaN,10000,10000,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0,May-2007,0,NaN,112.0,7,1,10677,54.2%,12,w,7787.21,7787.21,3805.020000,3805.02,...,0,36200,27595,13000,16500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,5,2020
4,NaN,NaN,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,Casino Host,10+ years,OWN,62000.0,Source Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,37.24,0,Oct-2007,0,NaN,86.0,15,1,18890,39.8%,36,w,0.00,0.00,2645.410000,2645.41,...,0,138354,104590,36400,90854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,4,2019

In [29]:
df_housing['last_pymnt_d'].value_counts()

2020-05-01    84284
2020-06-01     3236
2019-07-01     3146
2019-09-01     2755
2019-10-01     2722
2019-08-01     2716
2019-12-01     2714
2019-05-01     2547
2020-04-01     2418
2019-11-01     2388
2020-03-01     2365
2019-04-01     2356
2020-01-01     2312
2019-06-01     2288
2019-03-01     1984
2019-02-01     1915
2020-02-01     1805
2019-01-01     1561
2018-12-01     1054
2020-07-01      770
2018-11-01      679
2018-10-01      234
2020-08-01        4
Name: last_pymnt_d, dtype: int64

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01