<a href="https://colab.research.google.com/github/lindseyquinonez/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Lindsey_Quinonez_LS_DS15_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####
###LOADED DATASET###
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
pd.set_option('display.max_rows',150)
pd.set_option('display.max_columns',100)

--2020-04-08 03:40:50--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 54.69.167.66, 52.32.57.66, 50.112.132.61
Connecting to resources.lendingclub.com (resources.lendingclub.com)|54.69.167.66|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.3’

LoanStats_2018Q4.cs     [            <=>     ]  21.77M  1.95MB/s    in 11s

2020-04-08 03:41:02 (1.92 MB/s) - ‘LoanStats_2018Q4.csv.zip.3’ saved [22826918]

In [0]:
###EXTRACTED CSV FROM ZIPPED FOLDER###
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: LoanStats_2018Q4.csv

In [0]:

###USING BASH/SHELL COMMANDS TO LOOK AT THE RAW DATA###
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","35000","35000","35000"," 36 months"," 14.47%","1204.23","C","C2","Staff Physician","8 years","MORTGAGE","360000","Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","336xx","FL","19.9","0","Apr-1995","1","","","24","0","57259","43.2%","51","w","0.00","0.00","38187.0468373662","38187.05","35000.00","3187.05","0.0","0.0","0.0","Aug-2019","29882.16","","Sep-2019","0","","1","Individual","","","","0","0","828060","0","6","1","2","9","112027","29","4","8","19118","36","132400","3","2","5","11","34503","67341","46","0","0","173","284","8","8","3","8","","0","","0","11","11","13","20","23","16","24","11","24","0","0","0","5","100","30.8","0","0","1222051","169286","124600","258401","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 22.35%","191.86","D","D5","Director of Sales","10+ years","MORTGAGE","72000","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","333xx","FL","20.12","0","Mar-2010","0","","","13","0","11720","47.1%","26","f","0.00","0.00","5615.9776735688","5615.98","5000.00","615.98","0.0","0.0","0.0","Jul-2019","4474.13","","Aug-2019","0","","1","Individual","","","","0","534","189279","0","1","0","1","18","22698","","0","0","4056","47","24900","1","0","1","2","14560","8163","55.1","0","0","105","90","29","8","5","40","","9","","0","6","11","6","8","4","11","17","11","13","0","0","0","1","100","50","0","0","218686","34418","18200","37786","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 60 months"," 23.40%","284.21","E","E1","","< 1 year","RENT","55000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","902xx","CA","13.51","0","Apr-2007","0","44","88","9","1","11859","53.9%","11","w","8462.43","8462.43","4243.65","4243.65","1537.57","2706.08","0.0","0.0","0.0","Mar-2020","284.21","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","21235","0","1","0","1","20","9376","76","0","3","3122","62","22000","1","0","0","4","2359","1119","89.3","0","0","140","140","13","13","0","13","","15","44","0","4","7","4","5","2","8","9","7","9","0","0","0","0","90.9","100","1","0","34386","21235","10500","12386","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","17100","17100","17100"," 36 months"," 18.94%","626.3","D","D2","Receptionist ","10+ years","RENT","38000","Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","150xx","PA","38.09","0","Mar-1998","1","47","","14","0","15323","53%","21","w","11120.22","11120.22","9367.51","9367.51","5979.78","3387.73","0.0","0.0","0.0","Mar-2020","626.3","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","43351","1","2","1","1","10","28028","67","1","5","7533","53","29170","0","0","2","6","3096","4150","77","0","0","125","230","5","5","2","5","","5","","0","4","12","5","5","5","12","14","9","14","","0","0","2","95","75","0","0","70954","43351","16600","41784","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 10.72%","130.43","B","B2","Extrusion assistant ","10+ years","MORTGAGE","56000","Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","301xx","GA","31.03","0","Sep-2006","0","","","7","0","4518","28.6%","11","w","2487.19","2487.19","1943.36","1943.36","1512.81","430.55","0.0","0.0","0.0","Mar-2020","130.43","Apr-2020","Mar-2020","1","","1","Individual","","","","0","136","192983","0","2","0","2","14","66857","","0","3","1608","29","15800","3","0","0","5","27569","7835","36.3","0","0","147","29","22","14","1","22","","17","","0","3","4","3","3","6","4","4","4","7","0","0","0","0","100","0","0","0","221310","71375","12300","77865","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10475","10475","10475"," 36 months"," 11.31%","344.48","B","B3","Teacher","6 years","RENT","66150","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","786xx","TX","7.4","0","Jun-1991","0","28","","10","0","10499","40.2%","17","w","6535.06","6535.06","5157.33","5157.33","3939.94","1217.39","0.0","0.0","0.0","Mar-2020","344.48","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","10499","1","0","0","0","84","0","","3","5","3841","40","26100","2","1","5","5","1312","14847","36.8","0","0","88","330","3","3","2","7","","1","28","0","5","8","7","8","2","10","13","8","10","0","0","0","3","88.2","60","0","0","26100","10499","23500","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","7500","7500","7500"," 36 months"," 11.31%","246.65","B","B3","Supervisor","7 years","MORTGAGE","40500","Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","604xx","IL","31.61","0","Sep-1996","1","","","23","0","14218","16.3%","33","w","4862.42","4862.42","3508.34","3508.34","2637.58","855.76","15.0","0.0","0.0","Mar-2020","1016.6","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","123779","3","2","1","1","12","8096","29","3","6","2972","19","87000","0","0","2","7","5626","21078","23.9","0","0","59","267","1","1","1","6","","6","","0","4","6","7","10","2","20","30","6","23","0","0","0","4","100","0","0","0","221569","22314","27700","28409","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","3600","3600","3600"," 36 months"," 11.80%","119.23","B","B4","Analyst","5 years","MORTGAGE","50000","Source Verified","Dec-2018","Fully Paid","n","","","other","Other","427xx","KY","16.11","0","Jan-2002","2","","","10","0","5865","17.4%","17","w","0.00","0.00","4004.1696442235","4004.17","3600.00","404.17","0.0","0.0","0.0","Feb-2020","2678.48","","Mar-2020","0","","1","Individual","","","","0","0","243415","3","3","1","2","3","68184","95","1","3","0","53","33700","2","1","10","6","24342","17300","0","0","0","203","198","4","3","1","18","","3","","1","0","1","4","6","6","6","10","1","10","0","0","0","3","93.8","0","0","0","272629","74049","17300","68929","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [0]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3235.65","3235.65","3223.02","3223.02","2364.35","858.67","0.0","0.0","0.0","Mar-2020","190.21","Apr-2020","Mar-2020","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","5831.03","5831.03","5886.58","5886.58","4168.97","1717.61","0.0","0.0","0.0","Mar-2020","346.76","Apr-2020","Mar-2020","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","2888.98","2888.98","2883.34","2883.34","2111.02","772.32","0.0","0.0","0.0","Mar-2020","169.83","Apr-2020","Mar-2020","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","5687.01","5544.84","5555.2","5416.32","4312.99","1242.21","0.0","0.0","0.0","Mar-2020","327.68","Apr-2020","Mar-2020","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","5899.34","5899.34","6043.97","6043.97","4100.66","1943.31","0.0","0.0","0.0","Mar-2020","356.08","Apr-2020","Mar-2020","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [0]:
##BROWSING THROUGH THE RAW DATA, WE CAN SEE THAT THERE WILL BE ALOT OF MISSING DATA##
Loan_Stats = pd.read_csv('LoanStats_2018Q4.csv')
print(Loan_Stats.shape)
Loan_Stats.head(20)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128415, 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title                           emp_length home_ownership annual_inc verification_status issue_d  loan_status        pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt      total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       35000     35000       35000            36 months  14.47%  1204.23     C     C2        Staff Physician                     8 years    MORTGAGE       360000     Verified            Dec-2018 Fully Paid         n          NaN NaN  credit_card        Credit card refinancing 336xx    FL         19.9  0           Apr-1995         1              NaN                    NaN                    24       0       57259     43.2%      51        w                   0.00      0.00          38187.0468373662 38187.05        35000.00        3187.05       0.0                0.0        0.0                     Aug-2019     29882.16        NaN          Sep-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            828060      0           6           1           2           9                  112027       29      4           8           19118      36       132400           3      2           5            11                   34503       67341          46      0                        0           173                284                  8                     8              3        8                    NaN                      0                     NaN                            0                     11             11              13          20        23        16            24            11                  24       0                0            0                  5                  100            30.8             0                    0         1222051         169286            124600         258401                     NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              5000      5000        5000             36 months  22.35%  191.86      D     D5        Director of Sales                   10+ years  MORTGAGE       72000      Source Verified     Dec-2018 Fully Paid         n          NaN NaN  debt_consolidation Debt consolidation      333xx    FL         20.12 0           Mar-2010         0              NaN                    NaN                    13       0       11720     47.1%      26        f                   0.00      0.00          5615.9776735688  5615.98         5000.00         615.98        0.0                0.0        0.0                     Jul-2019     4474.13         NaN          Aug-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              534          189279      0           1           0           1           18                 22698        NaN     0           0           4056       47       24900            1      0           1            2                    14560       8163           55.1    0                        0           105                90                   29                    8              5        40                   NaN                      9                     NaN                            0                     6              11              6           8         4         11            17            11                  13       0                0            0                  1                  100            50               0                    0         218686          34418             18200          37786                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              10000     10000       10000            60 months  23.40%  284.21      E     E1        NaN                                 < 1 year   RENT           55000      Source Verified     Dec-2018 Current            n          NaN NaN  debt_consolidation Debt consolidation      902xx    CA         13.51 0           Apr-2007         0              44                     88                     9        1       11859     53.9%      11        w                   8462.43   8462.43       4243.65          4243.65         1537.57         2706.08       0.0                0.0        0.0                     Mar-2020     284.21          Apr-2020     Mar-2020           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            21235       0           1           0           1           20                 9376         76      0           3           3122       62       22000            1      0           0            4                    2359        1119           89.3    0                        0           140                140                  13                    13             0        13                   NaN                      15                    44                             0                     4              7               4           5         2         8             9             7                   9        0                0            0                  0                  90.9           100              1                    0         34386           21235             10500          12386                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              17100     17100       17100            36 months  18.94%  626.3       D     D2        Receptionist                        10+ years  RENT           38000      Verified            Dec-2018 Current            n          NaN NaN  debt_consolidation Debt consolidation      150xx    PA         38.09 0           Mar-1998         1              47                     NaN                    14       0       15323     53%        21        w                   11120.22  11120.22      9367.51          9367.51         5979.78         3387.73       0.0                0.0        0.0                     Mar-2020     626.3           Apr-2020     Mar-2020           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            43351       1           2           1           1           10                 28028        67      1           5           7533       53       29170            0      0           2            6                    3096        4150           77      0                        0           125                230                  5                     5              2        5                    NaN                      5                     NaN                            0                     4              12              5           5         5         12            14            9                   14       NaN              0            0                  2                  95             75               0                    0         70954           43351             16600          41784                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              4000      4000        4000             36 months  10.72%  130.43      B     B2        Extrusion assistant                 10+ years  MORTGAGE       56000      Verified            Dec-2018 Current            n          NaN NaN  credit_card        Credit card refinancing 301xx    GA         31.03 0           Sep-2006         0              NaN                    NaN                    7        0       4518      28.6%      11        w                   2487.19   2487.19       1943.36          1943.36         1512.81         430.55        0.0                0.0        0.0                     Mar-2020     130.43          Apr-2020     Mar-2020           1                          NaN                         1           Individual       NaN              NaN       NaN                       0              136          192983      0           2           0           2           14                 66857        NaN     0           3           1608       29       15800            3      0           0            5                    27569       7835           36.3    0                        0           147                29                   22                    14             1        22                   NaN                      17                    NaN                            0                     3              4               3           3         6         4             4             4                   7        0                0            0                  0                  100            0                0                    0         221310          71375             12300          77865                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              10475     10475       10475            36 months  11.31%  344.48      B     B3        Teacher                             6 years    RENT           66150      Source Verified     Dec-2018 Current            n          NaN NaN  debt_consolidation Debt consolidation      786xx    TX         7.4   0           Jun-1991         0              28                     NaN                    10       0       10499     40.2%      17        w                   6535.06   6535.06       5157.33          5157.33         3939.94         1217.39       0.0                0.0        0.0                     Mar-2020     344.48          Apr-2020     Mar-2020           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            10499       1           0           0           0           84                 0            NaN     3           5           3841       40       26100            2      1           5            5                    1312        14847          36.8    0                        0           88                 330                  3                     3              2        7                    NaN                      1                     28                             0                     5              8               7           8         2         10            13            8                   10       0                0            0                  3                  88.2           60               0                    0         26100           10499             23500          0                          NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

In [0]:
Loan_Stats.tail(10)
##TWO EXTRA ROWS AT THE BOTTOM. N/NA/NaN VALUES. HAVE TO COME BACK TO THIS##

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
NaN                                              NaN 22000 22000 22000  60 months   7.84% 444.4  A   A4  Owner                      10+ years MORTGAGE 55000.0 Not Verified    Oct-2018 Current     n   NaN NaN other              Other                   982xx WA  2.18  0   Apr-1987 0   NaN  NaN  8   0   6310    14.3% 21  w   16612.59 16612.59 7545.22         7545.22 5387.41 2157.81 0.0 0.0 0.0 Mar-2020 444.4   Apr-2020 Mar-2020 0   NaN  1   Individual NaN NaN NaN 0   0    159636.0 0   0   0   0   33.0 0       NaN   0   3   5436  14.0 44200 0   0   0   3   19955.0 31090.0 16.9 0   0   128.0 376 17  17  2   17.0  NaN  23.0 NaN  0   2   2   5   9   7   7   12  2   8   0.0 0   0   0   100.0 20.0  0   0   204200.0 6310  37400 0       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     5000  5000  5000   36 months  16.14% 176.14 C   C4  Oncology Medical Assistant 3 years   MORTGAGE 46400.0 Source Verified Oct-2018 Fully Paid  n   NaN NaN debt_consolidation Debt consolidation      338xx FL  16.85 0   Nov-2003 0   29.0 NaN  10  0   6722    62.2% 18  w   0.0      0.0      5436.0267199262 5436.03 5000.0  436.03  0.0 0.0 0.0 Apr-2019 4550.84 NaN      Jun-2019 0   30.0 1   Individual NaN NaN NaN 0   0    140818.0 0   1   1   1   10.0 13257   89.0  1   5   1287  78.0 10800 2   4   5   6   14082.0 114.0   96.2 0   0   120.0 178 10  10  1   15.0  29.0 10.0 29.0 3   3   5   3   4   3   8   14  5   10  0.0 0   0   2   72.2  100.0 0   0   161585.0 19979 3000  14875   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     5600  5600  5600   36 months  13.56% 190.21 C   C1  NaN                        NaN       RENT     15600.0 Not Verified    Oct-2018 Current     n   NaN NaN credit_card        Credit card refinancing 836xx ID  15.31 0   Aug-2012 0   NaN  97.0 9   1   5996    34.5% 11  w   3235.65  3235.65  3223.02         3223.02 2364.35 858.67  0.0 0.0 0.0 Mar-2020 190.21  Apr-2020 Mar-2020 0   NaN  1   Individual NaN NaN NaN 0   0    5996.0   0   0   0   1   20.0 0       NaN   0   2   3017  35.0 17400 1   0   0   3   750     4689.0  45.5 0   0   20.0  73  13  13  0   13.0  NaN  20.0 NaN  0   3   5   4   4   1   9   10  5   9   0.0 0   0   0   100.0 25.0  1   0   17400    5996  8600  0       NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     23000 23000 23000  36 months  15.02% 797.53 C   C3  Tax Consultant             10+ years MORTGAGE 75000.0 Source Verified Oct-2018 Charged Off n   NaN NaN debt_consolidation Debt consolidation      352xx AL  20.95 1   Aug-1985 2   22.0 NaN  12  0   22465.0 43.6% 28  w   0.0      0.0      1547.08         1547.08 1025.67 521.41  0.0 0.0 0.0 Dec-2018 797.53  NaN      Nov-2018 0   NaN  1   Individual NaN NaN NaN 0   0    259658.0 4   2   3   3   6.0  18149   86.0  4   6   12843 56.0 51500 2   2   5   11  21638   26321.0 44.1 0   0   12.0  397 4   4   6   5.0   22.0 4.0  22.0 0   4   5   7   14  3   9   19  5   12  0.0 0   0   7   96.4  14.3  0   0   296500.0 40614 47100 21000   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     10000 10000 10000  36 months  15.02% 346.76 C   C3  security guard             5 years   MORTGAGE 38000.0 Not Verified    Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      443xx OH  13.16 3   Jul-1982 0   6.0  NaN  11  0   5634    37.1% 16  w   5831.03  5831.03  5886.58         5886.58 4168.97 1717.61 0.0 0.0 0.0 Mar-2020 346.76  Apr-2020 Mar-2020 0   NaN  1   Individual NaN NaN NaN 0   155  77424.0  0   1   0   0   34.0 200     10.0  1   1   1866  42.0 15200 2   0   0   2   7039.0  4537.0  50.1 0   0   34.0  434 11  11  3   11.0  6.0  17.0 6.0  0   3   5   5   6   1   8   11  5   11  0.0 0   0   1   73.3  40.0  0   0   91403.0  9323  9100  2000    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     5000  5000  5000   36 months  13.56% 169.83 C   C1  Payoff Clerk               10+ years MORTGAGE 35360.0 Not Verified    Oct-2018 Current     n   NaN NaN debt_consolidation Debt consolidation      381xx TN  11.3  1   Jun-2006 0   21.0 NaN  9   0   2597    27.3% 15  f   2888.98  2888.98  2883.34         2883.34 2111.02 772.32  0.0 0.0 0.0 Mar-2020 169.83  Apr-2020 Mar-2020 0   NaN  1   Individual NaN NaN NaN 0   1413 69785    0   2   0   1   16.0 2379    40.0  3   4   1826  32.0 9500  0   0   1   5   8723    1174.0  60.9 0   0   147.0 85  9   9   2   10.0  21.0 9.0  21.0 0   1   3   2   2   6   6   7   3   9   0.0 0   0   3   92.9  50.0  0   0   93908    4976  3000  6028.0  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                     10000 10000 9750   36 months  11.06% 327.68 B   B3  NaN                        NaN       RENT     44400.0 Source Verified Oct-2018 Current     n   NaN NaN credit_card        Credit card refinancing 980xx WA  11.78 0   Oct-2008 2   40.0 NaN  15  0   6269    13.1% 25  f   5687.01  5544.84  5555.2          5416.32 4312.99 1242.21 0.0 0.0 0.0 Mar-2020 327.68  Apr-2020 Mar-2020 0   53.0 1   Individual NaN NaN NaN 0   520  16440    3   1   1   1   2.0  10171   100.0 2   5   404   28.0 47700 0   3   5   6   1265.0  20037.0 2.3  0   0   61.0  119 1   1   0   1.0   NaN  1.0  40.0 1   2   4   6   8   3   14  22  4   15  0.0 0   0   3   92.0  0.0   0   0   57871.0  16440 20500 10171.0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
                                                                 10000  36 months  16.91% 356.08 C   C5  Key Accounts Manager       2 years   RENT     80000.0 Not Verified    Oct-2018 Current     n   NaN NaN other              Other                   021xx MA  17.72 1   Sep-2006 0   14.0 NaN  17  0   1942    30.8% 31  w   5899.34  5899.34  6043.97         6043.97 4100.66 1943.31 0.0 0.0 0.0 Mar-2020 356.08  Apr-2020 Mar-2020 0   25.0 1   Individual NaN NaN NaN 0   0    59194    0   15  1   1   12.0 57252.0 85.0  0   0   1942  80.0 6300  0   5   0   1   3482    2058.0  48.5 0   0   144.0 142 40  12  0   131.0 30.0 NaN  30.0 3   1   1   1   5   22  2   9   1   17  0.0 0   0   1   74.2  0.0   0   0   73669    59194 4000  67369   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N   NaN NaN NaN NaN NaN                                                NaN
Total amount funded in policy code 1: 2050909275 NaN NaN   NaN   NaN   NaN        NaN     NaN    NaN NaN NaN                        NaN       NaN      NaN     NaN             NaN      NaN         NaN NaN NaN NaN                NaN                     NaN   NaN NaN   NaN NaN      NaN NaN  NaN  NaN NaN NaN     NaN   NaN NaN NaN      NaN      NaN             NaN     NaN     NaN     NaN NaN NaN NaN      NaN     NaN      NaN      NaN NaN  NaN NaN        NaN NaN NaN NaN NaN  NaN      NaN NaN NaN NaN NaN  NaN     NaN   NaN NaN NaN   NaN  NaN   NaN NaN NaN NaN NaN     NaN     NaN  NaN NaN NaN   NaN NaN NaN NaN NaN   NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN NaN NaN      NaN   NaN   NaN     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN                                                NaN
Total amount funded in policy code 2: 820109297  NaN NaN   NaN   NaN   NaN        NaN     NaN    NaN NaN NaN                        NaN       NaN      NaN     NaN             NaN      NaN         NaN NaN NaN NaN                NaN                     NaN   NaN NaN   NaN NaN      NaN NaN  NaN  NaN NaN NaN     NaN   NaN NaN NaN      NaN      NaN             NaN     NaN     NaN     NaN NaN NaN NaN      NaN     NaN      NaN      NaN NaN  NaN NaN        NaN NaN NaN NaN NaN  NaN      NaN NaN NaN NaN NaN  NaN     NaN   NaN NaN NaN   NaN  NaN   NaN NaN NaN NaN NaN     NaN     NaN  NaN NaN NaN   NaN NaN NaN NaN NaN   NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   NaN   NaN NaN NaN      NaN   NaN   NaN     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN                                                NaN

In [0]:
##EVERYTHING IS A HEADER, SO TIME TO FIX THAT##
Loan_Stats = pd.read_csv('LoanStats_2018Q4.csv', header=1)
print(Loan_Stats.shape)
Loan_Stats.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,35000.0,35000.0,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,336xx,FL,19.90,0.0,Apr-1995,1.0,NaN,NaN,24.0,0.0,57259.0,43.2%,51.0,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0.0,...,23.0,16.0,24.0,11.0,24.0,0.0,0.0,0.0,5.0,100.0,30.8,0.0,0.0,1222051.0,169286.0,124600.0,258401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,5000.0,5000.0,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,333xx,FL,20.12,0.0,Mar-2010,0.0,NaN,NaN,13.0,0.0,11720.0,47.1%,26.0,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0.0,...,4.0,11.0,17.0,11.0,13.0,0.0,0.0,0.0,1.0,100.0,50.0,0.0,0.0,218686.0,34418.0,18200.0,37786.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,10000.0,10000.0,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,902xx,CA,13.51,0.0,Apr-2007,0.0,44.0,88.0,9.0,1.0,11859.0,53.9%,11.0,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0.0,...,2.0,8.0,9.0,7.0,9.0,0.0,0.0,0.0,0.0,90.9,100.0,1.0,0.0,34386.0,21235.0,10500.0,12386.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,17100.0,17100.0,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,150xx,PA,38.09,0.0,Mar-1998,1.0,47.0,NaN,14.0,0.0,15323.0,53%,21.0,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0.0,...,5.0,12.0,14.0,9.0,14.0,NaN,0.0,0.0,2.0,95.0,75.0,0.0,0.0,70954.0,43351.0,16600.0,41784.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,4000.0,4000.0,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,301xx,GA,31.03,0.0,Sep-2006,0.0,NaN,NaN,7.0,0.0,4518.0,28.6%,11.0,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1.0,...,6.0,4.0,4.0,4.0,7.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,221310.0,71375.0,12300.0,77865.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
Loan_Stats.isnull().sum()
#This shows us that there are two rows that are showing NaN across the board. To drop them, skipfooter must be used.

id                                            128412
member_id                                     128414
loan_amnt                                          2
funded_amnt                                        2
funded_amnt_inv                                    2
term                                               2
int_rate                                           2
installment                                        2
grade                                              2
sub_grade                                          2
emp_title                                      20949
emp_length                                     11706
home_ownership                                     2
annual_inc                                         2
verification_status                                2
issue_d                                            2
loan_status                                        2
pymnt_plan                                         2
url                                           128414
desc                                          128414
purpose                                            2
title                                              2
zip_code                                           2
addr_state                                         2
dti                                              239
delinq_2yrs                                        2
earliest_cr_line                                   2
inq_last_6mths                                     2
mths_since_last_delinq                         72198
mths_since_last_record                        112964
open_acc                                           2
pub_rec                                            2
revol_bal                                          2
revol_util                                       158
total_acc                                          2
initial_list_status                                2
out_prncp                                          2
out_prncp_inv                                      2
total_pymnt                                        2
total_pymnt_inv                                    2
total_rec_prncp                                    2
total_rec_int                                      2
total_rec_late_fee                                 2
recoveries                                         2
collection_recovery_fee                            2
last_pymnt_d                                     161
last_pymnt_amnt                                    2
next_pymnt_d                                   34636
last_credit_pull_d                                 3
collections_12_mths_ex_med                         2
mths_since_last_major_derog                    99234
policy_code                                        2
application_type                                   2
annual_inc_joint                              111632
dti_joint                                     111632
verification_status_joint                     113566
acc_now_delinq                                     2
tot_coll_amt                                       2
tot_cur_bal                                        2
open_acc_6m                                        2
open_act_il                                        2
open_il_12m                                        2
open_il_24m                                        2
mths_since_rcnt_il                              4480
total_bal_il                                       2
il_util                                        20276
open_rv_12m                                        2
open_rv_24m                                        2
max_bal_bc                                         2
all_util                                          39
total_rev_hi_lim                                   2
inq_fi                                             2
total_cu_tl                                        2
inq_last_12m                                       2
acc_open_past_24mths                               2
avg_cur_bal                                       15
bc_open_to_buy                                  1693
bc_util                                         1756
chargeoff_within_12_mths                           2
delinq_amnt                                        2
mo_sin_old_il_acct                              4480
mo_sin_old_rev_tl_op                               2
mo_sin_rcnt_rev_tl_op                              2
mo_sin_rcnt_tl                                     2
mort_acc                                           2
mths_since_recent_bc                            1593
mths_since_recent_bc_dlq                      103245
mths_since_recent_inq                          16049
mths_since_recent_revol_delinq                 91632
num_accts_ever_120_pd                              2
num_actv_bc_tl                                     2
num_actv_rev_tl                                    2
num_bc_sats                                        2
num_bc_tl                                          2
num_il_tl                                          2
num_op_rev_tl                                      2
num_rev_accts                                      2
num_rev_tl_bal_gt_0                                2
num_sats                                           2
num_tl_120dpd_2m                                2861
num_tl_30dpd                                       2
num_tl_90g_dpd_24m                                 2
num_tl_op_past_12m                                 2
pct_tl_nvr_dlq                                     2
percent_bc_gt_75                                1694
pub_rec_bankruptcies                               2
tax_liens                                          2
tot_hi_cred_lim                                    2
total_bal_ex_mort                                  2
total_bc_limit                                     2
total_il_high_credit_limit                         2
revol_bal_joint                               111632
sec_app_earliest_cr_line                      111632
sec_app_inq_last_6mths                        111632
sec_app_mort_acc                              111632
sec_app_open_acc                              111632
sec_app_revol_util                            111890
sec_app_open_act_il                           111632
sec_app_num_rev_accts                         111632
sec_app_chargeoff_within_12_mths              111632
sec_app_collections_12_mths_ex_med            111632
sec_app_mths_since_last_major_derog           123260
hardship_flag                                      2
hardship_type                                 128102
hardship_reason                               128102
hardship_status                               128102
deferral_term                                 128102
hardship_amount                               128102
hardship_start_date                           128102
hardship_end_date                             128102
payment_plan_start_date                       128102
hardship_length                               128102
hardship_dpd                                  128102
hardship_loan_status                          128102
orig_projected_additional_accrued_interest    128155
hardship_payoff_balance_amount                128102
hardship_last_payment_amount                  128102
debt_settlement_flag                               2
debt_settlement_flag_date                     127674
settlement_status                             127674
settlement_date                               127674
settlement_amount                             127674
settlement_percentage                         127674
settlement_term                               127674
dtype: int64

In [0]:
#Here, I was able to remove the last two rows that were giving us trouble
Loan_Stats = pd.read_csv('LoanStats_2018Q4.csv', header=1, skipfooter=2)
print(Loan_Stats.shape)
Loan_Stats.tail()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

(128412, 144)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
128407,NaN,NaN,23000,23000,23000.0,36 months,15.02%,797.53,C,C3,Tax Consultant,10+ years,MORTGAGE,75000.0,Source Verified,Oct-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,352xx,AL,20.95,1,Aug-1985,2,22.0,NaN,12,0,22465,43.6%,28,w,0.00,0.00,1547.08,1547.08,1025.67,521.41,0.0,0.0,0.0,Dec-2018,797.53,NaN,Nov-2018,0,...,3,9,19,5,12,0.0,0,0,7,96.4,14.3,0,0,296500,40614,47100,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128408,NaN,NaN,10000,10000,10000.0,36 months,15.02%,346.76,C,C3,security guard,5 years,MORTGAGE,38000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,443xx,OH,13.16,3,Jul-1982,0,6.0,NaN,11,0,5634,37.1%,16,w,5831.03,5831.03,5886.58,5886.58,4168.97,1717.61,0.0,0.0,0.0,Mar-2020,346.76,Apr-2020,Mar-2020,0,...,1,8,11,5,11,0.0,0,0,1,73.3,40.0,0,0,91403,9323,9100,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128409,NaN,NaN,5000,5000,5000.0,36 months,13.56%,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,381xx,TN,11.30,1,Jun-2006,0,21.0,NaN,9,0,2597,27.3%,15,f,2888.98,2888.98,2883.34,2883.34,2111.02,772.32,0.0,0.0,0.0,Mar-2020,169.83,Apr-2020,Mar-2020,0,...,6,6,7,3,9,0.0,0,0,3,92.9,50.0,0,0,93908,4976,3000,6028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000,10000,9750.0,36 months,11.06%,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,980xx,WA,11.78,0,Oct-2008,2,40.0,NaN,15,0,6269,13.1%,25,f,5687.01,5544.84,5555.20,5416.32,4312.99,1242.21,0.0,0.0,0.0,Mar-2020,327.68,Apr-2020,Mar-2020,0,...,3,14,22,4,15,0.0,0,0,3,92.0,0.0,0,0,57871,16440,20500,10171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000,10000,10000.0,36 months,16.91%,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,NaN,NaN,other,Other,021xx,MA,17.72,1,Sep-2006,0,14.0,NaN,17,0,1942,30.8%,31,w,5899.34,5899.34,6043.97,6043.97,4100.66,1943.31,0.0,0.0,0.0,Mar-2020,356.08,Apr-2020,Mar-2020,0,...,22,2,9,1,17,0.0,0,0,1,74.2,0.0,0,0,73669,59194,4000,67369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
Loan_Stats.isnull().sum()

id                                            128412
member_id                                     128412
loan_amnt                                          0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
emp_title                                      20947
emp_length                                     11704
home_ownership                                     0
annual_inc                                         0
verification_status                                0
issue_d                                            0
loan_status                                        0
pymnt_plan                                         0
url                                           128412
desc                                          128412
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
dti                                              237
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
mths_since_last_delinq                         72196
mths_since_last_record                        112962
open_acc                                           0
pub_rec                                            0
revol_bal                                          0
revol_util                                       156
total_acc                                          0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
total_rec_int                                      0
total_rec_late_fee                                 0
recoveries                                         0
collection_recovery_fee                            0
last_pymnt_d                                     159
last_pymnt_amnt                                    0
next_pymnt_d                                   34634
last_credit_pull_d                                 1
collections_12_mths_ex_med                         0
mths_since_last_major_derog                    99232
policy_code                                        0
application_type                                   0
annual_inc_joint                              111630
dti_joint                                     111630
verification_status_joint                     113564
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
mths_since_rcnt_il                              4478
total_bal_il                                       0
il_util                                        20274
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
all_util                                          37
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
avg_cur_bal                                       13
bc_open_to_buy                                  1691
bc_util                                         1754
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_il_acct                              4478
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
mths_since_recent_bc                            1591
mths_since_recent_bc_dlq                      103243
mths_since_recent_inq                          16047
mths_since_recent_revol_delinq                 91630
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_sats                                           0
num_tl_120dpd_2m                                2859
num_tl_30dpd                                       0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     0
percent_bc_gt_75                                1692
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
sec_app_mths_since_last_major_derog           123258
hardship_flag                                      0
hardship_type                                 128100
hardship_reason                               128100
hardship_status                               128100
deferral_term                                 128100
hardship_amount                               128100
hardship_start_date                           128100
hardship_end_date                             128100
payment_plan_start_date                       128100
hardship_length                               128100
hardship_dpd                                  128100
hardship_loan_status                          128100
orig_projected_additional_accrued_interest    128153
hardship_payoff_balance_amount                128100
hardship_last_payment_amount                  128100
debt_settlement_flag                               0
debt_settlement_flag_date                     127672
settlement_status                             127672
settlement_date                               127672
settlement_amount                             127672
settlement_percentage                         127672
settlement_term                               127672
dtype: int64

In [0]:
# .drop() TELLS CODE TO DROP A ROW (AUTOMATICALLY THINKS ROW)
#axis=1 tells pandas to drop columns and NOT rows.
Loan_Stats= Loan_Stats.drop(['url', 'member_id', 'id', 'desc'], axis=1)
Loan_Stats.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,...,23,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,...,4,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,2,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,5,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,...,6,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
#SHOWS US THE FIRST 10 ROWS OF COLUMN 'int_rate'
Loan_Stats['int_rate'].head(10)

0     14.47%
1     22.35%
2     23.40%
3     18.94%
4     10.72%
5     11.31%
6     11.31%
7     11.80%
8     11.80%
9     18.94%
Name: int_rate, dtype: object

In [0]:
#HERE, I CAN SEE THAT THE VALUE CONTAINS WHITESPACE AND IS A STRING. 
#I NEED TO MAKE THIS STRING VALUE A FLOAT SO THAT I CAN MANIPULATE THE DATA IN A MORE CONSTRUCTIVE WAY.
Loan_Stats['int_rate'][0]

' 14.47%'

In [0]:
##CREATING FUNCTION TO STRIP int_rate VALUES OF THEIR WHITESPACE AND '?'##
def int_rate_to_float(dirty_int_rate):
  return float(dirty_int_rate.strip().strip('%'))

In [0]:
## CASTING int_rate COLUMN VALUES TO A FLOAT##
Loan_Stats['int_rate'].apply(int_rate_to_float)

0         14.47
1         22.35
2         23.40
3         18.94
4         10.72
          ...
128407    15.02
128408    15.02
128409    13.56
128410    11.06
128411    16.91
Name: int_rate, Length: 128412, dtype: float64

In [0]:
##HERE, I AM CREATING A NEW COLUMN TITLED 'int_rate_cleaned' AND ASSIGNING IT 
#THE "NEW" FLOAT VALUES 
Loan_Stats['int_rate_cleaned'] = Loan_Stats['int_rate'].apply(int_rate_to_float) 
Loan_Stats.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,...,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,...,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,NaN,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,...,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72

In [0]:
type(Loan_Stats['int_rate_cleaned'])

pandas.core.series.Series

In [0]:
##Look at the top 20 employment titles
#The .value_counts(dropna=False) allows us to get the count for each employment
#title along with the count of missing employment titles.
Loan_Stats['emp_title'].value_counts(dropna=False).head(20)

NaN                   20947
Teacher                2090
Manager                1773
Registered Nurse        952
Driver                  924
RN                      726
Supervisor              697
Sales                   580
Project Manager         526
General Manager         523
Office Manager          521
Owner                   420
Director                402
Operations Manager      387
Truck Driver            387
Nurse                   326
Engineer                325
Sales Manager           304
manager                 301
Supervisor              270
Name: emp_title, dtype: int64

In [0]:
#How many different unique employment titles are there currently?
# .nunique gives us the number of unique values in the column.
# This can also be done using the len() function. Gives us the number of employment titles in the column.
#len(Loan_Stats['emp_title'].value_counts())
Loan_Stats['emp_title'].nunique()

43892

In [0]:
#How often is the emplyment_title null?
Loan_Stats['emp_title'].isnull().sum()

20947

In [0]:
#Create some examples that represent the cases that we want to clean up
import numpy as np

examples = ['owner', 'Supervisor', ' Project Manager', np.NaN]

In [0]:
 #Write a function to clean up these cases and increase uniformity.
 #The error shows me that np.Nan is NOT a string and therefore cannot be manipulated with .strip()
 #A np.NaN value is a float
 #Type checking needs to be completed. isinstance()
 # .title() - Title Casing allows us to uppercase the first letter of every word. and makes sure there is consistent casing throughout.
def clean_emp_title(title):
  if isinstance(title, str):
    return title.strip().title()
  else:
    return "Unknown"  
for example in examples:
  print(clean_emp_title(example))

Owner
Supervisor
Project Manager
Unknown

In [0]:
#Print out top 10 original emp_title column without applying changes
Loan_Stats['emp_title'].head(10)

0                        Staff Physician
1                      Director Of Sales
2                                Unknown
3                           Receptionist
4                    Extrusion Assistant
5                                Teacher
6                             Supervisor
7                                Analyst
8    Corporate Communications Strategist
9                        Project Manager
Name: emp_title, dtype: object

In [0]:
# Applies 'clean_emp_title' function to the emp_title column
# Then prints out the top 10 rows

Loan_Stats['emp_title'].apply(clean_emp_title).head(10)

0                        Staff Physician
1                      Director Of Sales
2                                Unknown
3                           Receptionist
4                    Extrusion Assistant
5                                Teacher
6                             Supervisor
7                                Analyst
8    Corporate Communications Strategist
9                        Project Manager
Name: emp_title, dtype: object

In [0]:
#Saves code back over
Loan_Stats['emp_title'] = Loan_Stats['emp_title'].apply(clean_emp_title)
Loan_Stats.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,int_rate_cleaned
0,35000,35000,35000.0,36 months,14.47%,1204.23,C,C2,Staff Physician,8 years,MORTGAGE,360000.0,Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,336xx,FL,19.90,0,Apr-1995,1,NaN,NaN,24,0,57259,43.2%,51,w,0.00,0.00,38187.046837,38187.05,35000.00,3187.05,0.0,0.0,0.0,Aug-2019,29882.16,NaN,Sep-2019,0,NaN,1,Individual,NaN,...,16,24,11,24,0.0,0,0,5,100.0,30.8,0,0,1222051,169286,124600,258401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,14.47
1,5000,5000,5000.0,36 months,22.35%,191.86,D,D5,Director Of Sales,10+ years,MORTGAGE,72000.0,Source Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,333xx,FL,20.12,0,Mar-2010,0,NaN,NaN,13,0,11720,47.1%,26,f,0.00,0.00,5615.977674,5615.98,5000.00,615.98,0.0,0.0,0.0,Jul-2019,4474.13,NaN,Aug-2019,0,NaN,1,Individual,NaN,...,11,17,11,13,0.0,0,0,1,100.0,50.0,0,0,218686,34418,18200,37786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,22.35
2,10000,10000,10000.0,60 months,23.40%,284.21,E,E1,Unknown,< 1 year,RENT,55000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,902xx,CA,13.51,0,Apr-2007,0,44.0,88.0,9,1,11859,53.9%,11,w,8462.43,8462.43,4243.650000,4243.65,1537.57,2706.08,0.0,0.0,0.0,Mar-2020,284.21,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,8,9,7,9,0.0,0,0,0,90.9,100.0,1,0,34386,21235,10500,12386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,23.40
3,17100,17100,17100.0,36 months,18.94%,626.30,D,D2,Receptionist,10+ years,RENT,38000.0,Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,150xx,PA,38.09,0,Mar-1998,1,47.0,NaN,14,0,15323,53%,21,w,11120.22,11120.22,9367.510000,9367.51,5979.78,3387.73,0.0,0.0,0.0,Mar-2020,626.30,Apr-2020,Mar-2020,0,NaN,1,Individual,NaN,...,12,14,9,14,NaN,0,0,2,95.0,75.0,0,0,70954,43351,16600,41784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,18.94
4,4000,4000,4000.0,36 months,10.72%,130.43,B,B2,Extrusion Assistant,10+ years,MORTGAGE,56000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,301xx,GA,31.03,0,Sep-2006,0,NaN,NaN,7,0,4518,28.6%,11,w,2487.19,2487.19,1943.360000,1943.36,1512.81,430.55,0.0,0.0,0.0,Mar-2020,130.43,Apr-2020,Mar-2020,1,NaN,1,Individual,NaN,...,4,4,4,7,0.0,0,0,0,100.0,0.0,0,0,221310,71375,12300,77865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,10.72

In [0]:
# list comprehensions can combine function calls and for loops over lists
# into one succint and fairly readable single line of code.

#[clean_emp_title(title) for title in examples]

In [0]:
# We have a function that works as expected. Let's apply it to our column.
# This time we;ll overwrite the original column.

In [0]:
##CHECK YOUR CODE!
# Look at the top 20 employment titles
Loan_Stats['emp_title'].value_counts().head(20)

Unknown                                128403
Teacher                                     1
Extrusion Assistant                         1
Project Manager                             1
Analyst                                     1
Corporate Communications Strategist         1
Staff Physician                             1
Receptionist                                1
Director Of Sales                           1
Supervisor                                  1
Name: emp_title, dtype: int64

In [0]:
# How many different unique employ,emt titles are there currently?
Loan_Stats['emp_title'].nunique()

10

In [0]:
# How often is the employment_title null (NaN)?
Loan_Stats['emp_title'].isnull().sum()

0

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

In [0]:
Loan_Stats['revol_util'].value_counts(dropna=False).head(20)

0%       1132
43%       225
49%       222
39.1%     220
32%       217
32.9%     216
28%       214
37.5%     213
44%       212
33%       211
51%       211
33.8%     211
34%       210
38%       210
29%       210
47%       208
33.3%     208
39%       205
37.3%     203
41%       203
Name: revol_util, dtype: int64

In [0]:
#def revol_util_to_float(dirty_revol_util):
#  return float(dirty_revol_util.strip().strip('%'))

In [0]:
#Test out function
x = '67.88%'
revol_util_to_float(x)

67.88

In [0]:
#check type
type(revol_util_to_float(x))

float

In [0]:
def clean_revol_util(title):
  if isinstance(title, str):
    return title.strip().strip('%')
  else:
    return 'Unknown'

Unknown

In [0]:
Loan_Stats['revol_util'].apply(revol_util_to_float)

AttributeError: ignored

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01