<a href="https://colab.research.google.com/github/gagansingh23/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module2-make-features/Gagan_DS11_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [9]:
#load data 
import pandas as pd

!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-12-03 20:35:34--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.2’

LoanStats_2018Q4.cs     [     <=>            ]  21.69M   417KB/s    in 54s

2019-12-03 20:36:28 (411 KB/s) - ‘LoanStats_2018Q4.csv.zip.2’ saved [22744357]

In [6]:
#unzip data
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [7]:
#use bash/shell to view raw files

!head LoanStats_2018Q4.csv
!tail LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 36 months"," 14.47%","688.13","C","C2","bus driver","4 years","OWN","52000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","681xx","NE","30.65","1","Jun-1979","2","15","","6","0","15048","73%","22","w","14777.99","14777.99","7481.0","7481.00","5222.01","2258.99","0.0","0.0","0.0","Nov-2019","688.13","Dec-2019","Nov-2019","0","","1","Individual","","","","0","0","33157","0","2","1","1","8","18109","44","1","2","8628","73","20700","1","1","4","3","5526","5175","73","0","0","141","474","10","8","0","10","15","1","15","0","4","4","11","12","8","4","14","4","6","","0","0","2","95","50","0","0","61699","33157","20700","40999","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","25000","25000","25000"," 60 months"," 16.14%","609.82","C","C4","Production Manager","5 years","MORTGAGE","45000","Not Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","703xx","LA","37.09","0","Sep-2003","0","","","7","0","8901","36.8%","21","w","0.00","0.00","26653.1675796436","26653.17","25000.00","1653.17","0.0","0.0","0.0","Apr-2019","24857.33","","May-2019","0","","1","Individual","","","","0","1303","49524","0","2","1","2","7","40623","82","0","0","7830","67","24200","2","0","1","2","7075","10465","43.7","0","0","161","162","45","7","4","96","","7","","0","2","3","3","5","7","5","10","3","7","0","0","0","1","100","33.3","0","0","73683","49524","18600","49483","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","26500","26500","26500"," 60 months"," 11.31%","580.28","B","B3","Compliance Director","10+ years","MORTGAGE","134000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","747xx","OK","18.91","0","Dec-2006","2","","","17","0","43640","65.4%","37","w","23051.06","23051.06","5777.82","5777.82","3448.94","2328.88","0.0","0.0","0.0","Oct-2019","580.28","Dec-2019","Nov-2019","0","","1","Individual","","","","0","0","381100","3","3","2","2","4","64335","46","1","3","10115","58","66700","2","1","7","6","22418","14577","70.4","0","0","114","144","3","3","4","22","","2","","0","8","10","9","10","7","13","26","10","17","0","0","0","4","100","66.7","0","0","430403","107975","49300","88875","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10400","10400","10400"," 36 months"," 12.98%","350.32","B","B5","Program Support Assistant ","10+ years","MORTGAGE","56099","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","800xx","CO","20.92","0","Jul-2013","2","32","67","8","1","1669","9.8%","10","w","7902.57","7902.57","3491.95","3491.95","2497.43","994.52","0.0","0.0","0.0","Oct-2019","350.32","Dec-2019","Nov-2019","0","","1","Individual","","","","0","0","39564","4","2","1","2","1","37895","92","3","6","725","36","17000","1","0","4","8","4946","15331","9.8","0","0","65","57","1","1","0","1","","0","32","0","3","3","6","6","3","6","7","3","8","0","0","0","4","90","0","1","0","60709","39564","17000","43709","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","35000","35000","35000"," 60 months"," 12.98%","796","B","B5","Sr. Vice President -Risk Manager","7 years","MORTGAGE","211646","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","797xx","TX","15.09","0","Sep-1985","0","77","","13","0","55944","74.9%","39","w","0.00","0.00","36266.741551619","36266.74","35000.00","1266.74","0.0","0.0","0.0","Apr-2019","34712.6","","Nov-2019","0","","1","Joint App","272421","15.89","Source Verified","0","0","420931","1","3","1","2","5","26570","51","0","2","24795","65","74700","1","6","1","4","32379","8677","85.5","0","0","152","399","21","5","6","21","77","12","77","0","6","8","6","11","14","9","19","8","13","0","0","0","1","97.4","66.7","0","0","516204","82514","59700","51904","88364","Sep-1985","0","6","19","53.4","2","29","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","20000","20000","20000"," 36 months","  7.56%","622.68","A","A3","Teacher","10+ years","MORTGAGE","100000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","982xx","WA","18.92","0","Feb-1999","0","48","","9","0","25416","29.9%","19","w","0.00","0.00","20215.79243","20215.79","20000.00","215.79","0.0","0.0","0.0","Feb-2019","20228.39","","Feb-2019","0","","1","Joint App","190000","11.75","Not Verified","0","0","515779","1","2","0","1","13","46153","71","1","2","9759","39","85100","2","2","0","5","57309","59684","29.9","0","0","171","238","1","1","5","1","","13","48","0","5","5","5","6","5","5","9","5","9","0","0","0","1","94.7","20","0","0","622183","71569","85100","74833","43287","Aug-1998","0","3","10","29.7","2","7","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 17.97%","469.79","D","D1","Help Tech Supervisor","10+ years","MORTGAGE","92360","Source Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","300xx","GA","27.44","0","Sep-2006","1","68","","18","0","32020","49.6%","30","w","10055.86","10055.86","4678.43","4678.43","2944.14","1734.29","0.0","0.0","0.0","Oct-2019","469.79","Dec-2019","Nov-2019","0","","1","Individual","","","","0","0","131919","1","2","1","3","4","17310","60","0","2","6116","53","64600","1","4","1","5","7760","7140","70.7","0","0","120","147","16","4","2","18","","4","70","0","5","12","6","7","6","15","22","12","18","0","0","0","1","90","66.7","0","0","190803","49330","24400","28861","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","12000","12000","12000"," 60 months"," 14.47%","282.16","C","C2","Assistant Athletic Director of Marketing","1 year","RENT","67000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","231xx","VA","28.39","0","Aug-2009","1","","","9","0","10018","50.9%","34","w","0.00","0.00","13140.1266634624","13140.13","12000.00","1140.13","0.0","0.0","0.0","Sep-2019","11169.83","","Nov-2019","0","","1","Individual","","","","0","0","184578","1","4","2","3","5","174560","97","0","1","4615","87","19700","1","1","2","4","20509","9682","50.9","0","0","112","80","23","5","0","23","","5","","0","3","3","5","5","26","5","8","3","9","0","0","0","2","100","0","0","0","183897","184578","19700","164197","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","3833.26","3833.26","2462.18","2462.18","1766.74","695.44","0.0","0.0","0.0","Nov-2019","190.21","Dec-2019","Nov-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","6892.70","6892.70","4499.54","4499.54","3107.30","1392.24","0.0","0.0","0.0","Nov-2019","346.76","Dec-2019","Nov-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3422.56","3422.56","2204.02","2204.02","1577.44","626.58","0.0","0.0","0.0","Nov-2019","169.83","Dec-2019","Nov-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","6763.16","6594.08","4244.48","4138.37","3236.84","1007.64","0.0","0.0","0.0","Nov-2019","327.68","Dec-2019","Nov-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","6953.72","6953.72","4619.65","4619.65","3046.28","1573.37","0.0","0.0","0.0","Nov-2019","356.08","Dec-2019","Nov-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [226]:
#view the data 

df = pd.read_csv('LoanStats_2018Q4.csv')
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128415, 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title                  emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt      total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       20000     20000       20000            36 months  14.47%  688.13      C     C2        bus driver                 4 years    OWN            52000      Source Verified     Dec-2018 Current     n          NaN NaN  debt_consolidation Debt consolidation      681xx    NE         30.65 1           Jun-1979         2              15                     NaN                    6        0       15048     73%        22        w                   14777.99  14777.99      7481.0           7481.00         5222.01         2258.99       0.0                0.0        0.0                     Nov-2019     688.13          Dec-2019     Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            33157       0           2           1           1           8                  18109        44      1           2           8628       73       20700            1      1           4            3                    5526        5175           73      0                        0           141                474                  10                    8              0        10                   15                       1                     15                             0                     4              4               11          12        8         4             14            4                   6        NaN              0            0                  2                  95             50               0                    0         61699           33157             20700          40999                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              25000     25000       25000            60 months  16.14%  609.82      C     C4        Production Manager         5 years    MORTGAGE       45000      Not Verified        Dec-2018 Fully Paid  n          NaN NaN  debt_consolidation Debt consolidation      703xx    LA         37.09 0           Sep-2003         0              NaN                    NaN                    7        0       8901      36.8%      21        w                   0.00      0.00          26653.1675796436 26653.17        25000.00        1653.17       0.0                0.0        0.0                     Apr-2019     24857.33        NaN          May-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              1303         49524       0           2           1           2           7                  40623        82      0           0           7830       67       24200            2      0           1            2                    7075        10465          43.7    0                        0           161                162                  45                    7              4        96                   NaN                      7                     NaN                            0                     2              3               3           5         7         5             10            3                   7        0                0            0                  1                  100            33.3             0                    0         73683           49524             18600          49483                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              26500     26500       26500            60 months  11.31%  580.28      B     B3        Compliance Director        10+ years  MORTGAGE       134000     Source Verified     Dec-2018 Current     n          NaN NaN  credit_card        Credit card refinancing 747xx    OK         18.91 0           Dec-2006         2              NaN                    NaN                    17       0       43640     65.4%      37        w                   23051.06  23051.06      5777.82          5777.82         3448.94         2328.88       0.0                0.0        0.0                     Oct-2019     580.28          Dec-2019     Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            381100      3           3           2           2           4                  64335        46      1           3           10115      58       66700            2      1           7            6                    22418       14577          70.4    0                        0           114                144                  3                     3              4        22                   NaN                      2                     NaN                            0                     8              10              9           10        7         13            26            10                  17       0                0            0                  4                  100            66.7             0                    0         430403          107975            49300          88875                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              10400     10400       10400            36 months  12.98%  350.32      B     B5        Program Support Assistant  10+ years  MORTGAGE       56099      Source Verified     Dec-2018 Current     n          NaN NaN  credit_card        Credit card refinancing 800xx    CO         20.92 0           Jul-2013         2              32                     67                     8        1       1669      9.8%       10        w                   7902.57   7902.57       3491.95          3491.95         2497.43         994.52        0.0                0.0        0.0                     Oct-2019     350.32          Dec-2019     Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            39564       4           2           1           2           1                  37895        92      3           6           725        36       17000            1      0           4            8                    4946        15331          9.8     0                        0           65                 57                   1                     1              0        1                    NaN                      0                     32                             0                     3              3               6           6         3         6             7             3                   8        0                0            0                  4                  90             0                1                    0         60709           39564             17000          43709                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

In [113]:
#fix header if column headers incorrect

df = pd.read_csv('LoanStats_2018Q4.csv', header=1)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [114]:
#find null values in each column and sort

pd.set_option('display.max_rows', 150)

df.isnull().sum().sort_values()

inq_fi                                             2
delinq_amnt                                        2
chargeoff_within_12_mths                           2
acc_open_past_24mths                               2
inq_last_12m                                       2
total_cu_tl                                        2
total_rev_hi_lim                                   2
max_bal_bc                                         2
open_rv_24m                                        2
open_rv_12m                                        2
total_bal_il                                       2
open_il_24m                                        2
hardship_flag                                      2
open_act_il                                        2
open_acc_6m                                        2
tot_cur_bal                                        2
tot_coll_amt                                       2
acc_now_delinq                                     2
application_type                                   2
policy_code                                        2
mo_sin_old_rev_tl_op                               2
mo_sin_rcnt_rev_tl_op                              2
mo_sin_rcnt_tl                                     2
mort_acc                                           2
total_il_high_credit_limit                         2
total_bc_limit                                     2
total_bal_ex_mort                                  2
tot_hi_cred_lim                                    2
tax_liens                                          2
pub_rec_bankruptcies                               2
pct_tl_nvr_dlq                                     2
num_tl_op_past_12m                                 2
num_tl_90g_dpd_24m                                 2
collections_12_mths_ex_med                         2
num_tl_30dpd                                       2
num_rev_tl_bal_gt_0                                2
num_rev_accts                                      2
num_op_rev_tl                                      2
num_il_tl                                          2
num_bc_tl                                          2
num_bc_sats                                        2
num_actv_rev_tl                                    2
num_actv_bc_tl                                     2
num_accts_ever_120_pd                              2
num_sats                                           2
last_pymnt_amnt                                    2
open_il_12m                                        2
debt_settlement_flag                               2
pub_rec                                            2
open_acc                                           2
grade                                              2
sub_grade                                          2
home_ownership                                     2
inq_last_6mths                                     2
annual_inc                                         2
verification_status                                2
earliest_cr_line                                   2
delinq_2yrs                                        2
issue_d                                            2
addr_state                                         2
zip_code                                           2
title                                              2
loan_status                                        2
pymnt_plan                                         2
installment                                        2
revol_bal                                          2
term                                               2
collection_recovery_fee                            2
loan_amnt                                          2
recoveries                                         2
total_rec_late_fee                                 2
funded_amnt                                        2
funded_amnt_inv                                    2
total_acc                                          2
total_rec_int                                      2
purpose                                            2
total_rec_prncp                                    2
total_pymnt_inv                                    2
total_pymnt                                        2
out_prncp_inv                                      2
out_prncp                                          2
initial_list_status                                2
int_rate                                           2
last_credit_pull_d                                 3
avg_cur_bal                                       15
all_util                                          39
revol_util                                       158
last_pymnt_d                                     161
dti                                              239
mths_since_recent_bc                            1593
bc_open_to_buy                                  1693
percent_bc_gt_75                                1694
bc_util                                         1756
num_tl_120dpd_2m                                2861
mths_since_rcnt_il                              4480
mo_sin_old_il_acct                              4480
emp_length                                     11706
mths_since_recent_inq                          16049
il_util                                        20276
emp_title                                      20949
next_pymnt_d                                   23980
mths_since_last_delinq                         72198
mths_since_recent_revol_delinq                 91632
mths_since_last_major_derog                    99234
mths_since_recent_bc_dlq                      103245
sec_app_open_acc                              111632
sec_app_mort_acc                              111632
sec_app_inq_last_6mths                        111632
sec_app_earliest_cr_line                      111632
revol_bal_joint                               111632
sec_app_open_act_il                           111632
annual_inc_joint                              111632
dti_joint                                     111632
sec_app_collections_12_mths_ex_med            111632
sec_app_chargeoff_within_12_mths              111632
sec_app_num_rev_accts                         111632
sec_app_revol_util                            111890
mths_since_last_record                        112964
verification_status_joint                     113566
sec_app_mths_since_last_major_derog           123260
debt_settlement_flag_date                     128078
settlement_date                               128078
settlement_amount                             128078
settlement_status                             128078
settlement_term                               128078
settlement_percentage                         128078
hardship_status                               128234
deferral_term                                 128234
hardship_amount                               128234
hardship_start_date                           128234
hardship_end_date                             128234
payment_plan_start_date                       128234
hardship_length                               128234
hardship_dpd                                  128234
hardship_loan_status                          128234
hardship_reason                               128234
hardship_payoff_balance_amount                128234
hardship_last_payment_amount                  128234
hardship_type                                 128234
orig_projected_additional_accrued_interest    128251
id                                            128412
url                                           128414
member_id                                     128414
desc                                          128414
dtype: int64

In [227]:
#have 2 null values because of footer, adress issue

df = pd.read_csv('LoanStats_2018Q4.csv', header=1, skipfooter=2)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

(128412, 144)

   id  member_id  ...  settlement_percentage  settlement_term
0 NaN        NaN  ...                    NaN              NaN
1 NaN        NaN  ...                    NaN              NaN
2 NaN        NaN  ...                    NaN              NaN
3 NaN        NaN  ...                    NaN              NaN
4 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [151]:
#check for Nan Values updated

df.isnull().sum().sort_values()

inq_fi                                             0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
total_cu_tl                                        0
total_rev_hi_lim                                   0
max_bal_bc                                         0
open_rv_24m                                        0
open_rv_12m                                        0
total_bal_il                                       0
open_il_24m                                        0
hardship_flag                                      0
open_act_il                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
tot_coll_amt                                       0
acc_now_delinq                                     0
application_type                                   0
policy_code                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
total_il_high_credit_limit                         0
total_bc_limit                                     0
total_bal_ex_mort                                  0
tot_hi_cred_lim                                    0
tax_liens                                          0
pub_rec_bankruptcies                               0
pct_tl_nvr_dlq                                     0
num_tl_op_past_12m                                 0
num_tl_90g_dpd_24m                                 0
collections_12_mths_ex_med                         0
num_tl_30dpd                                       0
num_rev_tl_bal_gt_0                                0
num_rev_accts                                      0
num_op_rev_tl                                      0
num_il_tl                                          0
num_bc_tl                                          0
num_bc_sats                                        0
num_actv_rev_tl                                    0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
num_sats                                           0
last_pymnt_amnt                                    0
open_il_12m                                        0
debt_settlement_flag                               0
pub_rec                                            0
open_acc                                           0
grade                                              0
sub_grade                                          0
home_ownership                                     0
inq_last_6mths                                     0
annual_inc                                         0
verification_status                                0
earliest_cr_line                                   0
delinq_2yrs                                        0
issue_d                                            0
addr_state                                         0
zip_code                                           0
title                                              0
loan_status                                        0
pymnt_plan                                         0
installment                                        0
revol_bal                                          0
term                                               0
collection_recovery_fee                            0
loan_amnt                                          0
recoveries                                         0
total_rec_late_fee                                 0
funded_amnt                                        0
funded_amnt_inv                                    0
total_acc                                          0
total_rec_int                                      0
purpose                                            0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
out_prncp_inv                                      0
out_prncp                                          0
initial_list_status                                0
int_rate                                           0
last_credit_pull_d                                 1
avg_cur_bal                                       13
all_util                                          37
revol_util                                       156
last_pymnt_d                                     159
dti                                              237
mths_since_recent_bc                            1591
bc_open_to_buy                                  1691
percent_bc_gt_75                                1692
bc_util                                         1754
num_tl_120dpd_2m                                2859
mths_since_rcnt_il                              4478
mo_sin_old_il_acct                              4478
emp_length                                     11704
mths_since_recent_inq                          16047
il_util                                        20274
emp_title                                      20947
next_pymnt_d                                   23978
mths_since_last_delinq                         72196
mths_since_recent_revol_delinq                 91630
mths_since_last_major_derog                    99232
mths_since_recent_bc_dlq                      103243
sec_app_open_acc                              111630
sec_app_mort_acc                              111630
sec_app_inq_last_6mths                        111630
sec_app_earliest_cr_line                      111630
revol_bal_joint                               111630
sec_app_open_act_il                           111630
annual_inc_joint                              111630
dti_joint                                     111630
sec_app_collections_12_mths_ex_med            111630
sec_app_chargeoff_within_12_mths              111630
sec_app_num_rev_accts                         111630
sec_app_revol_util                            111888
mths_since_last_record                        112962
verification_status_joint                     113564
sec_app_mths_since_last_major_derog           123258
debt_settlement_flag_date                     128076
settlement_date                               128076
settlement_amount                             128076
settlement_status                             128076
settlement_term                               128076
settlement_percentage                         128076
hardship_status                               128232
deferral_term                                 128232
hardship_amount                               128232
hardship_start_date                           128232
hardship_end_date                             128232
payment_plan_start_date                       128232
hardship_length                               128232
hardship_dpd                                  128232
hardship_loan_status                          128232
hardship_reason                               128232
hardship_payoff_balance_amount                128232
hardship_last_payment_amount                  128232
hardship_type                                 128232
orig_projected_additional_accrued_interest    128249
url                                           128412
member_id                                     128412
desc                                          128412
id                                            128412
dtype: int64

In [0]:
#get rid of blank columns which show number of entires = null values using drop function(axis means columns)

df = df.drop(['url', 'member_id', 'desc', 'id'], axis=1)
df.head()

In [28]:
df['int_rate'][2]

' 11.31%'

In [0]:
#fix one string at a time #leading space issue

int_rate = ' 11.31%'

In [0]:
#use .strip() to clear empty space if nothing between parentheses
int_rate.strip()

In [0]:
#use .strip() to remove percent sign
int_rate.strip('%')

In [0]:
#put both together to clean
int_rate.strip().strip('%')

In [0]:
#find value then typcast to change
type(int_rate.strip().strip('%'))

float(int_rate.strip().strip('%'))

type(float(int_rate.strip().strip('%')))

In [0]:
# declare a function so we can use it for the whole columns

def fix_rate(cell_c):
  return(float(cell_c.strip().strip('%')))

In [129]:
#test function 
fix_rate(int_rate)

11.31

In [130]:
#check datatype
type(fix_rate(int_rate))

float

In [0]:
#now the fun part, apply to every cell in our columns for df

df['int_rate_float'] = df['int_rate'].apply(fix_rate)
df.head(5)

In [0]:
#fix other values
df['emp_title'].value_counts(dropna=False)[:20]

In [62]:
#see how many different employee titles using len() function
len(df['emp_title'].value_counts())

34902

In [0]:
#how many null values for employment title using isnull().sum()
df['emp_title'].isnull().sum()

In [0]:

examples = ['owner', 'Supervior', 'Project Manager', np.NaN]

In [0]:
#start by fixing one example / .title() capitalizes and lowercases

def new_title(job_title):
  if isinstance(job_title, str):
    return job_title.title().strip()
  else:
    return "Unknown"

for title in examples:
  print(new_title(title))

In [0]:
#apply new function to column overwrite original column

df['emp_title'] = df['emp_title'].apply(new_title)

df.head(100)

In [0]:
df['emp_title'].value_counts(dropna=False,ascending=False)[:20]

In [133]:
#check for null values
df['emp_title'].isnull().sum()

20949

In [156]:
df['term'].value_counts()

 36 months    88179
 60 months    40233
Name: term, dtype: int64

In [155]:
#convert term column from string to int
df['term'].value_counts(dropna=False)

 36 months    88179
 60 months    40233
Name: term, dtype: int64

In [157]:
#declare a function to change string to int
df['term'][1]

' 60 months'

In [163]:
#apply function to term column every cell
#small steps to create function 
term_s = ' 48 month'
term_s.strip('month')

' 48 '

In [164]:
int(term_s.strip('month'))

48

In [165]:
type(int(term_s.strip('month')))

int

In [0]:
#create a function
def convert_to_int(cell_contents):
  return (int(cell_contents.strip('months')))

In [268]:
#CONVERT TERM COLUMN FROM STRING TO INT
df['term'] = df['term'].apply(convert_to_int)
df.head()

   id  member_id  ...  last_pymnt_d_year  last_payment_d_month
0 NaN        NaN  ...               2018                    12
1 NaN        NaN  ...               2018                    12
2 NaN        NaN  ...               2018                    12
3 NaN        NaN  ...               2018                    12
4 NaN        NaN  ...               2018                    12

[5 rows x 149 columns]

In [269]:
df.dtypes['term']

dtype('int64')

In [0]:
Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.

Make last_pymnt_d_month and last_pymnt_d_year columns.

In [228]:
#Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.
df['loan_status'].head()

0       Current
1    Fully Paid
2       Current
3       Current
4    Fully Paid
Name: loan_status, dtype: object

In [0]:
#create a function for new column
def f(loan_status):
  if (loan_status) == "Current" or  (loan_status) == "Fully Paid":
    return 1
  else: 
    return 0

In [271]:
#NEW COLUMN LOAN_STATUS_IS_GREAT
df['loan_status_is_great'] = df['loan_status'].apply(f)


df['loan_status_is_great'].tail(10)

128402    1
128403    1
128404    1
128405    1
128406    1
128407    0
128408    1
128409    1
128410    1
128411    1
Name: loan_status_is_great, dtype: int64

In [235]:
#verify the codes correspond correctly
df['loan_status'].tail(10)

128402        Current
128403        Current
128404        Current
128405     Fully Paid
128406        Current
128407    Charged Off
128408        Current
128409        Current
128410        Current
128411        Current
Name: loan_status, dtype: object

In [242]:
#DT FORMAT 

[col for col in df if col.endswith('_d')]

['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d']

In [272]:
df['issue_d'] = pd.to_datetime(df['issue_d'], infer_datetime_format=True)

df.dtypes[:15]

id                     float64
member_id              float64
loan_amnt                int64
funded_amnt              int64
funded_amnt_inv        float64
term                     int64
int_rate                object
installment            float64
grade                   object
sub_grade               object
emp_title               object
emp_length              object
home_ownership          object
annual_inc             float64
verification_status     object
dtype: object

In [0]:
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

In [275]:
#Make last_pymnt_d_month and last_pymnt_d_year columns
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year
df['last_payment_d_month'] = df['last_pymnt_d'].dt.month

df.tail()

        id  member_id  ...  last_pymnt_d_year  last_payment_d_month
128407 NaN        NaN  ...               2018                    10
128408 NaN        NaN  ...               2018                    10
128409 NaN        NaN  ...               2018                    10
128410 NaN        NaN  ...               2018                    10
128411 NaN        NaN  ...               2018                    10

[5 rows x 149 columns]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01